<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramHighlight;
use OpenHandle\Models\InstagramPost;
use OpenHandle\Models\InstagramProfile;
use OpenHandle\Models\InstagramStory;
use OpenHandle\Models\RedditPost;
use OpenHandle\Models\RedditProfile;
use OpenHandle\Models\RedditSubreddit;
use OpenHandle\Models\TikTokPost;
use OpenHandle\Models\TikTokProfile;
use OpenHandle\Models\TwitterPost;
use OpenHandle\Models\TwitterProfile;
use OpenHandle\Response;

/**
 * The generated resource graph shared by every OpenHandle client.
 */
abstract class GeneratedClient
{
    public readonly InstagramResource $instagram;

    public readonly RedditResource $reddit;

    public readonly TestDataResource $testData;

    public readonly TikTokResource $tiktok;

    public readonly TwitterResource $twitter;

    public function __construct(private readonly Transport $transport)
    {
        $this->instagram = new InstagramResource($transport, []);
        $this->reddit = new RedditResource($transport, []);
        $this->testData = new TestDataResource($transport, []);
        $this->tiktok = new TikTokResource($transport, []);
        $this->twitter = new TwitterResource($transport, []);
    }

    /**
     * Fetch the resource at a social URL
     *
     * Parse a supported social URL locally, then return the same typed resource as its canonical
     * Openhandle operation. TikTok short links such as tiktok.com/t/… and vm.tiktok.com/… are expanded
     * through their redirect first. The underlying data read is metered once.
     *
     * Example:
     *     $openhandle->fetch('https://www.instagram.com/openai/', freshness: '24h');
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<InstagramProfile|InstagramPost|InstagramStory|InstagramHighlight|TikTokProfile|TikTokPost|TwitterProfile|TwitterPost|RedditProfile|RedditPost|RedditSubreddit>
     */
    public function fetch(string $url, ?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        if (trim($url) === '') {
            throw new \InvalidArgumentException('fetch($url) requires a non-empty social URL.');
        }
        $body = ['url' => $url];
        if ($freshness !== null) {
            $body['freshness'] = $freshness;
        }

        return $this->transport->response(
            'post',
            '/v1/urls/fetch',
            [],
            [],
            $body,
            $timeout,
            $maxRetries,
            static function (mixed $data, array $envelope): InstagramProfile|InstagramPost|InstagramStory|InstagramHighlight|TikTokProfile|TikTokPost|TwitterProfile|TwitterPost|RedditProfile|RedditPost|RedditSubreddit {
                $platform = Wire::string($envelope['platform'] ?? null, 'platform');
                $resource = Wire::string($envelope['resource'] ?? null, 'resource');
                $fields = Wire::map($data, 'data');

                return match (true) {
                    $platform === 'instagram' && $resource === 'profile' => InstagramProfile::fromArray($fields),
                    $platform === 'instagram' && $resource === 'post' => InstagramPost::fromArray($fields),
                    $platform === 'instagram' && $resource === 'entity' => Wire::variant($fields, [
                        InstagramStory::class => ['ai', 'attribution', 'caption', 'carousel', 'code', 'collaborators', 'comments', 'crossposting', 'expiresAt', 'extracted', 'fbid', 'hasDelayedMetadata', 'hasTaggedUsers', 'hasVisualReplies', 'highlights', 'invitedCollaborators', 'isEarlyAccess', 'isEdited', 'isFanClubPromo', 'isLastVideoSegment', 'isOpenToPublicSubmission', 'isPaidPartnership', 'isPublicChatWelcomeVideo', 'language', 'likeAndViewCountsHidden', 'location', 'media', 'notes', 'pinning', 'productTags', 'remix', 'reuse', 'shareCountHidden', 'sharingEnabled', 'stickers', 'taggedUsers', 'template', 'text', 'type'],
                        InstagramHighlight::class => ['cover', 'isArchived', 'isConvertedToReel', 'isInProfileGrid', 'isPinned', 'lastStoryAt', 'stories', 'updatedAt'],
                    ])::fromArray($fields),
                    $platform === 'tiktok' && $resource === 'profile' => TikTokProfile::fromArray($fields),
                    $platform === 'tiktok' && $resource === 'post' => TikTokPost::fromArray($fields),
                    $platform === 'twitter' && $resource === 'profile' => TwitterProfile::fromArray($fields),
                    $platform === 'twitter' && $resource === 'post' => TwitterPost::fromArray($fields),
                    $platform === 'reddit' && $resource === 'profile' => RedditProfile::fromArray($fields),
                    $platform === 'reddit' && $resource === 'post' => RedditPost::fromArray($fields),
                    $platform === 'reddit' && $resource === 'subreddit' => RedditSubreddit::fromArray($fields),
                    default => throw Wire::invalid('data', "a supported fetch resource, not {$platform} {$resource}"),
                };
            },
        );
    }
}
