<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramComment;
use OpenHandle\Page;

final class InstagramPostCommentRepliesResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List comment replies
     *
     * Return a stable page of replies for one comment. Use find_test_data to discover compatible post and
     * comment IDs. Test and Live use the same route, parameters, response schema, pagination, and errors.
     * In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->instagram->post('910100000001')->comment('910200000001')->replies->list(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/instagram-comment-replies-list
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<InstagramComment>
     */
    public function list(?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/instagram/posts/{identifier}/comments/{comment_id}/replies',
            $this->bindings,
            ['freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): InstagramComment => Wire::object($item, $path, InstagramComment::class),
        );
    }

    /**
     * Iterate items lazily across pages of instagram.post.comment.replies.list, one request per page.
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, InstagramComment, mixed, void>
     */
    public function items(?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
