<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramPost;
use OpenHandle\Response;

final class InstagramPostResource
{
    public readonly InstagramPostClipMetadataResource $clipMetadata;

    public readonly InstagramPostCommentMetadataResource $commentMetadata;

    public readonly InstagramPostCommentModerationResource $commentModeration;

    public readonly InstagramPostCommentsResource $comments;

    public readonly InstagramPostInsightsResource $insights;

    public readonly InstagramPostLikersResource $likers;

    public readonly InstagramPostOEmbedResource $oembed;

    public readonly InstagramPostTaggedUsersResource $taggedUsers;

    public readonly InstagramPostTemplateResource $template;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->clipMetadata = new InstagramPostClipMetadataResource($transport, $bindings);
        $this->commentMetadata = new InstagramPostCommentMetadataResource($transport, $bindings);
        $this->commentModeration = new InstagramPostCommentModerationResource($transport, $bindings);
        $this->comments = new InstagramPostCommentsResource($transport, $bindings);
        $this->insights = new InstagramPostInsightsResource($transport, $bindings);
        $this->likers = new InstagramPostLikersResource($transport, $bindings);
        $this->oembed = new InstagramPostOEmbedResource($transport, $bindings);
        $this->taggedUsers = new InstagramPostTaggedUsersResource($transport, $bindings);
        $this->template = new InstagramPostTemplateResource($transport, $bindings);
    }

    /**
     * Select the comment resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function comment(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramPostCommentResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'comment');

        return new InstagramPostCommentResource($this->transport, [...$this->bindings, 'comment_id' => $identifier]);
    }

    /**
     * Get a post
     *
     * Get a post by a canonical platform identifier. URLs must be converted before calling a data
     * endpoint. Test and Live use the same route, parameters, response schema, pagination, and errors. In
     * Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->instagram->post('910100000001')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/instagram-post-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<InstagramPost>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/instagram/posts/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): InstagramPost => Wire::object($data, 'data', InstagramPost::class),
        );
    }
}
