<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramProfile;
use OpenHandle\Page;

final class InstagramCommentLikersResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List comment likers
     *
     * List comment likers from public Instagram data. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->instagram->comment('910100000001')->likers->list(mediaId: '910100000001', freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/instagram-comment-likers-list
     *
     * @param string $mediaId Opaque native media ID associated with the selected resource.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<InstagramProfile>
     */
    public function list(string $mediaId, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/instagram/comments/{identifier}/likers',
            $this->bindings,
            ['media_id' => $mediaId, 'freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): InstagramProfile => Wire::object($item, $path, InstagramProfile::class),
        );
    }

    /**
     * Iterate items lazily across pages of instagram.comment.likers.list, one request per page.
     *
     * @param string $mediaId Opaque native media ID associated with the selected resource.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, InstagramProfile, mixed, void>
     */
    public function items(string $mediaId, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(mediaId: $mediaId, freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
