<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramHashtag;
use OpenHandle\Response;

final class InstagramHashtagResource
{
    public readonly InstagramHashtagPostsResource $posts;

    public readonly InstagramHashtagReelsResource $reels;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->posts = new InstagramHashtagPostsResource($transport, $bindings);
        $this->reels = new InstagramHashtagReelsResource($transport, $bindings);
    }

    /**
     * Get a hashtag
     *
     * Return one public hashtag by its native identifier. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->instagram->hashtag('syntheticvolume')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/instagram-hashtag-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<InstagramHashtag>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/instagram/hashtags/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): InstagramHashtag => Wire::object($data, 'data', InstagramHashtag::class),
        );
    }
}
