<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\InstagramCommentMetadata;
use OpenHandle\Response;

final class InstagramPostCommentMetadataResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Get comment metadata
     *
     * Get comment metadata from public Instagram data. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->instagram->post('910100000001')->commentMetadata->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/instagram-post-comment-metadata-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<InstagramCommentMetadata>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/instagram/posts/{identifier}/comment-metadata',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): InstagramCommentMetadata => Wire::object($data, 'data', InstagramCommentMetadata::class),
        );
    }
}
