<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;

final class InstagramResource
{
    public readonly InstagramSearchResource $search;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->search = new InstagramSearchResource($transport, $bindings);
    }

    /**
     * Select the comment resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function comment(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramCommentResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'comment');

        return new InstagramCommentResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the hashtag resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function hashtag(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramHashtagResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'hashtag');

        return new InstagramHashtagResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the highlight resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function highlight(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramHighlightResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'highlight');

        return new InstagramHighlightResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the location resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function location(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramLocationResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'location');

        return new InstagramLocationResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the music resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function music(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramMusicResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'music');

        return new InstagramMusicResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the post resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function post(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramPostResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'post');

        return new InstagramPostResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the profile resource using a username shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the username, id, or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $username
     * @param string|null $id
     * @param string|null $url
     */
    public function profile(mixed $reference = null, mixed $username = null, mixed $id = null, mixed $url = null): InstagramProfileResource
    {
        $identifier = References::selector($reference, $username, $id, $url, 'instagram', 'profile');

        return new InstagramProfileResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the story resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function story(mixed $reference = null, mixed $id = null, mixed $url = null): InstagramStoryResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'instagram', 'story');

        return new InstagramStoryResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }
}
