<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\RedditRule;
use OpenHandle\Response;

final class RedditSubredditRulesResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List subreddit rules
     *
     * List subreddit rules from public Reddit data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->reddit->subreddit('synthetic')->rules->list(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/reddit-subreddit-rules-list
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<list<RedditRule>>
     */
    public function list(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/reddit/subreddits/{identifier}/rules',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): array => Wire::list($data, 'data', static fn(mixed $item, string $path): RedditRule => Wire::object($item, $path, RedditRule::class)),
        );
    }
}
