<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\RedditProfile;
use OpenHandle\Response;

final class RedditProfileResource
{
    public readonly RedditProfileCommentsResource $comments;

    public readonly RedditProfileModeratedResource $moderated;

    public readonly RedditProfilePostsResource $posts;

    public readonly RedditProfileTrophiesResource $trophies;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->comments = new RedditProfileCommentsResource($transport, $bindings);
        $this->moderated = new RedditProfileModeratedResource($transport, $bindings);
        $this->posts = new RedditProfilePostsResource($transport, $bindings);
        $this->trophies = new RedditProfileTrophiesResource($transport, $bindings);
    }

    /**
     * Get a profile
     *
     * Return one public Reddit profile. Use @username or a t2_ profile ID. An ID resolves only after the
     * profile was read by username once. Test and Live use the same route, parameters, response schema,
     * pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->reddit->profile('@synthetic_reddit')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/reddit-profile-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<RedditProfile>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/reddit/profiles/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): RedditProfile => Wire::object($data, 'data', RedditProfile::class),
        );
    }
}
