<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;

final class RedditResource
{
    public readonly RedditSearchResource $search;

    public readonly RedditSubredditsResource $subreddits;

    public readonly RedditTrendingResource $trending;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->search = new RedditSearchResource($transport, $bindings);
        $this->subreddits = new RedditSubredditsResource($transport, $bindings);
        $this->trending = new RedditTrendingResource($transport, $bindings);
    }

    /**
     * Select the domain resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function domain(mixed $reference = null, mixed $id = null, mixed $url = null): RedditDomainResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'reddit', 'domain');

        return new RedditDomainResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the post resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function post(mixed $reference = null, mixed $id = null, mixed $url = null): RedditPostResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'reddit', 'post');

        return new RedditPostResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the profile resource using a username shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the username, id, or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $username
     * @param string|null $id
     * @param string|null $url
     */
    public function profile(mixed $reference = null, mixed $username = null, mixed $id = null, mixed $url = null): RedditProfileResource
    {
        $identifier = References::selector($reference, $username, $id, $url, 'reddit', 'profile');

        return new RedditProfileResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }

    /**
     * Select the subreddit resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function subreddit(mixed $reference = null, mixed $id = null, mixed $url = null): RedditSubredditResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'reddit', 'subreddit');

        return new RedditSubredditResource($this->transport, [...$this->bindings, 'identifier' => $identifier]);
    }
}
