<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\RedditSubreddit;
use OpenHandle\Response;

final class RedditSubredditResource
{
    public readonly RedditSubredditPostsResource $posts;

    public readonly RedditSubredditRulesResource $rules;

    public readonly RedditSubredditWikiPagesResource $wikiPages;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->posts = new RedditSubredditPostsResource($transport, $bindings);
        $this->rules = new RedditSubredditRulesResource($transport, $bindings);
        $this->wikiPages = new RedditSubredditWikiPagesResource($transport, $bindings);
    }

    /**
     * Select the wikiPage resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function wikiPage(mixed $reference = null, mixed $id = null, mixed $url = null): RedditSubredditWikiPageResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'reddit', 'wikiPage');

        return new RedditSubredditWikiPageResource($this->transport, [...$this->bindings, 'page' => $identifier]);
    }

    /**
     * Get a subreddit
     *
     * Get a subreddit from public Reddit data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->reddit->subreddit('synthetic')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/reddit-subreddit-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<RedditSubreddit>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/reddit/subreddits/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): RedditSubreddit => Wire::object($data, 'data', RedditSubreddit::class),
        );
    }
}
