<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\RedditPost;
use OpenHandle\Page;

final class RedditSubredditPostsResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List subreddit posts
     *
     * List subreddit posts from public Reddit data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->reddit->subreddit('synthetic')->posts->list(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/reddit-subreddit-posts-list
     *
     * @param 'hot'|'new'|'top'|'rising'|'controversial'|null $sort Result ordering for this operation.
     * @param 'hour'|'day'|'week'|'month'|'year'|'all'|null $t Time window for top and controversial results.
     * @param int|null $limit Maximum number of results to return.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<RedditPost>
     */
    public function list(?string $sort = null, ?string $t = null, ?int $limit = null, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/reddit/subreddits/{identifier}/posts',
            $this->bindings,
            ['sort' => $sort, 't' => $t, 'limit' => $limit, 'freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): RedditPost => Wire::object($item, $path, RedditPost::class),
        );
    }

    /**
     * Iterate items lazily across pages of reddit.subreddit.posts.list, one request per page.
     *
     * @param 'hot'|'new'|'top'|'rising'|'controversial'|null $sort Result ordering for this operation.
     * @param 'hour'|'day'|'week'|'month'|'year'|'all'|null $t Time window for top and controversial results.
     * @param int|null $limit Maximum number of results to return.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, RedditPost, mixed, void>
     */
    public function items(?string $sort = null, ?string $t = null, ?int $limit = null, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(sort: $sort, t: $t, limit: $limit, freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
