<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\RedditComment;
use OpenHandle\Response;

final class RedditPostCommentsResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List post comments
     *
     * List post comments from public Reddit data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->reddit->post('synthetic')->comments->list(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/reddit-post-comments-list
     *
     * @param 'confidence'|'top'|'new'|'controversial'|'old'|'qa'|null $sort Result ordering for this operation.
     * @param int|null $limit Maximum number of results to return.
     * @param int|null $depth Maximum depth of nested replies.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<list<RedditComment>>
     */
    public function list(?string $sort = null, ?int $limit = null, ?int $depth = null, ?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/reddit/posts/{identifier}/comments',
            $this->bindings,
            ['sort' => $sort, 'limit' => $limit, 'depth' => $depth, 'freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): array => Wire::list($data, 'data', static fn(mixed $item, string $path): RedditComment => Wire::object($item, $path, RedditComment::class)),
        );
    }
}
