<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TestDataCatalog;
use OpenHandle\Response;

final class TestDataResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Select the testDataEntry resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function entry(mixed $reference = null, mixed $id = null, mixed $url = null): TestDataEntryResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'testData', 'testDataEntry');

        return new TestDataEntryResource($this->transport, [...$this->bindings, 'id' => $identifier]);
    }

    /**
     * Search the synthetic test-data catalog
     *
     * Public, unmetered discovery. Filter by platform, resource, operation, traits, expected status, error
     * code, or text.
     *
     * Example:
     *     $openhandle->testData->list();
     *
     * @param 'instagram'|'tiktok'|'twitter'|'reddit'|null $platform Provider-specific public-data filter for this operation.
     * @param 'profile'|'post'|'comment'|'hashtag'|'location'|'music'|'category'|'list'|'entity'|'subreddit'|'rule'|'wiki'|'trophy'|null $resource Provider-specific public-data filter for this operation.
     * @param string|null $operation Provider-specific public-data filter for this operation.
     * @param string|null $traits Provider-specific public-data filter for this operation.
     * @param int|null $status Provider-specific public-data filter for this operation.
     * @param string|null $errorCode Provider-specific public-data filter for this operation.
     * @param string|null $search Provider-specific public-data filter for this operation.
     * @param int|null $limit Maximum number of results to return.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TestDataCatalog>
     */
    public function list(?string $platform = null, ?string $resource = null, ?string $operation = null, ?string $traits = null, ?int $status = null, ?string $errorCode = null, ?string $search = null, ?int $limit = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/test-data',
            $this->bindings,
            ['platform' => $platform, 'resource' => $resource, 'operation' => $operation, 'traits' => $traits, 'status' => $status, 'errorCode' => $errorCode, 'search' => $search, 'limit' => $limit],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TestDataCatalog => Wire::object($data, 'data', TestDataCatalog::class),
        );
    }
}
