<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TestDataEntry;
use OpenHandle\Response;

final class TestDataEntryResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Get one synthetic catalog entry
     *
     * Example:
     *     $openhandle->testData->entry('<id>')->get();
     *
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TestDataEntry>
     */
    public function get(?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/test-data/{id}',
            $this->bindings,
            [],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TestDataEntry => Wire::object($data, 'data', TestDataEntry::class),
        );
    }
}
