<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokMusic;
use OpenHandle\Page;

final class TikTokTrendingMusicResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * List trending music
     *
     * Return TikTok's public Top 50 music chart for the configured provider region. Test and Live use the
     * same route, parameters, response schema, pagination, and errors. In Test, null means unavailable,
     * not zero.
     *
     * Example:
     *     $openhandle->tiktok->trending->music->list(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-trending-music-list
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<TikTokMusic>
     */
    public function list(?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/tiktok/trending/music',
            $this->bindings,
            ['freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): TikTokMusic => Wire::object($item, $path, TikTokMusic::class),
        );
    }

    /**
     * Iterate items lazily across pages of tiktok.trending.music.list, one request per page.
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, TikTokMusic, mixed, void>
     */
    public function items(?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
