<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokProfile;
use OpenHandle\Page;

final class TikTokSearchProfilesResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Search Tiktok profiles
     *
     * Search public Tiktok profiles with cursor pagination. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->tiktok->search->profiles->list(q: 'synthetic', freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-search-profiles-list
     *
     * @param string $q Public search query.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<TikTokProfile>
     */
    public function list(string $q, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/tiktok/search/profiles',
            $this->bindings,
            ['q' => $q, 'freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): TikTokProfile => Wire::object($item, $path, TikTokProfile::class),
        );
    }

    /**
     * Iterate items lazily across pages of tiktok.search.profiles.list, one request per page.
     *
     * @param string $q Public search query.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, TikTokProfile, mixed, void>
     */
    public function items(string $q, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(q: $q, freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
