<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokPlaylist;
use OpenHandle\Response;

final class TikTokProfilePlaylistResource
{
    public readonly TikTokProfilePlaylistPostsResource $posts;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->posts = new TikTokProfilePlaylistPostsResource($transport, $bindings);
    }

    /**
     * Get a playlist
     *
     * Get a playlist from public Tiktok data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->tiktok->profile('@pixel_orchard_tt_test')->playlist('950000000006')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-profile-playlist-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TikTokPlaylist>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/tiktok/profiles/{identifier}/playlists/{playlist_id}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TikTokPlaylist => Wire::object($data, 'data', TikTokPlaylist::class),
        );
    }
}
