<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokEffect;
use OpenHandle\Page;

final class TikTokEffectsResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Get effects in a batch
     *
     * Get effects in a batch from public Tiktok data. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->tiktok->effects->list(ids: '950000000007', freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-effects-list
     *
     * @param string $ids Comma-separated opaque native IDs.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<TikTokEffect>
     */
    public function list(string $ids, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/tiktok/effects',
            $this->bindings,
            ['ids' => $ids, 'freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): TikTokEffect => Wire::object($item, $path, TikTokEffect::class),
        );
    }

    /**
     * Iterate items lazily across pages of tiktok.effects.list, one request per page.
     *
     * @param string $ids Comma-separated opaque native IDs.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, TikTokEffect, mixed, void>
     */
    public function items(string $ids, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(ids: $ids, freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
