<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;

final class TikTokTrendingResource
{
    public readonly TikTokTrendingCategoriesResource $categories;

    public readonly TikTokTrendingMusicResource $music;

    public readonly TikTokTrendingPostsResource $posts;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        Transport $transport,
        array $bindings,
    ) {
        $this->categories = new TikTokTrendingCategoriesResource($transport, $bindings);
        $this->music = new TikTokTrendingMusicResource($transport, $bindings);
        $this->posts = new TikTokTrendingPostsResource($transport, $bindings);
    }
}
