<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokProfile;
use OpenHandle\Response;

final class TikTokProfileResource
{
    public readonly TikTokProfileFollowersResource $followers;

    public readonly TikTokProfileFollowingResource $following;

    public readonly TikTokProfileLikedPostsResource $likedPosts;

    public readonly TikTokProfilePlaylistsResource $playlists;

    public readonly TikTokProfilePostsResource $posts;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->followers = new TikTokProfileFollowersResource($transport, $bindings);
        $this->following = new TikTokProfileFollowingResource($transport, $bindings);
        $this->likedPosts = new TikTokProfileLikedPostsResource($transport, $bindings);
        $this->playlists = new TikTokProfilePlaylistsResource($transport, $bindings);
        $this->posts = new TikTokProfilePostsResource($transport, $bindings);
    }

    /**
     * Select the playlist resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function playlist(mixed $reference = null, mixed $id = null, mixed $url = null): TikTokProfilePlaylistResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'tiktok', 'playlist');

        return new TikTokProfilePlaylistResource($this->transport, [...$this->bindings, 'playlist_id' => $identifier]);
    }

    /**
     * Get a profile
     *
     * Return one public profile. Use @username or a platform ID as the identifier. Test and Live use the
     * same route, parameters, response schema, pagination, and errors. In Test, null means unavailable,
     * not zero.
     *
     * Example:
     *     $openhandle->tiktok->profile('@pixel_orchard_tt_test')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-profile-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TikTokProfile>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/tiktok/profiles/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TikTokProfile => Wire::object($data, 'data', TikTokProfile::class),
        );
    }
}
