<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TikTokEffect;
use OpenHandle\Response;

final class TikTokEffectResource
{
    public readonly TikTokEffectPostsResource $posts;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->posts = new TikTokEffectPostsResource($transport, $bindings);
    }

    /**
     * Get an effect
     *
     * Get an effect from public Tiktok data. Test and Live use the same route, parameters, response
     * schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->tiktok->effect('920100000000000001')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/tiktok-effect-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TikTokEffect>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/tiktok/effects/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TikTokEffect => Wire::object($data, 'data', TikTokEffect::class),
        );
    }
}
