<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\Transport;

final class TwitterListResource
{
    public readonly TwitterListPostsResource $posts;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        Transport $transport,
        array $bindings,
    ) {
        $this->posts = new TwitterListPostsResource($transport, $bindings);
    }
}
