<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use Generator;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TwitterPost;
use OpenHandle\Page;

final class TwitterSearchMediaResource
{
    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
    }

    /**
     * Search Twitter media
     *
     * Search public Twitter media with cursor pagination. Test and Live use the same route, parameters,
     * response schema, pagination, and errors. In Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->twitter->search->media->list(q: 'synthetic', type: 'image', freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/twitter-search-media-list
     *
     * @param string $q Public search query.
     * @param 'image'|'video' $type Media type filter.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Page<TwitterPost>
     */
    public function list(string $q, string $type, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Page
    {
        return $this->transport->page(
            'get',
            '/v1/twitter/search/media',
            $this->bindings,
            ['q' => $q, 'type' => $type, 'freshness' => $freshness, 'cursor' => $cursor],
            $timeout,
            $maxRetries,
            static fn(mixed $item, string $path): TwitterPost => Wire::object($item, $path, TwitterPost::class),
        );
    }

    /**
     * Iterate items lazily across pages of twitter.search.media.list, one request per page.
     *
     * @param string $q Public search query.
     * @param 'image'|'video' $type Media type filter.
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param string|null $cursor Opaque cursor returned by the previous page.
     * @param float|null $timeout Request timeout in seconds for each page.
     * @param int|null $maxRetries Retry limit for each page.
     *
     * @return Generator<int, TwitterPost, mixed, void>
     */
    public function items(string $q, string $type, ?string $freshness = null, ?string $cursor = null, ?float $timeout = null, ?int $maxRetries = null): Generator
    {
        $page = $this->list(q: $q, type: $type, freshness: $freshness, cursor: $cursor, timeout: $timeout, maxRetries: $maxRetries);
        while ($page !== null) {
            yield from $page->data;
            $page = $page->next();
        }
    }
}
