<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Resources;

use OpenHandle\Internal\References;
use OpenHandle\Internal\Transport;
use OpenHandle\Internal\Wire;
use OpenHandle\Models\TwitterPost;
use OpenHandle\Response;

final class TwitterPostResource
{
    public readonly TwitterPostCommentsResource $comments;

    public readonly TwitterPostRepostersResource $reposters;

    /**
     * @internal
     *
     * @param array<string, string> $bindings
     */
    public function __construct(
        private readonly Transport $transport,
        private readonly array $bindings,
    ) {
        $this->comments = new TwitterPostCommentsResource($transport, $bindings);
        $this->reposters = new TwitterPostRepostersResource($transport, $bindings);
    }

    /**
     * Select the comment resource using a supported string shorthand or an explicit ID or URL reference.
     *
     * Pass a raw string, or exactly one of the id or url named arguments.
     * IDs are opaque strings. Resource selection does not perform a request.
     *
     * @param string|null $reference
     * @param string|null $id
     * @param string|null $url
     */
    public function comment(mixed $reference = null, mixed $id = null, mixed $url = null): TwitterPostCommentResource
    {
        $identifier = References::selector($reference, null, $id, $url, 'twitter', 'comment');

        return new TwitterPostCommentResource($this->transport, [...$this->bindings, 'comment_id' => $identifier]);
    }

    /**
     * Get a post
     *
     * Get a post by a canonical platform identifier. URLs must be converted before calling a data
     * endpoint. Test and Live use the same route, parameters, response schema, pagination, and errors. In
     * Test, null means unavailable, not zero.
     *
     * Example:
     *     $openhandle->twitter->post('940100000000000001')->get(freshness: '24h');
     *
     * @see https://openhandle.dev/docs/api-reference/twitter-post-get
     *
     * @param 'live'|'24h'|'7d'|'30d'|null $freshness Maximum accepted data age. The default is 24h.
     * @param float|null $timeout Request timeout in seconds for this call.
     * @param int|null $maxRetries Retry limit for this call.
     *
     * @return Response<TwitterPost>
     */
    public function get(?string $freshness = null, ?float $timeout = null, ?int $maxRetries = null): Response
    {
        return $this->transport->response(
            'get',
            '/v1/twitter/posts/{identifier}',
            $this->bindings,
            ['freshness' => $freshness],
            null,
            $timeout,
            $maxRetries,
            static fn(mixed $data): TwitterPost => Wire::object($data, 'data', TwitterPost::class),
        );
    }
}
