<?php

declare(strict_types=1);

/*
 * Generate the typed OpenHandle SDK sources from the pinned OpenAPI contract.
 *
 * Usage: php scripts/generate.php [--check] [--input=openapi/openhandle.json]
 */

namespace OpenHandle\Generator;

use RuntimeException;

const PACKAGE_ROOT = __DIR__ . '/..';
const GENERATED_HEADER = "<?php\n\n// Generated by scripts/generate.php. Do not edit.\n\ndeclare(strict_types=1);\n\n";
const GENERATED_DIRECTORIES = ['src/Models', 'src/Resources'];
const HTTP_METHODS = ['get', 'post', 'put', 'patch', 'delete'];
const TERMINAL_OPERATIONS = ['fetch', 'get', 'list', 'search'];
const INITIALISMS = ['id' => 'ID', 'ids' => 'IDs', 'oembed' => 'OEmbed', 'qrCode' => 'QRCode', 'tiktok' => 'TikTok', 'url' => 'URL'];
const RESERVED_CLASS_NAMES = [
    'abstract', 'and', 'array', 'as', 'bool', 'break', 'callable', 'case', 'catch', 'class', 'clone', 'const', 'continue',
    'declare', 'default', 'do', 'echo', 'else', 'elseif', 'empty', 'enddeclare', 'endfor', 'endforeach', 'endif',
    'endswitch', 'endwhile', 'enum', 'eval', 'exit', 'extends', 'false', 'final', 'finally', 'float', 'fn', 'for',
    'foreach', 'function', 'global', 'goto', 'if', 'implements', 'include', 'instanceof', 'insteadof', 'int',
    'interface', 'isset', 'iterable', 'list', 'match', 'mixed', 'namespace', 'never', 'new', 'null', 'object', 'or',
    'print', 'private', 'protected', 'public', 'readonly', 'require', 'return', 'static', 'string', 'switch', 'throw',
    'trait', 'true', 'try', 'unset', 'use', 'var', 'void', 'while', 'xor', 'yield',
];

function main(array $arguments): int
{
    $check = in_array('--check', $arguments, true);
    $input = PACKAGE_ROOT . '/openapi/openhandle.json';
    foreach ($arguments as $argument) {
        if (str_starts_with($argument, '--input=')) {
            $input = substr($argument, strlen('--input='));
        }
    }

    $document = json_decode((string) file_get_contents($input), true, 512, JSON_THROW_ON_ERROR);
    $outputs = (new Generator($document))->outputs();

    $stale = [];
    foreach ($outputs as $relativePath => $contents) {
        $target = PACKAGE_ROOT . '/' . $relativePath;
        if ($check) {
            if (!is_file($target) || file_get_contents($target) !== $contents) {
                $stale[] = $relativePath;
            }
            continue;
        }
        if (!is_dir(dirname($target))) {
            mkdir(dirname($target), 0777, true);
        }
        if (!is_file($target) || file_get_contents($target) !== $contents) {
            file_put_contents($target, $contents);
        }
    }

    foreach (GENERATED_DIRECTORIES as $directory) {
        foreach (glob(PACKAGE_ROOT . "/{$directory}/*.php") ?: [] as $file) {
            $relativePath = $directory . '/' . basename($file);
            if (array_key_exists($relativePath, $outputs)) {
                continue;
            }
            if ($check) {
                $stale[] = $relativePath;
                continue;
            }
            unlink($file);
        }
    }

    if ($stale !== []) {
        fwrite(STDERR, "Generated files are stale. Run php scripts/generate.php.\n  " . implode("\n  ", $stale) . "\n");

        return 1;
    }

    return 0;
}

final class TypeInfo
{
    /**
     * @param string $native the PHP type without null
     * @param string $doc the PHPDoc type without null
     * @param \Closure(string, string, bool): string $reader builds a read expression from a value and path expression
     * @param string|null $zero the value a missing non-null field reads as, or null when absence is an error
     */
    public function __construct(
        public readonly string $native,
        public readonly string $doc,
        public readonly bool $nullable,
        public readonly \Closure $reader,
        public readonly bool $scalar = false,
        public readonly ?string $zero = null,
    ) {}

    public function withNullable(bool $nullable): self
    {
        return new self($this->native, $this->doc, $this->nullable || $nullable, $this->reader, $this->scalar, $this->zero);
    }

    public function nativeType(bool $nullable): string
    {
        if ($this->native === 'mixed' || !$nullable) {
            return $this->native;
        }

        return str_contains($this->native, '|') ? "{$this->native}|null" : "?{$this->native}";
    }

    public function docType(bool $nullable): string
    {
        if ($this->native === 'mixed' || !$nullable) {
            return $this->doc;
        }

        return "{$this->doc}|null";
    }

    public function read(string $value, string $path, bool $nullable): string
    {
        return ($this->reader)($value, $path, $nullable);
    }
}

final class Node
{
    /** @var array<string, Node> */
    public array $children = [];

    /** @var array<string, array<string, mixed>> */
    public array $operations = [];

    /**
     * @param list<string> $path
     * @param array<string, mixed> $scope
     */
    public function __construct(public readonly array $path, public readonly array $scope = []) {}
}

final class Generator
{
    /** @var array<string, array<string, mixed>> */
    private array $schemas;

    /** @var list<array<string, mixed>> */
    private array $operations;

    /** @var array<string, string> model class name => file contents */
    private array $models = [];

    /** @var array<string, true> */
    private array $fetchResources = [];

    public function __construct(array $document)
    {
        $this->schemas = $document['components']['schemas'] ?? [];
        $this->operations = operationDefinitions($document);
    }

    /**
     * @return array<string, string>
     */
    public function outputs(): array
    {
        $fetch = $this->fetchVariants();
        foreach ($fetch as $variant) {
            $this->fetchResources[$variant['class']] = true;
        }
        foreach (array_keys($this->schemas) as $name) {
            if (isObjectSchema($this->schemas[$name])) {
                $this->model($name, $this->schemas[$name]);
            }
        }
        $resources = $this->resources();

        $outputs = [];
        ksort($this->models);
        assertCaseInsensitiveUnique(array_keys($this->models), 'model class');
        foreach ($this->models as $name => $contents) {
            $outputs["src/Models/{$name}.php"] = $contents;
        }
        if ($fetch !== []) {
            $outputs['src/Models/FetchResource.php'] = GENERATED_HEADER
                . "namespace OpenHandle\\Models;\n\nuse OpenHandle\\Internal\\Model;\n\n"
                . "/**\n * One of the concrete resources returned by a URL fetch.\n */\ninterface FetchResource extends Model\n{\n}\n";
        }
        foreach ($resources as $name => $contents) {
            $outputs["src/Resources/{$name}.php"] = $contents;
        }
        $outputs['src/Internal/Operations.php'] = $this->manifest();
        ksort($outputs);

        return $outputs;
    }

    // ------------------------------------------------------------------ models

    private function model(string $name, array $schema): string
    {
        if (isset($this->models[$name])) {
            return $name;
        }
        if (in_array(strtolower($name), RESERVED_CLASS_NAMES, true)) {
            throw new RuntimeException("generator: model name {$name} is a reserved PHP word.");
        }
        $this->models[$name] = '';

        [$properties, $required] = $this->flattenedMembers($schema);
        $parameters = [];
        $arguments = [];
        foreach ($properties as $property => $propertySchema) {
            if (preg_match('/^[A-Za-z_][A-Za-z0-9_]*$/', $property) !== 1) {
                throw new RuntimeException("generator: property {$name}.{$property} is not a valid PHP identifier.");
            }
            $type = $this->type($propertySchema, $name . pascalCase($property));
            $optional = !in_array($property, $required, true);
            $nullable = $type->nullable || $optional;
            $native = $type->nativeType($nullable);
            $doc = $type->docType($nullable);
            $lines = [];
            $description = is_string($propertySchema['description'] ?? null) ? $propertySchema['description'] : '';
            if ($description !== '') {
                array_push($lines, ...wrap(docText($description)));
            }
            $nativeDoc = str_starts_with($native, '?') ? substr($native, 1) . '|null' : $native;
            if ($doc !== $nativeDoc) {
                $lines[] = "@var {$doc}";
            }
            $comment = $lines === [] ? '' : docBlock($lines, '        ');
            $default = $nullable || $native === 'mixed' ? ' = null' : '';
            $parameters[] = [
                'default' => $default !== '',
                'code' => "{$comment}        public readonly {$native} \${$property}{$default},",
            ];
            $fallback = !$nullable && $type->zero !== null ? $type->zero : 'null';
            $arguments[] = "            {$property}: " . $type->read("\$data['{$property}'] ?? {$fallback}", "\"{\$path}.{$property}\"", $nullable) . ',';
        }
        usort($parameters, static fn(array $left, array $right): int => $left['default'] <=> $right['default']);

        $interfaces = ['Model'];
        if (isset($this->fetchResources[$name])) {
            $interfaces[] = 'FetchResource';
        }
        $description = is_string($schema['description'] ?? null) ? $schema['description'] : '';
        $classDoc = $description !== '' ? docBlock(wrap(docText($description)), '') : '';
        $constructor = $parameters === []
            ? "    public function __construct()\n    {\n    }\n"
            : "    public function __construct(\n" . implode("\n", array_column($parameters, 'code')) . "\n    ) {\n    }\n";
        $factory = $arguments === []
            ? "        return new self();\n"
            : "        return new self(\n" . implode("\n", $arguments) . "\n        );\n";

        $this->models[$name] = GENERATED_HEADER
            . "namespace OpenHandle\\Models;\n\n"
            . "use OpenHandle\\Internal\\Model;\nuse OpenHandle\\Internal\\Wire;\n\n"
            . $classDoc
            . "final class {$name} implements " . implode(', ', $interfaces) . "\n{\n"
            . $constructor
            . "\n    /**\n     * @param array<string, mixed> \$data\n     */\n"
            . "    public static function fromArray(array \$data, string \$path = 'data'): static\n    {\n"
            . $factory
            . "    }\n}\n";

        return $name;
    }

    /**
     * @return array{array<string, array<string, mixed>>, list<string>}
     */
    private function flattenedMembers(array $schema): array
    {
        $properties = [];
        $required = [];
        $merge = function (array $part) use (&$merge, &$properties, &$required): void {
            if (isset($part['$ref'])) {
                $merge($this->schemas[referenceName($part['$ref'])]);

                return;
            }
            foreach ($part['allOf'] ?? [] as $subPart) {
                $merge($subPart);
            }
            foreach ($part['properties'] ?? [] as $name => $propertySchema) {
                $properties[$name] = $propertySchema;
            }
            foreach ($part['required'] ?? [] as $name) {
                $required[] = $name;
            }
        };
        $merge($schema);

        return [$properties, array_values(array_unique($required))];
    }

    private function type(array $schema, string $context): TypeInfo
    {
        if ($schema === [] || array_keys($schema) === ['description']) {
            return new TypeInfo('mixed', 'mixed', false, static fn(string $value): string => $value);
        }
        if (isset($schema['$ref'])) {
            $name = referenceName($schema['$ref']);
            $target = $this->schemas[$name] ?? throw new RuntimeException("generator: unknown schema {$name}.");
            if (!isObjectSchema($target)) {
                return $this->type($target, $name);
            }

            return $this->objectType($this->model($name, $target));
        }
        if (isset($schema['anyOf']) || isset($schema['oneOf'])) {
            return $this->unionType([...($schema['anyOf'] ?? []), ...($schema['oneOf'] ?? [])], $context);
        }
        if (isset($schema['allOf'])) {
            if (count($schema['allOf']) === 1 && isset($schema['allOf'][0]['$ref'])) {
                return $this->type($schema['allOf'][0], $context);
            }

            return $this->objectType($this->auxiliaryModel($schema, $context));
        }

        $types = $schema['type'] ?? [];
        $types = is_array($types) ? $types : [$types];
        $nullable = in_array('null', $types, true);
        $types = array_values(array_filter($types, static fn(string $type): bool => $type !== 'null'));

        if (isset($schema['enum']) || array_key_exists('const', $schema)) {
            $values = isset($schema['enum']) ? $schema['enum'] : [$schema['const']];
            $nullable = $nullable || in_array(null, $values, true);
            $values = array_values(array_filter($values, static fn(mixed $value): bool => $value !== null));
            $native = scalarNative($types[0] ?? gettype($values[0]));
            if (!in_array($native, ['string', 'int', 'bool'], true)) {
                throw new RuntimeException("generator: {$context} has an unsupported {$native} enum.");
            }
            $literals = implode(', ', array_map(phpLiteral(...), $values));
            $doc = implode('|', array_map(phpLiteral(...), $values));

            return new TypeInfo(
                $native,
                $doc,
                $nullable,
                static fn(string $value, string $path, bool $isNullable): string => ($isNullable ? 'Wire::nullableEnum' : 'Wire::enum') . "({$value}, {$path}, [{$literals}])",
                scalar: true,
            );
        }
        if (count($types) > 1) {
            throw new RuntimeException("generator: {$context} has an unsupported multi-type schema.");
        }
        $type = $types[0] ?? (isset($schema['properties']) ? 'object' : null);

        return match ($type) {
            'array' => $this->arrayType($schema, $context)->withNullable($nullable),
            'object' => $this->mapType($schema, $context)->withNullable($nullable),
            'string', 'integer', 'number', 'boolean' => scalarType(scalarNative($type))->withNullable($nullable),
            default => throw new RuntimeException("generator: {$context} has an unsupported schema."),
        };
    }

    private function objectType(string $class): TypeInfo
    {
        return new TypeInfo(
            $class,
            $class,
            false,
            static fn(string $value, string $path, bool $nullable): string => ($nullable ? 'Wire::nullableObject' : 'Wire::object') . "({$value}, {$path}, {$class}::class)",
            zero: '[]',
        );
    }

    private function arrayType(array $schema, string $context): TypeInfo
    {
        $item = $this->type($schema['items'] ?? [], "{$context}Item");
        $closure = itemClosure($item);

        return new TypeInfo(
            'array',
            'list<' . $item->docType($item->nullable) . '>',
            false,
            static fn(string $value, string $path, bool $nullable): string => ($nullable ? 'Wire::nullableList' : 'Wire::list') . "({$value}, {$path}, {$closure})",
            zero: '[]',
        );
    }

    private function mapType(array $schema, string $context): TypeInfo
    {
        if (!empty($schema['properties'])) {
            return $this->objectType($this->auxiliaryModel($schema, $context));
        }
        $additional = $schema['additionalProperties'] ?? true;
        if (!is_array($additional) || $additional === []) {
            return new TypeInfo(
                'array',
                'array<string, mixed>',
                false,
                static fn(string $value, string $path, bool $nullable): string => ($nullable ? 'Wire::nullableMap' : 'Wire::map') . "({$value}, {$path})",
                zero: '[]',
            );
        }
        $item = $this->type($additional, "{$context}Value");
        $closure = itemClosure($item);

        return new TypeInfo(
            'array',
            'array<string, ' . $item->docType($item->nullable) . '>',
            false,
            static fn(string $value, string $path, bool $nullable): string => ($nullable ? 'Wire::nullableMapOf' : 'Wire::mapOf') . "({$value}, {$path}, {$closure})",
            zero: '[]',
        );
    }

    /**
     * @param list<array<string, mixed>> $variants
     */
    private function unionType(array $variants, string $context): TypeInfo
    {
        $nullable = false;
        $types = [];
        foreach ($variants as $variant) {
            if (($variant['type'] ?? null) === 'null') {
                $nullable = true;
                continue;
            }
            $types[] = $this->type($variant, $context);
        }
        if (count($types) === 1) {
            return $types[0]->withNullable($nullable);
        }
        if ($types === []) {
            return new TypeInfo('mixed', 'mixed', false, static fn(string $value): string => $value);
        }
        $natives = [];
        foreach ($types as $type) {
            if (!$type->scalar || $type->nullable) {
                throw new RuntimeException("generator: {$context} has an unsupported non-scalar union.");
            }
            $natives[$type->native] = true;
        }
        $native = implode('|', array_keys($natives));
        $checks = implode(' || ', array_map(
            static fn(string $type): string => match ($type) {
                'string' => 'is_string($value)',
                'int' => 'is_int($value)',
                'float' => 'is_float($value) || is_int($value)',
                'bool' => 'is_bool($value)',
            },
            array_keys($natives),
        ));

        return new TypeInfo(
            $native,
            $native,
            $nullable,
            static function (string $value, string $path, bool $isNullable) use ($native, $checks): string {
                $returnType = $isNullable ? "{$native}|null" : $native;
                $guard = $isNullable ? "\$value === null || {$checks}" : $checks;

                return "(static function (mixed \$value, string \$path): {$returnType} {\n"
                    . "                if ({$guard}) {\n"
                    . "                    return \$value;\n"
                    . "                }\n\n"
                    . "                throw Wire::invalid(\$path, '{$returnType}');\n"
                    . "            })({$value}, {$path})";
            },
            scalar: true,
        );
    }

    private function auxiliaryModel(array $schema, string $context): string
    {
        if (isset($this->schemas[$context])) {
            throw new RuntimeException("generator: auxiliary model name {$context} collides with a component schema.");
        }

        return $this->model($context, $schema);
    }

    // ---------------------------------------------------------------- fetch

    /**
     * @return list<array{platform: string, resource: string, class: string, keys: list<string>}>
     */
    private function fetchVariants(): array
    {
        foreach ($this->operations as $operation) {
            if ($operation['operation'] !== 'fetch') {
                continue;
            }
            $response = $operation['definition']['responses']['200']['content']['application/json']['schema'];
            $variants = [];
            foreach ($response['oneOf'] ?? [] as $variant) {
                $platform = $this->findProperty($variant, 'platform')['const'] ?? null;
                $resource = $this->findProperty($variant, 'resource')['const'] ?? null;
                $data = $this->findProperty($variant, 'data');
                if (!is_string($platform) || !is_string($resource) || !isset($data['$ref'])) {
                    throw new RuntimeException('generator: every fetch variant needs a platform, resource, and data reference.');
                }
                $variants[] = ['platform' => $platform, 'resource' => $resource, 'class' => referenceName($data['$ref']), 'keys' => []];
            }
            foreach ($variants as $index => $variant) {
                $siblings = array_filter(
                    $variants,
                    static fn(array $other): bool => $other['platform'] === $variant['platform']
                        && $other['resource'] === $variant['resource']
                        && $other['class'] !== $variant['class'],
                );
                if ($siblings === []) {
                    continue;
                }
                [, $required] = $this->flattenedMembers($this->schemas[$variant['class']]);
                foreach ($siblings as $sibling) {
                    [, $siblingRequired] = $this->flattenedMembers($this->schemas[$sibling['class']]);
                    $required = array_diff($required, $siblingRequired);
                }
                if ($required === []) {
                    throw new RuntimeException("generator: fetch variant {$variant['class']} has no distinguishing required field.");
                }
                sort($required);
                $variants[$index]['keys'] = array_values($required);
            }

            return $variants;
        }

        return [];
    }

    private function findProperty(array $schema, string $name): ?array
    {
        if (isset($schema['$ref'])) {
            return $this->findProperty($this->schemas[referenceName($schema['$ref'])], $name);
        }
        if (isset($schema['properties'][$name])) {
            return $schema['properties'][$name];
        }
        foreach (array_reverse($schema['allOf'] ?? []) as $part) {
            $found = $this->findProperty($part, $name);
            if ($found !== null) {
                return $found;
            }
        }

        return null;
    }

    // ---------------------------------------------------------------- manifest

    private function manifest(): string
    {
        $entries = [];
        foreach ($this->operations as $operation) {
            $scope = array_map(
                static fn(array $segment): string => '[' . implode(', ', array_map(
                    static fn(string $key): string => phpLiteral($key) . ' => ' . phpLiteral($segment[$key]),
                    array_values(array_intersect(['name', 'parameter', 'reference'], array_keys($segment))),
                )) . ']',
                $operation['scope'],
            );
            $entries[] = "        [\n"
                . '            \'apiPath\' => ' . phpLiteral($operation['apiPath']) . ",\n"
                . '            \'method\' => ' . phpLiteral($operation['method']) . ",\n"
                . '            \'operation\' => ' . phpLiteral($operation['operation']) . ",\n"
                . '            \'paginated\' => ' . phpLiteral($operation['paginated']) . ",\n"
                . '            \'path\' => ' . phpLiteral($operation['path']) . ",\n"
                . '            \'scope\' => [' . implode(', ', $scope) . "],\n"
                . '        ],';
        }

        return GENERATED_HEADER
            . "namespace OpenHandle\\Internal;\n\n"
            . "/**\n * Every OpenAPI operation the SDK exposes, keyed by its canonical SDK path.\n *\n * @internal\n */\n"
            . "final class Operations\n{\n"
            . "    /**\n     * @var list<array{apiPath: string, method: string, operation: string, paginated: bool, path: string, scope: list<array<string, string>>}>\n     */\n"
            . "    public const ALL = [\n"
            . implode("\n", $entries)
            . "\n    ];\n}\n";
    }

    // --------------------------------------------------------------- resources

    /**
     * @return array<string, string>
     */
    private function resources(): array
    {
        $root = new Node([]);
        foreach ($this->operations as $operation) {
            $node = $root;
            foreach ($operation['scope'] as $segment) {
                $node->children[$segment['name']] ??= new Node([...$node->path, $segment['name']], $segment);
                $node = $node->children[$segment['name']];
            }
            $node->operations[$operation['operation']] = $operation;
        }

        $classes = [];
        $visit = function (Node $node) use (&$visit, &$classes): void {
            foreach ($node->children as $child) {
                $visit($child);
                $classes[nodeClassName($child->path)] = $this->nodeClass($child);
            }
        };
        $visit($root);
        $classes['GeneratedClient'] = $this->rootClass($root);
        assertCaseInsensitiveUnique(array_keys($classes), 'resource class');
        ksort($classes);

        return $classes;
    }

    private function nodeClass(Node $node): string
    {
        $className = nodeClassName($node->path);
        [$properties, $assignments] = $this->namespaces($node);
        $methods = $this->methods($node);
        $stores = $node->operations !== [] || array_filter($node->children, static fn(Node $child): bool => isset($child->scope['parameter'])) !== [];
        $constructorParameters = $stores
            ? "        private readonly Transport \$transport,\n        private readonly array \$bindings,\n"
            : "        Transport \$transport,\n        array \$bindings,\n";

        return GENERATED_HEADER
            . "namespace OpenHandle\\Resources;\n\n"
            . $this->imports($node)
            . "final class {$className}\n{\n"
            . $properties
            . "    /**\n     * @internal\n     *\n     * @param array<string, string> \$bindings\n     */\n"
            . "    public function __construct(\n{$constructorParameters}    ) {\n"
            . $assignments
            . "    }\n"
            . $methods
            . "}\n";
    }

    private function rootClass(Node $root): string
    {
        [$properties, $assignments] = $this->namespaces($root, rootBindings: true);
        $methods = $this->methods($root);

        return GENERATED_HEADER
            . "namespace OpenHandle\\Resources;\n\n"
            . $this->imports($root)
            . "/**\n * The generated resource graph shared by every OpenHandle client.\n */\n"
            . "abstract class GeneratedClient\n{\n"
            . $properties
            . "    public function __construct(private readonly Transport \$transport)\n    {\n"
            . $assignments
            . "    }\n"
            . $methods
            . "}\n";
    }

    private function imports(Node $node): string
    {
        $imports = ['OpenHandle\\Internal\\Transport'];
        $operations = array_values($node->operations);
        $hasSelectors = array_filter($node->children, static fn(Node $child): bool => isset($child->scope['parameter'])) !== [];
        if ($hasSelectors) {
            $imports[] = 'OpenHandle\\Internal\\References';
        }
        foreach ($operations as $operation) {
            $imports[] = 'OpenHandle\\Internal\\Wire';
            $imports[] = $operation['paginated'] ? 'OpenHandle\\Page' : 'OpenHandle\\Response';
            if ($operation['operation'] === 'fetch') {
                foreach ($this->fetchVariants() as $variant) {
                    $imports[] = "OpenHandle\\Models\\{$variant['class']}";
                }
                continue;
            }
            $imports[] = 'OpenHandle\\Models\\' . $this->dataClass($operation);
            if ($operation['paginated']) {
                $imports[] = 'Generator';
            }
            foreach (queryParameters($operation) as $parameter) {
                if ($parameter['dateTime']) {
                    $imports[] = 'DateTimeInterface';
                }
            }
        }
        $imports = array_values(array_unique($imports));
        sort($imports);

        return implode('', array_map(static fn(string $import): string => "use {$import};\n", $imports)) . "\n";
    }

    /**
     * @return array{string, string}
     */
    private function namespaces(Node $node, bool $rootBindings = false): array
    {
        $properties = '';
        $assignments = '';
        foreach ($node->children as $name => $child) {
            if (isset($child->scope['parameter'])) {
                continue;
            }
            $className = nodeClassName($child->path);
            $properties .= "    public readonly {$className} \${$name};\n\n";
            $bindings = $rootBindings ? '[]' : '$bindings';
            $assignments .= "        \$this->{$name} = new {$className}(\$transport, {$bindings});\n";
        }

        return [$properties, $assignments];
    }

    private function methods(Node $node): string
    {
        $methods = [];
        foreach ($node->children as $name => $child) {
            if (isset($child->scope['parameter'])) {
                $methods[$name] = $this->selectorMethod($name, $child);
            }
        }
        foreach ($node->operations as $operationName => $operation) {
            $methods[$operationName] = $operation['operation'] === 'fetch'
                ? $this->fetchMethod($operation)
                : $this->operationMethod($operation);
            if ($operation['paginated']) {
                $itemsName = $operationName === 'list' ? 'items' : "{$operationName}Items";
                $methods[$itemsName] = $this->itemsMethod($operation, $itemsName);
            }
        }
        assertCaseInsensitiveUnique(array_keys($methods), 'method in ' . (nodeClassName($node->path) ?: 'GeneratedClient'));

        return implode('', array_map(static fn(string $method): string => "\n{$method}", $methods));
    }

    private function selectorMethod(string $name, Node $child): string
    {
        $family = $child->scope['reference'] ?? $name;
        $platform = $child->path[0];
        $className = nodeClassName($child->path);
        $isProfile = $family === 'profile';
        $forms = $isProfile
            ? 'a username shorthand or an explicit ID or URL reference'
            : 'a supported string shorthand or an explicit ID or URL reference';
        $named = $isProfile ? 'username, id, or url' : 'id or url';
        $parameters = $isProfile
            ? 'mixed $reference = null, mixed $username = null, mixed $id = null, mixed $url = null'
            : 'mixed $reference = null, mixed $id = null, mixed $url = null';
        $docParameters = array_map(
            static fn(string $parameter): string => "@param string|null \${$parameter}",
            $isProfile ? ['reference', 'username', 'id', 'url'] : ['reference', 'id', 'url'],
        );
        $username = $isProfile ? '$username' : 'null';

        return docBlock([
            "Select the {$family} resource using {$forms}.",
            '',
            "Pass a raw string, or exactly one of the {$named} named arguments.",
            'IDs are opaque strings. Resource selection does not perform a request.',
            '',
            ...$docParameters,
        ], '    ')
            . "    public function {$name}({$parameters}): {$className}\n    {\n"
            . "        \$identifier = References::selector(\$reference, {$username}, \$id, \$url, " . phpLiteral($platform) . ', ' . phpLiteral($family) . ");\n\n"
            . "        return new {$className}(\$this->transport, [...\$this->bindings, " . phpLiteral($child->scope['parameter']) . " => \$identifier]);\n"
            . "    }\n";
    }

    private function fetchMethod(array $operation): string
    {
        $variants = $this->fetchVariants();
        $union = implode('|', array_unique(array_column($variants, 'class')));
        $groups = [];
        foreach ($variants as $variant) {
            $groups[$variant['platform'] . '/' . $variant['resource']][] = $variant;
        }
        $arms = [];
        foreach ($groups as $group) {
            $condition = '$platform === ' . phpLiteral($group[0]['platform']) . ' && $resource === ' . phpLiteral($group[0]['resource']);
            if (count($group) === 1) {
                $arms[] = "                    {$condition} => {$group[0]['class']}::fromArray(\$fields),";
                continue;
            }
            $candidates = implode('', array_map(
                static fn(array $variant): string => "                        {$variant['class']}::class => [" . implode(', ', array_map(phpLiteral(...), $variant['keys'])) . "],\n",
                $group,
            ));
            $arms[] = "                    {$condition} => Wire::variant(\$fields, [\n{$candidates}                    ])::fromArray(\$fields),";
        }
        $freshness = $this->freshnessDoc($operation);

        return docBlock([
            ...$this->description($operation),
            '',
            "@param {$freshness} \$freshness",
            '@param float|null $timeout Request timeout in seconds for this call.',
            '@param int|null $maxRetries Retry limit for this call.',
            '',
            "@return Response<{$union}>",
        ], '    ')
            . "    public function fetch(string \$url, ?string \$freshness = null, ?float \$timeout = null, ?int \$maxRetries = null): Response\n    {\n"
            . "        if (trim(\$url) === '') {\n"
            . "            throw new \\InvalidArgumentException('fetch(\$url) requires a non-empty social URL.');\n"
            . "        }\n"
            . "        \$body = ['url' => \$url];\n"
            . "        if (\$freshness !== null) {\n"
            . "            \$body['freshness'] = \$freshness;\n"
            . "        }\n\n"
            . "        return \$this->transport->response(\n"
            . '            ' . phpLiteral($operation['method']) . ",\n"
            . '            ' . phpLiteral($operation['apiPath']) . ",\n"
            . "            [],\n            [],\n            \$body,\n            \$timeout,\n            \$maxRetries,\n"
            . "            static function (mixed \$data, array \$envelope): {$union} {\n"
            . "                \$platform = Wire::string(\$envelope['platform'] ?? null, 'platform');\n"
            . "                \$resource = Wire::string(\$envelope['resource'] ?? null, 'resource');\n"
            . "                \$fields = Wire::map(\$data, 'data');\n\n"
            . "                return match (true) {\n"
            . implode("\n", $arms) . "\n"
            . "                    default => throw Wire::invalid('data', \"a supported fetch resource, not {\$platform} {\$resource}\"),\n"
            . "                };\n"
            . "            },\n"
            . "        );\n"
            . "    }\n";
    }

    private function operationMethod(array $operation): string
    {
        $parameters = queryParameters($operation);
        $signature = implode(', ', [...array_map(parameterSignature(...), $parameters), '?float $timeout = null', '?int $maxRetries = null']);
        $params = '[' . implode(', ', array_map(
            static fn(array $parameter): string => phpLiteral($parameter['name']) . " => \${$parameter['php']}",
            $parameters,
        )) . ']';
        $class = $this->dataClass($operation);
        $paginated = $operation['paginated'];
        $isList = $this->dataIsList($operation);
        $dataDoc = $isList ? "list<{$class}>" : $class;
        $return = $paginated ? "Page<{$class}>" : "Response<{$dataDoc}>";
        $docs = [
            ...$this->description($operation),
            '',
            ...array_map(fn(array $parameter): string => $this->parameterDoc($parameter), $parameters),
            '@param float|null $timeout Request timeout in seconds for this call.',
            '@param int|null $maxRetries Retry limit for this call.',
            '',
            "@return {$return}",
        ];
        $item = "static fn(mixed \$item, string \$path): {$class} => Wire::object(\$item, \$path, {$class}::class)";
        $call = $paginated
            ? "        return \$this->transport->page(\n"
                . '            ' . phpLiteral($operation['method']) . ",\n"
                . '            ' . phpLiteral($operation['apiPath']) . ",\n"
                . "            \$this->bindings,\n            {$params},\n            \$timeout,\n            \$maxRetries,\n"
                . "            {$item},\n        );\n"
            : "        return \$this->transport->response(\n"
                . '            ' . phpLiteral($operation['method']) . ",\n"
                . '            ' . phpLiteral($operation['apiPath']) . ",\n"
                . "            \$this->bindings,\n            {$params},\n            null,\n            \$timeout,\n            \$maxRetries,\n"
                . ($isList
                    ? "            static fn(mixed \$data): array => Wire::list(\$data, 'data', {$item}),\n"
                    : "            static fn(mixed \$data): {$class} => Wire::object(\$data, 'data', {$class}::class),\n")
                . "        );\n";
        $returnType = $paginated ? 'Page' : 'Response';

        return docBlock($docs, '    ')
            . "    public function {$operation['operation']}({$signature}): {$returnType}\n    {\n"
            . $call
            . "    }\n";
    }

    private function itemsMethod(array $operation, string $itemsName): string
    {
        $parameters = queryParameters($operation);
        $signature = implode(', ', [...array_map(parameterSignature(...), $parameters), '?float $timeout = null', '?int $maxRetries = null']);
        $arguments = implode(', ', [
            ...array_map(static fn(array $parameter): string => "{$parameter['php']}: \${$parameter['php']}", $parameters),
            'timeout: $timeout',
            'maxRetries: $maxRetries',
        ]);
        $class = $this->dataClass($operation);

        return docBlock([
            "Iterate items lazily across pages of {$operation['path']}, one request per page.",
            '',
            ...array_map(fn(array $parameter): string => $this->parameterDoc($parameter), $parameters),
            '@param float|null $timeout Request timeout in seconds for each page.',
            '@param int|null $maxRetries Retry limit for each page.',
            '',
            "@return Generator<int, {$class}, mixed, void>",
        ], '    ')
            . "    public function {$itemsName}({$signature}): Generator\n    {\n"
            . "        \$page = \$this->{$operation['operation']}({$arguments});\n"
            . "        while (\$page !== null) {\n"
            . "            yield from \$page->data;\n"
            . "            \$page = \$page->next();\n"
            . "        }\n"
            . "    }\n";
    }

    private function parameterDoc(array $parameter): string
    {
        $doc = "@param {$parameter['doc']}" . ($parameter['required'] ? '' : '|null') . " \${$parameter['php']}";
        if ($parameter['description'] !== '') {
            $doc .= ' ' . docText($parameter['description']);
        }

        return $doc;
    }

    private function freshnessDoc(array $operation): string
    {
        $body = $operation['definition']['requestBody']['content']['application/json']['schema'] ?? [];
        $values = $body['properties']['freshness']['enum'] ?? ['live', '24h', '7d', '30d'];

        return implode('|', array_map(phpLiteral(...), $values)) . '|null';
    }

    /**
     * @return list<string>
     */
    private function description(array $operation): array
    {
        $definition = $operation['definition'];
        $lines = [docText($definition['summary'] ?? $operation['path'])];
        if (!empty($definition['description'])) {
            $lines[] = '';
            foreach (wrap(docText($definition['description'])) as $line) {
                $lines[] = $line;
            }
        }
        $lines[] = '';
        $lines[] = 'Example:';
        $lines[] = '    ' . $this->example($operation);
        $operationId = $definition['x-openhandle-operation'] ?? null;
        if (is_string($operationId)) {
            $lines[] = '';
            $lines[] = '@see https://openhandle.dev/docs/api-reference/' . str_replace('.', '-', $operationId);
        }

        return $lines;
    }

    private function example(array $operation): string
    {
        if ($operation['operation'] === 'fetch') {
            return "\$openhandle->fetch('https://www.instagram.com/openai/', freshness: '24h');";
        }
        $examples = $operation['definition']['x-openhandle-test-data']['example'] ?? [];
        $call = '$openhandle';
        foreach ($operation['scope'] as $segment) {
            $call .= "->{$segment['name']}";
            if (isset($segment['parameter'])) {
                $value = $examples[$segment['parameter']] ?? null;
                $call .= '(' . phpLiteral(is_scalar($value) ? (string) $value : "<{$segment['parameter']}>") . ')';
            }
        }
        $options = [];
        foreach (queryParameters($operation) as $parameter) {
            if (!$parameter['required'] && $parameter['name'] !== 'freshness') {
                continue;
            }
            $value = $parameter['example'] ?? $examples[$parameter['name']] ?? null;
            $options[] = "{$parameter['php']}: " . phpLiteral(is_scalar($value) ? $value : "<{$parameter['name']}>");
        }

        return "{$call}->{$operation['operation']}(" . implode(', ', $options) . ');';
    }

    private function dataClass(array $operation): string
    {
        $data = $this->dataSchema($operation);
        if ($operation['paginated'] || $this->dataIsList($operation)) {
            $data = $data['items'] ?? throw new RuntimeException("generator: {$operation['path']} data is not an array.");
        }
        if (!isset($data['$ref'])) {
            throw new RuntimeException("generator: operation {$operation['path']} data is not a component reference.");
        }
        $name = referenceName($data['$ref']);
        while (array_keys($this->schemas[$name]) === ['$ref']) {
            $name = referenceName($this->schemas[$name]['$ref']);
        }
        if (!isObjectSchema($this->schemas[$name])) {
            throw new RuntimeException("generator: operation {$operation['path']} data is not an object schema.");
        }

        return $name;
    }

    private function dataIsList(array $operation): bool
    {
        $data = $this->dataSchema($operation);

        return !$operation['paginated'] && ($data['type'] ?? null) === 'array';
    }

    private function dataSchema(array $operation): array
    {
        $response = $operation['definition']['responses']['200']['content']['application/json']['schema'];

        return $this->findProperty($response, 'data')
            ?? throw new RuntimeException("generator: operation {$operation['path']} has no data schema.");
    }
}

/**
 * @return list<array<string, mixed>>
 */
function operationDefinitions(array $document): array
{
    $result = [];
    $seen = [];
    foreach ($document['paths'] ?? [] as $apiPath => $pathItem) {
        foreach ($pathItem as $method => $definition) {
            if (!in_array($method, HTTP_METHODS, true)) {
                continue;
            }
            $sdk = $definition['x-openhandle-sdk'] ?? null;
            if (
                !is_array($sdk)
                || !is_string($sdk['path'] ?? null)
                || !is_array($sdk['scope'] ?? null)
                || !in_array($sdk['operation'] ?? null, TERMINAL_OPERATIONS, true)
            ) {
                throw new RuntimeException('generator: ' . strtoupper($method) . " {$apiPath} has no valid x-openhandle-sdk mapping.");
            }
            if (isset($seen[$sdk['path']])) {
                throw new RuntimeException("generator: duplicate SDK path {$sdk['path']}.");
            }
            $seen[$sdk['path']] = true;
            $result[] = [
                'apiPath' => $apiPath,
                'method' => $method,
                'operation' => $sdk['operation'],
                'paginated' => ($sdk['paginated'] ?? false) === true,
                'path' => $sdk['path'],
                'scope' => $sdk['scope'],
                'definition' => $definition,
            ];
        }
    }
    usort($result, static fn(array $left, array $right): int => strcmp($left['path'], $right['path']));

    return $result;
}

/**
 * @return list<array{name: string, php: string, required: bool, native: string, doc: string, dateTime: bool, description: string, example: mixed}>
 */
function queryParameters(array $operation): array
{
    $parameters = [];
    foreach ($operation['definition']['parameters'] ?? [] as $parameter) {
        if (($parameter['in'] ?? null) !== 'query') {
            continue;
        }
        $schema = $parameter['schema'] ?? [];
        $dateTime = ($schema['format'] ?? null) === 'date-time';
        [$native, $doc] = match (true) {
            isset($schema['enum']) => ['string', implode('|', array_map(phpLiteral(...), array_values(array_filter($schema['enum'], static fn(mixed $value): bool => $value !== null))))],
            $dateTime => ['string|DateTimeInterface', 'string|DateTimeInterface'],
            ($schema['type'] ?? null) === 'integer' => ['int', 'int'],
            ($schema['type'] ?? null) === 'boolean' => ['bool', 'bool'],
            default => ['string', 'string'],
        };
        $parameters[] = [
            'name' => $parameter['name'],
            'php' => camelCase($parameter['name']),
            'required' => ($parameter['required'] ?? false) === true,
            'native' => $native,
            'doc' => $doc,
            'dateTime' => $dateTime,
            'description' => is_string($parameter['description'] ?? null) ? $parameter['description'] : '',
            'example' => $parameter['example'] ?? $schema['default'] ?? null,
        ];
    }
    usort($parameters, static fn(array $left, array $right): int => $right['required'] <=> $left['required']);

    return $parameters;
}

function parameterSignature(array $parameter): string
{
    if ($parameter['required']) {
        return "{$parameter['native']} \${$parameter['php']}";
    }
    $native = str_contains($parameter['native'], '|') ? "{$parameter['native']}|null" : "?{$parameter['native']}";

    return "{$native} \${$parameter['php']} = null";
}

function itemClosure(TypeInfo $item): string
{
    if ($item->native === 'mixed') {
        return 'static fn(mixed $item): mixed => $item';
    }
    $returnType = $item->nativeType($item->nullable);

    return "static fn(mixed \$item, string \$path): {$returnType} => " . $item->read('$item', '$path', $item->nullable);
}

function scalarType(string $native): TypeInfo
{
    $reader = match ($native) {
        'string' => 'String',
        'int' => 'Int',
        'float' => 'Float',
        'bool' => 'Bool',
    };

    return new TypeInfo(
        $native,
        $native,
        false,
        static fn(string $value, string $path, bool $nullable): string => ($nullable ? "Wire::nullable{$reader}" : 'Wire::' . strtolower($reader)) . "({$value}, {$path})",
        scalar: true,
        zero: match ($native) {
            'string' => "''",
            'int' => '0',
            'float' => '0.0',
            'bool' => 'false',
        },
    );
}

function scalarNative(string $type): string
{
    return match ($type) {
        'string' => 'string',
        'integer' => 'int',
        'number', 'double' => 'float',
        'boolean' => 'bool',
        default => throw new RuntimeException("generator: unsupported scalar type {$type}."),
    };
}

function isObjectSchema(array $schema): bool
{
    if (isset($schema['allOf'])) {
        return true;
    }
    $types = $schema['type'] ?? [];
    $types = is_array($types) ? $types : [$types];

    return !empty($schema['properties']) && ($types === [] || in_array('object', $types, true));
}

function referenceName(string $reference): string
{
    return substr($reference, strrpos($reference, '/') + 1);
}

function nodeClassName(array $path): string
{
    return $path === [] ? '' : implode('', array_map(pascalCase(...), $path)) . 'Resource';
}

function pascalCase(string $value): string
{
    if (isset(INITIALISMS[$value])) {
        return INITIALISMS[$value];
    }
    $parts = preg_split('/[^A-Za-z0-9]+/', $value) ?: [];
    $result = implode('', array_map(static fn(string $part): string => ucfirst($part), $parts));

    return str_replace(['Id', 'Url', 'QrCode', 'Oembed', 'Tiktok'], ['ID', 'URL', 'QRCode', 'OEmbed', 'TikTok'], $result);
}

function camelCase(string $value): string
{
    $parts = preg_split('/[^A-Za-z0-9]+/', $value) ?: [];
    $first = array_shift($parts) ?? '';

    return $first . implode('', array_map(static fn(string $part): string => ucfirst($part), $parts));
}

function phpLiteral(mixed $value): string
{
    return match (true) {
        is_string($value) => "'" . str_replace(['\\', "'"], ['\\\\', "\\'"], $value) . "'",
        is_bool($value) => $value ? 'true' : 'false',
        is_int($value), is_float($value) => var_export($value, true),
        $value === null => 'null',
        default => throw new RuntimeException('generator: unsupported literal value.'),
    };
}

function docText(string $value): string
{
    return str_replace('*/', '*\/', trim($value));
}

/**
 * @return list<string>
 */
function wrap(string $text): array
{
    $lines = [];
    foreach (explode("\n", $text) as $paragraph) {
        $wrapped = wordwrap($paragraph, 100, "\n", false);
        foreach (explode("\n", $wrapped) as $line) {
            if (str_starts_with($line, '@') && $lines !== []) {
                $lines[array_key_last($lines)] .= " {$line}";
                continue;
            }
            $lines[] = $line;
        }
    }

    return $lines;
}

/**
 * @param list<string> $lines
 */
function docBlock(array $lines, string $indent): string
{
    $body = array_map(
        static fn(string $line): string => rtrim("{$indent} * {$line}"),
        $lines,
    );

    return "{$indent}/**\n" . implode("\n", $body) . "\n{$indent} */\n";
}

/**
 * @param list<string> $names
 */
function assertCaseInsensitiveUnique(array $names, string $kind): void
{
    $seen = [];
    foreach ($names as $name) {
        $key = strtolower($name);
        if (isset($seen[$key])) {
            throw new RuntimeException("generator: {$kind} names {$seen[$key]} and {$name} differ only by case.");
        }
        $seen[$key] = $name;
    }
}

exit(main(array_slice($argv, 1)));
