<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;

/**
 * One of the concrete resources returned by a URL fetch.
 */
interface FetchResource extends Model
{
}
