<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramLocationHours implements Model
{
    public function __construct(
        public readonly ?string $currentStatus = null,
        public readonly ?bool $isOpen = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $schedule = null,
        public readonly ?string $status = null,
        public readonly ?string $today = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            currentStatus: Wire::nullableString($data['currentStatus'] ?? null, "{$path}.currentStatus"),
            isOpen: Wire::nullableBool($data['isOpen'] ?? null, "{$path}.isOpen"),
            schedule: Wire::nullableList($data['schedule'] ?? null, "{$path}.schedule", static fn(mixed $item): mixed => $item),
            status: Wire::nullableString($data['status'] ?? null, "{$path}.status"),
            today: Wire::nullableString($data['today'] ?? null, "{$path}.today"),
        );
    }
}
