<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPostReferenceCarousel implements Model
{
    public function __construct(
        public readonly ?int $itemCount = null,
        public readonly ?int $pendingItemCount = null,
        /**
         * @var list<InstagramProfileReference>|null
         */
        public readonly ?array $previousSubmitters = null,
        public readonly ?string $submissionState = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            itemCount: Wire::nullableInt($data['itemCount'] ?? null, "{$path}.itemCount"),
            pendingItemCount: Wire::nullableInt($data['pendingItemCount'] ?? null, "{$path}.pendingItemCount"),
            previousSubmitters: Wire::nullableList($data['previousSubmitters'] ?? null, "{$path}.previousSubmitters", static fn(mixed $item, string $path): InstagramProfileReference => Wire::object($item, $path, InstagramProfileReference::class)),
            submissionState: Wire::nullableString($data['submissionState'] ?? null, "{$path}.submissionState"),
        );
    }
}
