<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPostInsight implements Model
{
    public function __construct(
        public readonly InstagramPostInsightFacebook $facebook,
        public readonly InstagramPostInsightImage $image,
        public readonly InstagramPostInsightMetrics $metrics,
        public readonly ?string $authorId = null,
        public readonly ?string $createdAt = null,
        public readonly ?string $fbid = null,
        public readonly ?bool $hasProductTags = null,
        public readonly ?string $organicPostId = null,
        public readonly ?string $postId = null,
        public readonly ?InstagramImage $thumbnail = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            authorId: Wire::nullableString($data['authorId'] ?? null, "{$path}.authorId"),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            facebook: Wire::object($data['facebook'] ?? [], "{$path}.facebook", InstagramPostInsightFacebook::class),
            fbid: Wire::nullableString($data['fbid'] ?? null, "{$path}.fbid"),
            hasProductTags: Wire::nullableBool($data['hasProductTags'] ?? null, "{$path}.hasProductTags"),
            image: Wire::object($data['image'] ?? [], "{$path}.image", InstagramPostInsightImage::class),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramPostInsightMetrics::class),
            organicPostId: Wire::nullableString($data['organicPostId'] ?? null, "{$path}.organicPostId"),
            postId: Wire::nullableString($data['postId'] ?? null, "{$path}.postId"),
            thumbnail: Wire::nullableObject($data['thumbnail'] ?? null, "{$path}.thumbnail", InstagramImage::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
