<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramSubtitles implements Model
{
    public function __construct(
        public readonly ?float $confidence = null,
        public readonly ?bool $enabled = null,
        public readonly ?bool $generated = null,
        public readonly ?string $locale = null,
        public readonly ?string $status = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            confidence: Wire::nullableFloat($data['confidence'] ?? null, "{$path}.confidence"),
            enabled: Wire::nullableBool($data['enabled'] ?? null, "{$path}.enabled"),
            generated: Wire::nullableBool($data['generated'] ?? null, "{$path}.generated"),
            locale: Wire::nullableString($data['locale'] ?? null, "{$path}.locale"),
            status: Wire::nullableString($data['status'] ?? null, "{$path}.status"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
