<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramAudioMetrics implements Model
{
    public function __construct(
        public readonly ?int $photos = null,
        public readonly ?int $previousTrendRank = null,
        public readonly ?int $reels = null,
        public readonly ?int $trendRank = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            photos: Wire::nullableInt($data['photos'] ?? null, "{$path}.photos"),
            previousTrendRank: Wire::nullableInt($data['previousTrendRank'] ?? null, "{$path}.previousTrendRank"),
            reels: Wire::nullableInt($data['reels'] ?? null, "{$path}.reels"),
            trendRank: Wire::nullableInt($data['trendRank'] ?? null, "{$path}.trendRank"),
        );
    }
}
