<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPostInsightMetrics implements Model
{
    public function __construct(
        public readonly InstagramPostInsightMetricsShopping $shopping,
        public readonly ?int $comments = null,
        public readonly ?int $likes = null,
        public readonly ?int $saves = null,
        public readonly ?int $shoppingOutboundClicks = null,
        public readonly ?int $shoppingProductClicks = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            saves: Wire::nullableInt($data['saves'] ?? null, "{$path}.saves"),
            shopping: Wire::object($data['shopping'] ?? [], "{$path}.shopping", InstagramPostInsightMetricsShopping::class),
            shoppingOutboundClicks: Wire::nullableInt($data['shoppingOutboundClicks'] ?? null, "{$path}.shoppingOutboundClicks"),
            shoppingProductClicks: Wire::nullableInt($data['shoppingProductClicks'] ?? null, "{$path}.shoppingProductClicks"),
        );
    }
}
