<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileReference implements Model
{
    public function __construct(
        public readonly InstagramProfileBroadcastChannels $broadcastChannels,
        public readonly InstagramProfileContact $contact,
        public readonly InstagramProfileContent $content,
        public readonly InstagramProfileContentSettings $contentSettings,
        public readonly InstagramProfileDisplaySettings $displaySettings,
        public readonly InstagramExtracted $extracted,
        public readonly InstagramProfileFanClub $fanClub,
        public readonly InstagramProfileFundraisers $fundraisers,
        public readonly InstagramProfileLocation $location,
        public readonly InstagramProfileMetrics $metrics,
        public readonly InstagramProfileThreads $threads,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $accountBadges = null,
        public readonly string|int|null $accountType = null,
        public readonly ?InstagramImage $avatar = null,
        public readonly ?string $bio = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $bioEntities = null,
        /**
         * @var list<InstagramBioLink>|null
         */
        public readonly ?array $bioLinks = null,
        public readonly ?string $category = null,
        public readonly ?string $categoryId = null,
        public readonly ?string $displayName = null,
        public readonly ?string $externalUrl = null,
        public readonly ?string $fbid = null,
        public readonly ?string $handle = null,
        public readonly ?bool $hasDigitalAvatar = null,
        public readonly ?string $id = null,
        public readonly ?bool $isAccountTransparencyVisible = null,
        public readonly ?bool $isBusiness = null,
        public readonly ?bool $isFacebookOnboardedCharity = null,
        public readonly ?bool $isMemorialized = null,
        public readonly ?bool $isNew = null,
        public readonly ?bool $isOpenToCollaboration = null,
        public readonly ?bool $isPotentialBusiness = null,
        public readonly ?bool $isPrivate = null,
        public readonly ?bool $isUnpublished = null,
        public readonly ?bool $isVerified = null,
        public readonly ?string $lastStoryAt = null,
        /**
         * @var list<InstagramMediaPreview>|null
         */
        public readonly ?array $mediaPreviews = null,
        public readonly ?string $messagingFbid = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $pronouns = null,
        public readonly ?string $socialContext = null,
        public readonly ?InstagramSuggestion $suggestion = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $upcomingEvents = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            accountBadges: Wire::nullableList($data['accountBadges'] ?? null, "{$path}.accountBadges", static fn(mixed $item): mixed => $item),
            accountType: (static function (mixed $value, string $path): string|int|null {
                if ($value === null || is_string($value) || is_int($value)) {
                    return $value;
                }

                throw Wire::invalid($path, 'string|int|null');
            })($data['accountType'] ?? null, "{$path}.accountType"),
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", InstagramImage::class),
            bio: Wire::nullableString($data['bio'] ?? null, "{$path}.bio"),
            bioEntities: Wire::nullableList($data['bioEntities'] ?? null, "{$path}.bioEntities", static fn(mixed $item): mixed => $item),
            bioLinks: Wire::nullableList($data['bioLinks'] ?? null, "{$path}.bioLinks", static fn(mixed $item, string $path): InstagramBioLink => Wire::object($item, $path, InstagramBioLink::class)),
            broadcastChannels: Wire::object($data['broadcastChannels'] ?? [], "{$path}.broadcastChannels", InstagramProfileBroadcastChannels::class),
            category: Wire::nullableString($data['category'] ?? null, "{$path}.category"),
            categoryId: Wire::nullableString($data['categoryId'] ?? null, "{$path}.categoryId"),
            contact: Wire::object($data['contact'] ?? [], "{$path}.contact", InstagramProfileContact::class),
            content: Wire::object($data['content'] ?? [], "{$path}.content", InstagramProfileContent::class),
            contentSettings: Wire::object($data['contentSettings'] ?? [], "{$path}.contentSettings", InstagramProfileContentSettings::class),
            displayName: Wire::nullableString($data['displayName'] ?? null, "{$path}.displayName"),
            displaySettings: Wire::object($data['displaySettings'] ?? [], "{$path}.displaySettings", InstagramProfileDisplaySettings::class),
            externalUrl: Wire::nullableString($data['externalUrl'] ?? null, "{$path}.externalUrl"),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", InstagramExtracted::class),
            fanClub: Wire::object($data['fanClub'] ?? [], "{$path}.fanClub", InstagramProfileFanClub::class),
            fbid: Wire::nullableString($data['fbid'] ?? null, "{$path}.fbid"),
            fundraisers: Wire::object($data['fundraisers'] ?? [], "{$path}.fundraisers", InstagramProfileFundraisers::class),
            handle: Wire::nullableString($data['handle'] ?? null, "{$path}.handle"),
            hasDigitalAvatar: Wire::nullableBool($data['hasDigitalAvatar'] ?? null, "{$path}.hasDigitalAvatar"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isAccountTransparencyVisible: Wire::nullableBool($data['isAccountTransparencyVisible'] ?? null, "{$path}.isAccountTransparencyVisible"),
            isBusiness: Wire::nullableBool($data['isBusiness'] ?? null, "{$path}.isBusiness"),
            isFacebookOnboardedCharity: Wire::nullableBool($data['isFacebookOnboardedCharity'] ?? null, "{$path}.isFacebookOnboardedCharity"),
            isMemorialized: Wire::nullableBool($data['isMemorialized'] ?? null, "{$path}.isMemorialized"),
            isNew: Wire::nullableBool($data['isNew'] ?? null, "{$path}.isNew"),
            isOpenToCollaboration: Wire::nullableBool($data['isOpenToCollaboration'] ?? null, "{$path}.isOpenToCollaboration"),
            isPotentialBusiness: Wire::nullableBool($data['isPotentialBusiness'] ?? null, "{$path}.isPotentialBusiness"),
            isPrivate: Wire::nullableBool($data['isPrivate'] ?? null, "{$path}.isPrivate"),
            isUnpublished: Wire::nullableBool($data['isUnpublished'] ?? null, "{$path}.isUnpublished"),
            isVerified: Wire::nullableBool($data['isVerified'] ?? null, "{$path}.isVerified"),
            lastStoryAt: Wire::nullableString($data['lastStoryAt'] ?? null, "{$path}.lastStoryAt"),
            location: Wire::object($data['location'] ?? [], "{$path}.location", InstagramProfileLocation::class),
            mediaPreviews: Wire::nullableList($data['mediaPreviews'] ?? null, "{$path}.mediaPreviews", static fn(mixed $item, string $path): InstagramMediaPreview => Wire::object($item, $path, InstagramMediaPreview::class)),
            messagingFbid: Wire::nullableString($data['messagingFbid'] ?? null, "{$path}.messagingFbid"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramProfileMetrics::class),
            pronouns: Wire::nullableList($data['pronouns'] ?? null, "{$path}.pronouns", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            socialContext: Wire::nullableString($data['socialContext'] ?? null, "{$path}.socialContext"),
            suggestion: Wire::nullableObject($data['suggestion'] ?? null, "{$path}.suggestion", InstagramSuggestion::class),
            threads: Wire::object($data['threads'] ?? [], "{$path}.threads", InstagramProfileThreads::class),
            upcomingEvents: Wire::nullableList($data['upcomingEvents'] ?? null, "{$path}.upcomingEvents", static fn(mixed $item): mixed => $item),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
