<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryReferenceAiLabel implements Model
{
    public function __construct(
        public readonly ?string $detectionMethod = null,
        public readonly ?bool $isSelfDisclosed = null,
        public readonly ?string $subtitle = null,
        public readonly ?string $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            detectionMethod: Wire::nullableString($data['detectionMethod'] ?? null, "{$path}.detectionMethod"),
            isSelfDisclosed: Wire::nullableBool($data['isSelfDisclosed'] ?? null, "{$path}.isSelfDisclosed"),
            subtitle: Wire::nullableString($data['subtitle'] ?? null, "{$path}.subtitle"),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
        );
    }
}
