<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramDASH implements Model
{
    public function __construct(
        public readonly ?string $manifest = null,
        public readonly ?int $qualityCount = null,
        /**
         * @var list<InstagramStreamVariant>|null
         */
        public readonly ?array $variants = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            manifest: Wire::nullableString($data['manifest'] ?? null, "{$path}.manifest"),
            qualityCount: Wire::nullableInt($data['qualityCount'] ?? null, "{$path}.qualityCount"),
            variants: Wire::nullableList($data['variants'] ?? null, "{$path}.variants", static fn(mixed $item, string $path): InstagramStreamVariant => Wire::object($item, $path, InstagramStreamVariant::class)),
        );
    }
}
