<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramComment implements Model
{
    public function __construct(
        public readonly InstagramCommentAi $ai,
        public readonly string $createdAt,
        public readonly InstagramExtracted $extracted,
        public readonly string $id,
        public readonly InstagramCommentMetrics $metrics,
        public readonly InstagramCommentRanking $ranking,
        public readonly InstagramCommentTranslation $translation,
        public readonly ?InstagramProfileReference $author = null,
        public readonly ?bool $isByPostAuthor = null,
        public readonly ?bool $isCovered = null,
        public readonly ?bool $isEdited = null,
        public readonly ?bool $isLikedByPostAuthor = null,
        public readonly ?bool $isPinned = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $keywords = null,
        /**
         * @var list<InstagramProfileReference>|null
         */
        public readonly ?array $likedByCoauthors = null,
        /**
         * @var list<InstagramImage>|null
         */
        public readonly ?array $media = null,
        public readonly ?string $parentId = null,
        public readonly ?int $pinnedPosition = null,
        public readonly ?string $postId = null,
        /**
         * @var list<InstagramProfileReference>|null
         */
        public readonly ?array $previewUsers = null,
        /**
         * @var list<InstagramCommentReference>|null
         */
        public readonly ?array $replies = null,
        public readonly ?string $replyToId = null,
        public readonly ?bool $sharingEnabled = null,
        public readonly ?string $status = null,
        public readonly ?string $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            ai: Wire::object($data['ai'] ?? [], "{$path}.ai", InstagramCommentAi::class),
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", InstagramProfileReference::class),
            createdAt: Wire::string($data['createdAt'] ?? '', "{$path}.createdAt"),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", InstagramExtracted::class),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isByPostAuthor: Wire::nullableBool($data['isByPostAuthor'] ?? null, "{$path}.isByPostAuthor"),
            isCovered: Wire::nullableBool($data['isCovered'] ?? null, "{$path}.isCovered"),
            isEdited: Wire::nullableBool($data['isEdited'] ?? null, "{$path}.isEdited"),
            isLikedByPostAuthor: Wire::nullableBool($data['isLikedByPostAuthor'] ?? null, "{$path}.isLikedByPostAuthor"),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            keywords: Wire::nullableList($data['keywords'] ?? null, "{$path}.keywords", static fn(mixed $item): mixed => $item),
            likedByCoauthors: Wire::nullableList($data['likedByCoauthors'] ?? null, "{$path}.likedByCoauthors", static fn(mixed $item, string $path): InstagramProfileReference => Wire::object($item, $path, InstagramProfileReference::class)),
            media: Wire::nullableList($data['media'] ?? null, "{$path}.media", static fn(mixed $item, string $path): InstagramImage => Wire::object($item, $path, InstagramImage::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramCommentMetrics::class),
            parentId: Wire::nullableString($data['parentId'] ?? null, "{$path}.parentId"),
            pinnedPosition: Wire::nullableInt($data['pinnedPosition'] ?? null, "{$path}.pinnedPosition"),
            postId: Wire::nullableString($data['postId'] ?? null, "{$path}.postId"),
            previewUsers: Wire::nullableList($data['previewUsers'] ?? null, "{$path}.previewUsers", static fn(mixed $item, string $path): InstagramProfileReference => Wire::object($item, $path, InstagramProfileReference::class)),
            ranking: Wire::object($data['ranking'] ?? [], "{$path}.ranking", InstagramCommentRanking::class),
            replies: Wire::nullableList($data['replies'] ?? null, "{$path}.replies", static fn(mixed $item, string $path): InstagramCommentReference => Wire::object($item, $path, InstagramCommentReference::class)),
            replyToId: Wire::nullableString($data['replyToId'] ?? null, "{$path}.replyToId"),
            sharingEnabled: Wire::nullableBool($data['sharingEnabled'] ?? null, "{$path}.sharingEnabled"),
            status: Wire::nullableString($data['status'] ?? null, "{$path}.status"),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            translation: Wire::object($data['translation'] ?? [], "{$path}.translation", InstagramCommentTranslation::class),
        );
    }
}
