<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryReferenceRemix implements Model
{
    public function __construct(
        public readonly ?bool $allowed = null,
        public readonly ?bool $carouselRemixesAllowed = null,
        public readonly ?bool $crosspostingAllowed = null,
        public readonly ?bool $hasBeenRemixed = null,
        public readonly ?bool $isRequestingRemixes = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            allowed: Wire::nullableBool($data['allowed'] ?? null, "{$path}.allowed"),
            carouselRemixesAllowed: Wire::nullableBool($data['carouselRemixesAllowed'] ?? null, "{$path}.carouselRemixesAllowed"),
            crosspostingAllowed: Wire::nullableBool($data['crosspostingAllowed'] ?? null, "{$path}.crosspostingAllowed"),
            hasBeenRemixed: Wire::nullableBool($data['hasBeenRemixed'] ?? null, "{$path}.hasBeenRemixed"),
            isRequestingRemixes: Wire::nullableBool($data['isRequestingRemixes'] ?? null, "{$path}.isRequestingRemixes"),
        );
    }
}
