<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryReferencePinning implements Model
{
    public function __construct(
        /**
         * @var list<string>|null
         */
        public readonly ?array $profileUserIds = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $reelsUserIds = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            profileUserIds: Wire::nullableList($data['profileUserIds'] ?? null, "{$path}.profileUserIds", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            reelsUserIds: Wire::nullableList($data['reelsUserIds'] ?? null, "{$path}.reelsUserIds", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
