<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryReferenceCrossposting implements Model
{
    public function __construct(
        public readonly ?bool $isFeedbackAggregated = null,
        public readonly ?bool $isSharedToFacebook = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            isFeedbackAggregated: Wire::nullableBool($data['isFeedbackAggregated'] ?? null, "{$path}.isFeedbackAggregated"),
            isSharedToFacebook: Wire::nullableBool($data['isSharedToFacebook'] ?? null, "{$path}.isSharedToFacebook"),
        );
    }
}
