<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramHighlight implements Model, FetchResource
{
    public function __construct(
        public readonly string $id,
        public readonly InstagramHighlightMetrics $metrics,
        public readonly string $url,
        public readonly ?InstagramProfileReference $author = null,
        public readonly ?InstagramImage $cover = null,
        public readonly ?string $createdAt = null,
        public readonly ?bool $isArchived = null,
        public readonly ?bool $isConvertedToReel = null,
        public readonly ?bool $isInProfileGrid = null,
        public readonly ?bool $isPinned = null,
        public readonly ?string $lastStoryAt = null,
        /**
         * @var list<InstagramStoryReference>|null
         */
        public readonly ?array $stories = null,
        public readonly ?string $title = null,
        public readonly ?string $updatedAt = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", InstagramProfileReference::class),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", InstagramImage::class),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isArchived: Wire::nullableBool($data['isArchived'] ?? null, "{$path}.isArchived"),
            isConvertedToReel: Wire::nullableBool($data['isConvertedToReel'] ?? null, "{$path}.isConvertedToReel"),
            isInProfileGrid: Wire::nullableBool($data['isInProfileGrid'] ?? null, "{$path}.isInProfileGrid"),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            lastStoryAt: Wire::nullableString($data['lastStoryAt'] ?? null, "{$path}.lastStoryAt"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramHighlightMetrics::class),
            stories: Wire::nullableList($data['stories'] ?? null, "{$path}.stories", static fn(mixed $item, string $path): InstagramStoryReference => Wire::object($item, $path, InstagramStoryReference::class)),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            updatedAt: Wire::nullableString($data['updatedAt'] ?? null, "{$path}.updatedAt"),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
        );
    }
}
