<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramTemplateSegment implements Model
{
    public function __construct(
        public readonly ?float $assetEndTime = null,
        public readonly ?float $assetStartTime = null,
        public readonly ?float $duration = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            assetEndTime: Wire::nullableFloat($data['assetEndTime'] ?? null, "{$path}.assetEndTime"),
            assetStartTime: Wire::nullableFloat($data['assetStartTime'] ?? null, "{$path}.assetStartTime"),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
        );
    }
}
