<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramAudioPart implements Model
{
    public function __construct(
        public readonly ?InstagramProfileReference $artist = null,
        public readonly ?string $artistName = null,
        public readonly ?InstagramImage $artwork = null,
        public readonly ?bool $isExplicit = null,
        public readonly ?string $musicId = null,
        public readonly ?float $parentStartTime = null,
        public readonly ?float $startTime = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            artist: Wire::nullableObject($data['artist'] ?? null, "{$path}.artist", InstagramProfileReference::class),
            artistName: Wire::nullableString($data['artistName'] ?? null, "{$path}.artistName"),
            artwork: Wire::nullableObject($data['artwork'] ?? null, "{$path}.artwork", InstagramImage::class),
            isExplicit: Wire::nullableBool($data['isExplicit'] ?? null, "{$path}.isExplicit"),
            musicId: Wire::nullableString($data['musicId'] ?? null, "{$path}.musicId"),
            parentStartTime: Wire::nullableFloat($data['parentStartTime'] ?? null, "{$path}.parentStartTime"),
            startTime: Wire::nullableFloat($data['startTime'] ?? null, "{$path}.startTime"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
