<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileContentSettings implements Model
{
    public function __construct(
        public readonly ?bool $highlightResharingEnabled = null,
        public readonly ?bool $postRemixingEnabled = null,
        public readonly ?bool $postResharingEnabled = null,
        public readonly ?bool $reelRemixingEnabled = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            highlightResharingEnabled: Wire::nullableBool($data['highlightResharingEnabled'] ?? null, "{$path}.highlightResharingEnabled"),
            postRemixingEnabled: Wire::nullableBool($data['postRemixingEnabled'] ?? null, "{$path}.postRemixingEnabled"),
            postResharingEnabled: Wire::nullableBool($data['postResharingEnabled'] ?? null, "{$path}.postResharingEnabled"),
            reelRemixingEnabled: Wire::nullableBool($data['reelRemixingEnabled'] ?? null, "{$path}.reelRemixingEnabled"),
        );
    }
}
