<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPostMetrics implements Model
{
    public function __construct(
        public readonly InstagramPostMetricsFacebook $facebook,
        public readonly InstagramPostMetricsInstagram $instagram,
        public readonly ?int $comments = null,
        public readonly ?int $likes = null,
        public readonly ?int $plays = null,
        public readonly ?int $premiumReactions = null,
        public readonly ?int $reposts = null,
        public readonly ?int $reshares = null,
        public readonly ?int $saves = null,
        public readonly ?int $views = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            facebook: Wire::object($data['facebook'] ?? [], "{$path}.facebook", InstagramPostMetricsFacebook::class),
            instagram: Wire::object($data['instagram'] ?? [], "{$path}.instagram", InstagramPostMetricsInstagram::class),
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            plays: Wire::nullableInt($data['plays'] ?? null, "{$path}.plays"),
            premiumReactions: Wire::nullableInt($data['premiumReactions'] ?? null, "{$path}.premiumReactions"),
            reposts: Wire::nullableInt($data['reposts'] ?? null, "{$path}.reposts"),
            reshares: Wire::nullableInt($data['reshares'] ?? null, "{$path}.reshares"),
            saves: Wire::nullableInt($data['saves'] ?? null, "{$path}.saves"),
            views: Wire::nullableInt($data['views'] ?? null, "{$path}.views"),
        );
    }
}
