<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileBroadcastChannel implements Model
{
    public function __construct(
        public readonly InstagramProfileBroadcastChannelCreator $creator,
        public readonly InstagramProfileBroadcastChannelMetrics $metrics,
        public readonly ?InstagramImage $avatar = null,
        public readonly ?InstagramImage $cover = null,
        public readonly ?string $id = null,
        public readonly ?string $title = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", InstagramImage::class),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", InstagramImage::class),
            creator: Wire::object($data['creator'] ?? [], "{$path}.creator", InstagramProfileBroadcastChannelCreator::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramProfileBroadcastChannelMetrics::class),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
