<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramAudio implements Model
{
    public function __construct(
        public readonly string $id,
        public readonly InstagramAudioMetrics $metrics,
        public readonly InstagramAudioSpotify $spotify,
        public readonly ?InstagramProfileReference $artist = null,
        public readonly ?string $artistId = null,
        public readonly ?string $artistName = null,
        public readonly ?InstagramImage $artwork = null,
        public readonly ?string $clusterId = null,
        public readonly ?float $compositionStartTime = null,
        public readonly ?string $createdAt = null,
        public readonly ?float $duration = null,
        public readonly ?string $fastStartUrl = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $filters = null,
        public readonly ?bool $hasLyrics = null,
        /**
         * @var list<float>|null
         */
        public readonly ?array $highlightStartTimes = null,
        public readonly ?bool $isAutomaticallyAttributed = null,
        public readonly ?bool $isCrosspostedFromFacebook = null,
        public readonly ?bool $isExplicit = null,
        public readonly ?bool $isTrending = null,
        public readonly ?string $monetizationType = null,
        public readonly ?string $musicId = null,
        public readonly ?string $originalPostId = null,
        public readonly ?float $overlapDuration = null,
        /**
         * @var list<InstagramAudioPart>|null
         */
        public readonly ?array $parts = null,
        public readonly ?string $previewUrl = null,
        public readonly ?float $startTime = null,
        public readonly ?InstagramStreaming $streaming = null,
        public readonly ?string $subtype = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            artist: Wire::nullableObject($data['artist'] ?? null, "{$path}.artist", InstagramProfileReference::class),
            artistId: Wire::nullableString($data['artistId'] ?? null, "{$path}.artistId"),
            artistName: Wire::nullableString($data['artistName'] ?? null, "{$path}.artistName"),
            artwork: Wire::nullableObject($data['artwork'] ?? null, "{$path}.artwork", InstagramImage::class),
            clusterId: Wire::nullableString($data['clusterId'] ?? null, "{$path}.clusterId"),
            compositionStartTime: Wire::nullableFloat($data['compositionStartTime'] ?? null, "{$path}.compositionStartTime"),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            fastStartUrl: Wire::nullableString($data['fastStartUrl'] ?? null, "{$path}.fastStartUrl"),
            filters: Wire::nullableList($data['filters'] ?? null, "{$path}.filters", static fn(mixed $item): mixed => $item),
            hasLyrics: Wire::nullableBool($data['hasLyrics'] ?? null, "{$path}.hasLyrics"),
            highlightStartTimes: Wire::nullableList($data['highlightStartTimes'] ?? null, "{$path}.highlightStartTimes", static fn(mixed $item, string $path): float => Wire::float($item, $path)),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isAutomaticallyAttributed: Wire::nullableBool($data['isAutomaticallyAttributed'] ?? null, "{$path}.isAutomaticallyAttributed"),
            isCrosspostedFromFacebook: Wire::nullableBool($data['isCrosspostedFromFacebook'] ?? null, "{$path}.isCrosspostedFromFacebook"),
            isExplicit: Wire::nullableBool($data['isExplicit'] ?? null, "{$path}.isExplicit"),
            isTrending: Wire::nullableBool($data['isTrending'] ?? null, "{$path}.isTrending"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramAudioMetrics::class),
            monetizationType: Wire::nullableString($data['monetizationType'] ?? null, "{$path}.monetizationType"),
            musicId: Wire::nullableString($data['musicId'] ?? null, "{$path}.musicId"),
            originalPostId: Wire::nullableString($data['originalPostId'] ?? null, "{$path}.originalPostId"),
            overlapDuration: Wire::nullableFloat($data['overlapDuration'] ?? null, "{$path}.overlapDuration"),
            parts: Wire::nullableList($data['parts'] ?? null, "{$path}.parts", static fn(mixed $item, string $path): InstagramAudioPart => Wire::object($item, $path, InstagramAudioPart::class)),
            previewUrl: Wire::nullableString($data['previewUrl'] ?? null, "{$path}.previewUrl"),
            spotify: Wire::object($data['spotify'] ?? [], "{$path}.spotify", InstagramAudioSpotify::class),
            startTime: Wire::nullableFloat($data['startTime'] ?? null, "{$path}.startTime"),
            streaming: Wire::nullableObject($data['streaming'] ?? null, "{$path}.streaming", InstagramStreaming::class),
            subtype: Wire::nullableString($data['subtype'] ?? null, "{$path}.subtype"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
