<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramSuggestion implements Model
{
    public function __construct(
        public readonly ?string $caption = null,
        public readonly ?bool $hasStoryRing = null,
        public readonly ?string $icon = null,
        public readonly ?bool $isNew = null,
        /**
         * @var list<InstagramImage>|null
         */
        public readonly ?array $largeImages = null,
        /**
         * @var list<InstagramPostReference>|null
         */
        public readonly ?array $posts = null,
        public readonly ?string $socialContext = null,
        /**
         * @var list<InstagramImage>|null
         */
        public readonly ?array $thumbnails = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            caption: Wire::nullableString($data['caption'] ?? null, "{$path}.caption"),
            hasStoryRing: Wire::nullableBool($data['hasStoryRing'] ?? null, "{$path}.hasStoryRing"),
            icon: Wire::nullableString($data['icon'] ?? null, "{$path}.icon"),
            isNew: Wire::nullableBool($data['isNew'] ?? null, "{$path}.isNew"),
            largeImages: Wire::nullableList($data['largeImages'] ?? null, "{$path}.largeImages", static fn(mixed $item, string $path): InstagramImage => Wire::object($item, $path, InstagramImage::class)),
            posts: Wire::nullableList($data['posts'] ?? null, "{$path}.posts", static fn(mixed $item, string $path): InstagramPostReference => Wire::object($item, $path, InstagramPostReference::class)),
            socialContext: Wire::nullableString($data['socialContext'] ?? null, "{$path}.socialContext"),
            thumbnails: Wire::nullableList($data['thumbnails'] ?? null, "{$path}.thumbnails", static fn(mixed $item, string $path): InstagramImage => Wire::object($item, $path, InstagramImage::class)),
        );
    }
}
