<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramMediaPreview implements Model
{
    public function __construct(
        public readonly ?string $fbid = null,
        public readonly ?string $id = null,
        public readonly ?InstagramImage $thumbnail = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            fbid: Wire::nullableString($data['fbid'] ?? null, "{$path}.fbid"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            thumbnail: Wire::nullableObject($data['thumbnail'] ?? null, "{$path}.thumbnail", InstagramImage::class),
        );
    }
}
