<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryCollectionAudience implements Model
{
    public function __construct(
        public readonly ?bool $hasCloseFriendsStories = null,
        public readonly ?bool $hasSubscriberStories = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasCloseFriendsStories: Wire::nullableBool($data['hasCloseFriendsStories'] ?? null, "{$path}.hasCloseFriendsStories"),
            hasSubscriberStories: Wire::nullableBool($data['hasSubscriberStories'] ?? null, "{$path}.hasSubscriberStories"),
        );
    }
}
