<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramBioLink implements Model
{
    public function __construct(
        public readonly ?InstagramImage $icon = null,
        public readonly ?string $id = null,
        public readonly ?InstagramImage $image = null,
        public readonly ?bool $isPinned = null,
        public readonly ?bool $isVerified = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            icon: Wire::nullableObject($data['icon'] ?? null, "{$path}.icon", InstagramImage::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            image: Wire::nullableObject($data['image'] ?? null, "{$path}.image", InstagramImage::class),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            isVerified: Wire::nullableBool($data['isVerified'] ?? null, "{$path}.isVerified"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
