<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPageMetadataMetrics implements Model
{
    public function __construct(
        public readonly ?int $comments = null,
        public readonly ?int $likes = null,
        public readonly ?int $replies = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            replies: Wire::nullableInt($data['replies'] ?? null, "{$path}.replies"),
        );
    }
}
