<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPageMetadata implements Model
{
    public function __construct(
        public readonly InstagramPageMetadataMetrics $metrics,
        public readonly ?InstagramStoryCollection $collection = null,
        public readonly ?bool $hasMore = null,
        public readonly ?bool $hasMoreAfter = null,
        public readonly ?bool $hasMoreBefore = null,
        public readonly ?bool $likesEnabled = null,
        public readonly ?InstagramCommentReference $parent = null,
        public readonly ?bool $threadingEnabled = null,
        public readonly ?InstagramAudioReference $track = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            collection: Wire::nullableObject($data['collection'] ?? null, "{$path}.collection", InstagramStoryCollection::class),
            hasMore: Wire::nullableBool($data['hasMore'] ?? null, "{$path}.hasMore"),
            hasMoreAfter: Wire::nullableBool($data['hasMoreAfter'] ?? null, "{$path}.hasMoreAfter"),
            hasMoreBefore: Wire::nullableBool($data['hasMoreBefore'] ?? null, "{$path}.hasMoreBefore"),
            likesEnabled: Wire::nullableBool($data['likesEnabled'] ?? null, "{$path}.likesEnabled"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramPageMetadataMetrics::class),
            parent: Wire::nullableObject($data['parent'] ?? null, "{$path}.parent", InstagramCommentReference::class),
            threadingEnabled: Wire::nullableBool($data['threadingEnabled'] ?? null, "{$path}.threadingEnabled"),
            track: Wire::nullableObject($data['track'] ?? null, "{$path}.track", InstagramAudioReference::class),
        );
    }
}
