<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramImage implements Model
{
    public function __construct(
        public readonly ?int $height = null,
        public readonly ?string $id = null,
        public readonly ?bool $isDefault = null,
        public readonly ?bool $isSpatial = null,
        public readonly ?InstagramImage $thumbnail = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        /**
         * @var list<InstagramImage>|null
         */
        public readonly ?array $variants = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isDefault: Wire::nullableBool($data['isDefault'] ?? null, "{$path}.isDefault"),
            isSpatial: Wire::nullableBool($data['isSpatial'] ?? null, "{$path}.isSpatial"),
            thumbnail: Wire::nullableObject($data['thumbnail'] ?? null, "{$path}.thumbnail", InstagramImage::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            variants: Wire::nullableList($data['variants'] ?? null, "{$path}.variants", static fn(mixed $item, string $path): InstagramImage => Wire::object($item, $path, InstagramImage::class)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
