<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramUserTag implements Model
{
    public function __construct(
        public readonly InstagramPosition $position,
        public readonly InstagramProfileReference $user,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            position: Wire::object($data['position'] ?? [], "{$path}.position", InstagramPosition::class),
            user: Wire::object($data['user'] ?? [], "{$path}.user", InstagramProfileReference::class),
        );
    }
}
