<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPartialError implements Model
{
    public function __construct(
        public readonly ?string $message = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $path = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            message: Wire::nullableString($data['message'] ?? null, "{$path}.message"),
            path: Wire::nullableList($data['path'] ?? null, "{$path}.path", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
