<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileThreads implements Model
{
    public function __construct(
        public readonly ?string $handle = null,
        public readonly ?bool $isActive = null,
        public readonly ?string $joinerLabel = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            handle: Wire::nullableString($data['handle'] ?? null, "{$path}.handle"),
            isActive: Wire::nullableBool($data['isActive'] ?? null, "{$path}.isActive"),
            joinerLabel: Wire::nullableString($data['joinerLabel'] ?? null, "{$path}.joinerLabel"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
