<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramSticker implements Model
{
    public function __construct(
        public readonly InstagramStickerPosition $position,
        public readonly ?InstagramAudioReference $audio = null,
        public readonly ?float $endTime = null,
        public readonly ?InstagramHashtagReference $hashtag = null,
        public readonly ?string $id = null,
        public readonly ?bool $isHidden = null,
        public readonly ?bool $isPinned = null,
        public readonly ?InstagramStickerPost $post = null,
        public readonly ?float $startTime = null,
        public readonly ?string $targetMediaId = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        public readonly ?InstagramProfileReference $user = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            audio: Wire::nullableObject($data['audio'] ?? null, "{$path}.audio", InstagramAudioReference::class),
            endTime: Wire::nullableFloat($data['endTime'] ?? null, "{$path}.endTime"),
            hashtag: Wire::nullableObject($data['hashtag'] ?? null, "{$path}.hashtag", InstagramHashtagReference::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isHidden: Wire::nullableBool($data['isHidden'] ?? null, "{$path}.isHidden"),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            position: Wire::object($data['position'] ?? [], "{$path}.position", InstagramStickerPosition::class),
            post: Wire::nullableObject($data['post'] ?? null, "{$path}.post", InstagramStickerPost::class),
            startTime: Wire::nullableFloat($data['startTime'] ?? null, "{$path}.startTime"),
            targetMediaId: Wire::nullableString($data['targetMediaId'] ?? null, "{$path}.targetMediaId"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            user: Wire::nullableObject($data['user'] ?? null, "{$path}.user", InstagramProfileReference::class),
        );
    }
}
