<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileFundraisers implements Model
{
    public function __construct(
        public readonly InstagramProfileFundraisersMetrics $metrics,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $items = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            items: Wire::nullableList($data['items'] ?? null, "{$path}.items", static fn(mixed $item): mixed => $item),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramProfileFundraisersMetrics::class),
        );
    }
}
