<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramCommentReferenceRanking implements Model
{
    public function __construct(
        public readonly ?int $index = null,
        public readonly ?bool $isRanked = null,
        public readonly ?int $replyIndex = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            index: Wire::nullableInt($data['index'] ?? null, "{$path}.index"),
            isRanked: Wire::nullableBool($data['isRanked'] ?? null, "{$path}.isRanked"),
            replyIndex: Wire::nullableInt($data['replyIndex'] ?? null, "{$path}.replyIndex"),
        );
    }
}
