<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramMediaVariant implements Model
{
    public function __construct(
        public readonly ?int $bitrate = null,
        public readonly ?int $height = null,
        public readonly ?string $id = null,
        public readonly ?bool $isSpatial = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            bitrate: Wire::nullableInt($data['bitrate'] ?? null, "{$path}.bitrate"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isSpatial: Wire::nullableBool($data['isSpatial'] ?? null, "{$path}.isSpatial"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
