<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramScrubber implements Model
{
    public function __construct(
        public readonly ?float $duration = null,
        public readonly ?int $height = null,
        public readonly ?int $maxThumbnailsPerSprite = null,
        public readonly ?float $thumbnailDuration = null,
        public readonly ?int $thumbnailHeight = null,
        public readonly ?int $thumbnailWidth = null,
        public readonly ?int $thumbnailsPerRow = null,
        public readonly ?int $thumbnailsPerSprite = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $urls = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            maxThumbnailsPerSprite: Wire::nullableInt($data['maxThumbnailsPerSprite'] ?? null, "{$path}.maxThumbnailsPerSprite"),
            thumbnailDuration: Wire::nullableFloat($data['thumbnailDuration'] ?? null, "{$path}.thumbnailDuration"),
            thumbnailHeight: Wire::nullableInt($data['thumbnailHeight'] ?? null, "{$path}.thumbnailHeight"),
            thumbnailWidth: Wire::nullableInt($data['thumbnailWidth'] ?? null, "{$path}.thumbnailWidth"),
            thumbnailsPerRow: Wire::nullableInt($data['thumbnailsPerRow'] ?? null, "{$path}.thumbnailsPerRow"),
            thumbnailsPerSprite: Wire::nullableInt($data['thumbnailsPerSprite'] ?? null, "{$path}.thumbnailsPerSprite"),
            urls: Wire::nullableList($data['urls'] ?? null, "{$path}.urls", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
