<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramClipMetadata implements Model
{
    public function __construct(
        public readonly ?InstagramAudioReference $audio = null,
        public readonly ?InstagramPartialData $partial = null,
        public readonly ?string $postId = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            audio: Wire::nullableObject($data['audio'] ?? null, "{$path}.audio", InstagramAudioReference::class),
            partial: Wire::nullableObject($data['partial'] ?? null, "{$path}.partial", InstagramPartialData::class),
            postId: Wire::nullableString($data['postId'] ?? null, "{$path}.postId"),
        );
    }
}
