<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPost implements Model, FetchResource
{
    public function __construct(
        public readonly InstagramPostAi $ai,
        public readonly InstagramPostAttribution $attribution,
        public readonly InstagramPostCarousel $carousel,
        public readonly InstagramCommentSettings $comments,
        public readonly string $createdAt,
        public readonly InstagramPostCrossposting $crossposting,
        public readonly InstagramExtracted $extracted,
        public readonly string $id,
        /**
         * @var list<InstagramMedia>
         */
        public readonly array $media,
        public readonly InstagramPostMetrics $metrics,
        public readonly InstagramPostPinning $pinning,
        public readonly InstagramPostRemix $remix,
        public readonly InstagramPostReuse $reuse,
        public readonly string $url,
        public readonly ?InstagramProfileReference $author = null,
        public readonly ?InstagramCaptionReference $caption = null,
        public readonly ?string $code = null,
        /**
         * @var list<InstagramProfileReference>|null
         */
        public readonly ?array $collaborators = null,
        public readonly ?string $fbid = null,
        public readonly ?bool $hasDelayedMetadata = null,
        public readonly ?bool $hasTaggedUsers = null,
        public readonly ?bool $hasVisualReplies = null,
        /**
         * @var list<InstagramProfileReference>|null
         */
        public readonly ?array $invitedCollaborators = null,
        public readonly ?bool $isEarlyAccess = null,
        public readonly ?bool $isFanClubPromo = null,
        public readonly ?bool $isOpenToPublicSubmission = null,
        public readonly ?bool $isPaidPartnership = null,
        public readonly ?bool $isPublicChatWelcomeVideo = null,
        public readonly ?string $language = null,
        public readonly ?bool $likeAndViewCountsHidden = null,
        public readonly ?InstagramLocationReference $location = null,
        /**
         * @var list<InstagramNote>|null
         */
        public readonly ?array $notes = null,
        /**
         * @var list<InstagramProductTag>|null
         */
        public readonly ?array $productTags = null,
        public readonly ?bool $shareCountHidden = null,
        public readonly ?bool $sharingEnabled = null,
        /**
         * @var list<InstagramUserTag>|null
         */
        public readonly ?array $taggedUsers = null,
        public readonly ?InstagramTemplateInfo $template = null,
        public readonly ?string $text = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            ai: Wire::object($data['ai'] ?? [], "{$path}.ai", InstagramPostAi::class),
            attribution: Wire::object($data['attribution'] ?? [], "{$path}.attribution", InstagramPostAttribution::class),
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", InstagramProfileReference::class),
            caption: Wire::nullableObject($data['caption'] ?? null, "{$path}.caption", InstagramCaptionReference::class),
            carousel: Wire::object($data['carousel'] ?? [], "{$path}.carousel", InstagramPostCarousel::class),
            code: Wire::nullableString($data['code'] ?? null, "{$path}.code"),
            collaborators: Wire::nullableList($data['collaborators'] ?? null, "{$path}.collaborators", static fn(mixed $item, string $path): InstagramProfileReference => Wire::object($item, $path, InstagramProfileReference::class)),
            comments: Wire::object($data['comments'] ?? [], "{$path}.comments", InstagramCommentSettings::class),
            createdAt: Wire::string($data['createdAt'] ?? '', "{$path}.createdAt"),
            crossposting: Wire::object($data['crossposting'] ?? [], "{$path}.crossposting", InstagramPostCrossposting::class),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", InstagramExtracted::class),
            fbid: Wire::nullableString($data['fbid'] ?? null, "{$path}.fbid"),
            hasDelayedMetadata: Wire::nullableBool($data['hasDelayedMetadata'] ?? null, "{$path}.hasDelayedMetadata"),
            hasTaggedUsers: Wire::nullableBool($data['hasTaggedUsers'] ?? null, "{$path}.hasTaggedUsers"),
            hasVisualReplies: Wire::nullableBool($data['hasVisualReplies'] ?? null, "{$path}.hasVisualReplies"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            invitedCollaborators: Wire::nullableList($data['invitedCollaborators'] ?? null, "{$path}.invitedCollaborators", static fn(mixed $item, string $path): InstagramProfileReference => Wire::object($item, $path, InstagramProfileReference::class)),
            isEarlyAccess: Wire::nullableBool($data['isEarlyAccess'] ?? null, "{$path}.isEarlyAccess"),
            isFanClubPromo: Wire::nullableBool($data['isFanClubPromo'] ?? null, "{$path}.isFanClubPromo"),
            isOpenToPublicSubmission: Wire::nullableBool($data['isOpenToPublicSubmission'] ?? null, "{$path}.isOpenToPublicSubmission"),
            isPaidPartnership: Wire::nullableBool($data['isPaidPartnership'] ?? null, "{$path}.isPaidPartnership"),
            isPublicChatWelcomeVideo: Wire::nullableBool($data['isPublicChatWelcomeVideo'] ?? null, "{$path}.isPublicChatWelcomeVideo"),
            language: Wire::nullableString($data['language'] ?? null, "{$path}.language"),
            likeAndViewCountsHidden: Wire::nullableBool($data['likeAndViewCountsHidden'] ?? null, "{$path}.likeAndViewCountsHidden"),
            location: Wire::nullableObject($data['location'] ?? null, "{$path}.location", InstagramLocationReference::class),
            media: Wire::list($data['media'] ?? [], "{$path}.media", static fn(mixed $item, string $path): InstagramMedia => Wire::object($item, $path, InstagramMedia::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramPostMetrics::class),
            notes: Wire::nullableList($data['notes'] ?? null, "{$path}.notes", static fn(mixed $item, string $path): InstagramNote => Wire::object($item, $path, InstagramNote::class)),
            pinning: Wire::object($data['pinning'] ?? [], "{$path}.pinning", InstagramPostPinning::class),
            productTags: Wire::nullableList($data['productTags'] ?? null, "{$path}.productTags", static fn(mixed $item, string $path): InstagramProductTag => Wire::object($item, $path, InstagramProductTag::class)),
            remix: Wire::object($data['remix'] ?? [], "{$path}.remix", InstagramPostRemix::class),
            reuse: Wire::object($data['reuse'] ?? [], "{$path}.reuse", InstagramPostReuse::class),
            shareCountHidden: Wire::nullableBool($data['shareCountHidden'] ?? null, "{$path}.shareCountHidden"),
            sharingEnabled: Wire::nullableBool($data['sharingEnabled'] ?? null, "{$path}.sharingEnabled"),
            taggedUsers: Wire::nullableList($data['taggedUsers'] ?? null, "{$path}.taggedUsers", static fn(mixed $item, string $path): InstagramUserTag => Wire::object($item, $path, InstagramUserTag::class)),
            template: Wire::nullableObject($data['template'] ?? null, "{$path}.template", InstagramTemplateInfo::class),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
        );
    }
}
