<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStoryCollection implements Model
{
    public function __construct(
        public readonly InstagramStoryCollectionAudience $audience,
        public readonly InstagramStoryCollectionMetrics $metrics,
        public readonly ?string $expiresAt = null,
        public readonly ?string $id = null,
        public readonly ?bool $isArchived = null,
        public readonly ?string $lastStoryAt = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            audience: Wire::object($data['audience'] ?? [], "{$path}.audience", InstagramStoryCollectionAudience::class),
            expiresAt: Wire::nullableString($data['expiresAt'] ?? null, "{$path}.expiresAt"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isArchived: Wire::nullableBool($data['isArchived'] ?? null, "{$path}.isArchived"),
            lastStoryAt: Wire::nullableString($data['lastStoryAt'] ?? null, "{$path}.lastStoryAt"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramStoryCollectionMetrics::class),
        );
    }
}
