<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileMetrics implements Model
{
    public function __construct(
        public readonly ?int $arEffects = null,
        public readonly ?int $followers = null,
        public readonly ?int $following = null,
        public readonly ?int $posts = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            arEffects: Wire::nullableInt($data['arEffects'] ?? null, "{$path}.arEffects"),
            followers: Wire::nullableInt($data['followers'] ?? null, "{$path}.followers"),
            following: Wire::nullableInt($data['following'] ?? null, "{$path}.following"),
            posts: Wire::nullableInt($data['posts'] ?? null, "{$path}.posts"),
        );
    }
}
