<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileBroadcastChannelCreator implements Model
{
    public function __construct(
        public readonly ?string $handle = null,
        public readonly ?string $id = null,
        public readonly ?bool $isVerified = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            handle: Wire::nullableString($data['handle'] ?? null, "{$path}.handle"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isVerified: Wire::nullableBool($data['isVerified'] ?? null, "{$path}.isVerified"),
        );
    }
}
