<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramCoordinates implements Model
{
    public function __construct(
        public readonly ?float $latitude = null,
        public readonly ?float $longitude = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            latitude: Wire::nullableFloat($data['latitude'] ?? null, "{$path}.latitude"),
            longitude: Wire::nullableFloat($data['longitude'] ?? null, "{$path}.longitude"),
        );
    }
}
