<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileContent implements Model
{
    public function __construct(
        public readonly ?bool $hasGuides = null,
        public readonly ?bool $hasHighlights = null,
        public readonly ?bool $hasLongformMedia = null,
        public readonly ?bool $hasMusic = null,
        public readonly ?bool $hasVideos = null,
        public readonly ?bool $hasVisibleNotes = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasGuides: Wire::nullableBool($data['hasGuides'] ?? null, "{$path}.hasGuides"),
            hasHighlights: Wire::nullableBool($data['hasHighlights'] ?? null, "{$path}.hasHighlights"),
            hasLongformMedia: Wire::nullableBool($data['hasLongformMedia'] ?? null, "{$path}.hasLongformMedia"),
            hasMusic: Wire::nullableBool($data['hasMusic'] ?? null, "{$path}.hasMusic"),
            hasVideos: Wire::nullableBool($data['hasVideos'] ?? null, "{$path}.hasVideos"),
            hasVisibleNotes: Wire::nullableBool($data['hasVisibleNotes'] ?? null, "{$path}.hasVisibleNotes"),
        );
    }
}
