<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileDisplaySettings implements Model
{
    public function __construct(
        public readonly ?bool $showCategory = null,
        public readonly ?bool $showPublicContacts = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            showCategory: Wire::nullableBool($data['showCategory'] ?? null, "{$path}.showCategory"),
            showPublicContacts: Wire::nullableBool($data['showPublicContacts'] ?? null, "{$path}.showPublicContacts"),
        );
    }
}
