<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramMusicStream implements Model
{
    public function __construct(
        public readonly string $id,
        /**
         * @var list<InstagramMedia>
         */
        public readonly array $media,
        public readonly InstagramMusicStreamMetrics $metrics,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            media: Wire::list($data['media'] ?? [], "{$path}.media", static fn(mixed $item, string $path): InstagramMedia => Wire::object($item, $path, InstagramMedia::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", InstagramMusicStreamMetrics::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
