<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramStickerPosition implements Model
{
    public function __construct(
        public readonly ?float $height = null,
        public readonly ?float $rotation = null,
        public readonly ?float $width = null,
        public readonly ?float $x = null,
        public readonly ?float $y = null,
        public readonly ?float $z = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableFloat($data['height'] ?? null, "{$path}.height"),
            rotation: Wire::nullableFloat($data['rotation'] ?? null, "{$path}.rotation"),
            width: Wire::nullableFloat($data['width'] ?? null, "{$path}.width"),
            x: Wire::nullableFloat($data['x'] ?? null, "{$path}.x"),
            y: Wire::nullableFloat($data['y'] ?? null, "{$path}.y"),
            z: Wire::nullableFloat($data['z'] ?? null, "{$path}.z"),
        );
    }
}
