<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramCaptionReference implements Model
{
    public function __construct(
        public readonly InstagramCaptionReferenceRanking $ranking,
        public readonly InstagramCaptionReferenceTranslation $translation,
        public readonly ?string $createdAt = null,
        public readonly ?string $id = null,
        public readonly ?bool $isCovered = null,
        public readonly ?bool $isEdited = null,
        public readonly ?bool $sharingEnabled = null,
        public readonly ?string $status = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isCovered: Wire::nullableBool($data['isCovered'] ?? null, "{$path}.isCovered"),
            isEdited: Wire::nullableBool($data['isEdited'] ?? null, "{$path}.isEdited"),
            ranking: Wire::object($data['ranking'] ?? [], "{$path}.ranking", InstagramCaptionReferenceRanking::class),
            sharingEnabled: Wire::nullableBool($data['sharingEnabled'] ?? null, "{$path}.sharingEnabled"),
            status: Wire::nullableString($data['status'] ?? null, "{$path}.status"),
            translation: Wire::object($data['translation'] ?? [], "{$path}.translation", InstagramCaptionReferenceTranslation::class),
        );
    }
}
