<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPrice implements Model
{
    public function __construct(
        public readonly ?string $amount = null,
        public readonly ?string $formatted = null,
        public readonly ?string $strippedFormatted = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            amount: Wire::nullableString($data['amount'] ?? null, "{$path}.amount"),
            formatted: Wire::nullableString($data['formatted'] ?? null, "{$path}.formatted"),
            strippedFormatted: Wire::nullableString($data['strippedFormatted'] ?? null, "{$path}.strippedFormatted"),
        );
    }
}
