<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramCommentSettings implements Model
{
    public function __construct(
        public readonly ?bool $enabled = null,
        public readonly ?bool $hasMore = null,
        public readonly ?bool $likesEnabled = null,
        public readonly ?int $maxVisiblePreviewComments = null,
        /**
         * @var list<InstagramCommentReference>|null
         */
        public readonly ?array $preview = null,
        public readonly ?bool $threadingEnabled = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            enabled: Wire::nullableBool($data['enabled'] ?? null, "{$path}.enabled"),
            hasMore: Wire::nullableBool($data['hasMore'] ?? null, "{$path}.hasMore"),
            likesEnabled: Wire::nullableBool($data['likesEnabled'] ?? null, "{$path}.likesEnabled"),
            maxVisiblePreviewComments: Wire::nullableInt($data['maxVisiblePreviewComments'] ?? null, "{$path}.maxVisiblePreviewComments"),
            preview: Wire::nullableList($data['preview'] ?? null, "{$path}.preview", static fn(mixed $item, string $path): InstagramCommentReference => Wire::object($item, $path, InstagramCommentReference::class)),
            threadingEnabled: Wire::nullableBool($data['threadingEnabled'] ?? null, "{$path}.threadingEnabled"),
        );
    }
}
