<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramPostInsightMetricsShopping implements Model
{
    public function __construct(
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $productClicks = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $productOutboundClicks = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            productClicks: Wire::nullableList($data['productClicks'] ?? null, "{$path}.productClicks", static fn(mixed $item): mixed => $item),
            productOutboundClicks: Wire::nullableList($data['productOutboundClicks'] ?? null, "{$path}.productOutboundClicks", static fn(mixed $item): mixed => $item),
        );
    }
}
