<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileContact implements Model
{
    public function __construct(
        public readonly ?string $contactPhone = null,
        public readonly ?string $email = null,
        public readonly ?string $method = null,
        public readonly ?string $phone = null,
        public readonly ?string $phoneCountryCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            contactPhone: Wire::nullableString($data['contactPhone'] ?? null, "{$path}.contactPhone"),
            email: Wire::nullableString($data['email'] ?? null, "{$path}.email"),
            method: Wire::nullableString($data['method'] ?? null, "{$path}.method"),
            phone: Wire::nullableString($data['phone'] ?? null, "{$path}.phone"),
            phoneCountryCode: Wire::nullableString($data['phoneCountryCode'] ?? null, "{$path}.phoneCountryCode"),
        );
    }
}
