<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramLocationReference implements Model
{
    public function __construct(
        public readonly InstagramLocationAddress $address,
        public readonly InstagramCoordinates $coordinates,
        public readonly InstagramLocationReferenceExternal $external,
        public readonly InstagramLocationReferenceSearchContext $searchContext,
        public readonly ?string $category = null,
        public readonly ?InstagramLocationHours $hours = null,
        public readonly ?string $id = null,
        public readonly ?string $name = null,
        public readonly ?string $phone = null,
        public readonly ?string $shortName = null,
        public readonly ?string $url = null,
        public readonly ?string $website = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            address: Wire::object($data['address'] ?? [], "{$path}.address", InstagramLocationAddress::class),
            category: Wire::nullableString($data['category'] ?? null, "{$path}.category"),
            coordinates: Wire::object($data['coordinates'] ?? [], "{$path}.coordinates", InstagramCoordinates::class),
            external: Wire::object($data['external'] ?? [], "{$path}.external", InstagramLocationReferenceExternal::class),
            hours: Wire::nullableObject($data['hours'] ?? null, "{$path}.hours", InstagramLocationHours::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            phone: Wire::nullableString($data['phone'] ?? null, "{$path}.phone"),
            searchContext: Wire::object($data['searchContext'] ?? [], "{$path}.searchContext", InstagramLocationReferenceSearchContext::class),
            shortName: Wire::nullableString($data['shortName'] ?? null, "{$path}.shortName"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            website: Wire::nullableString($data['website'] ?? null, "{$path}.website"),
        );
    }
}
