<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileAddress implements Model
{
    public function __construct(
        public readonly ?string $city = null,
        public readonly ?string $cityId = null,
        public readonly ?string $postalCode = null,
        public readonly ?string $street = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            city: Wire::nullableString($data['city'] ?? null, "{$path}.city"),
            cityId: Wire::nullableString($data['cityId'] ?? null, "{$path}.cityId"),
            postalCode: Wire::nullableString($data['postalCode'] ?? null, "{$path}.postalCode"),
            street: Wire::nullableString($data['street'] ?? null, "{$path}.street"),
        );
    }
}
