<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class InstagramProfileBroadcastChannels implements Model
{
    public function __construct(
        public readonly ?bool $hasPublicChannels = null,
        public readonly ?bool $isCreator = null,
        /**
         * @var list<InstagramProfileBroadcastChannel>|null
         */
        public readonly ?array $pinned = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasPublicChannels: Wire::nullableBool($data['hasPublicChannels'] ?? null, "{$path}.hasPublicChannels"),
            isCreator: Wire::nullableBool($data['isCreator'] ?? null, "{$path}.isCreator"),
            pinned: Wire::nullableList($data['pinned'] ?? null, "{$path}.pinned", static fn(mixed $item, string $path): InstagramProfileBroadcastChannel => Wire::object($item, $path, InstagramProfileBroadcastChannel::class)),
        );
    }
}
