<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditProfile implements Model, FetchResource
{
    public function __construct(
        public readonly RedditExtracted $extracted,
        public readonly string $handle,
        public readonly string $id,
        public readonly RedditProfileMetrics $metrics,
        public readonly string $url,
        public readonly RedditVerification $verification,
        public readonly RedditProfileVisibility $visibility,
        public readonly ?bool $acceptsFollowers = null,
        public readonly ?RedditImage $avatar = null,
        public readonly ?RedditImage $banner = null,
        public readonly ?string $bio = null,
        public readonly ?string $createdAt = null,
        public readonly ?string $displayHandle = null,
        public readonly ?string $displayName = null,
        public readonly ?bool $isEmployee = null,
        public readonly ?bool $isModerator = null,
        public readonly ?bool $isPremium = null,
        public readonly ?bool $isSensitive = null,
        public readonly ?RedditProfileCommunity $profileCommunity = null,
        public readonly ?RedditImage $snoovatar = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            acceptsFollowers: Wire::nullableBool($data['acceptsFollowers'] ?? null, "{$path}.acceptsFollowers"),
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", RedditImage::class),
            banner: Wire::nullableObject($data['banner'] ?? null, "{$path}.banner", RedditImage::class),
            bio: Wire::nullableString($data['bio'] ?? null, "{$path}.bio"),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            displayHandle: Wire::nullableString($data['displayHandle'] ?? null, "{$path}.displayHandle"),
            displayName: Wire::nullableString($data['displayName'] ?? null, "{$path}.displayName"),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", RedditExtracted::class),
            handle: Wire::string($data['handle'] ?? '', "{$path}.handle"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isEmployee: Wire::nullableBool($data['isEmployee'] ?? null, "{$path}.isEmployee"),
            isModerator: Wire::nullableBool($data['isModerator'] ?? null, "{$path}.isModerator"),
            isPremium: Wire::nullableBool($data['isPremium'] ?? null, "{$path}.isPremium"),
            isSensitive: Wire::nullableBool($data['isSensitive'] ?? null, "{$path}.isSensitive"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", RedditProfileMetrics::class),
            profileCommunity: Wire::nullableObject($data['profileCommunity'] ?? null, "{$path}.profileCommunity", RedditProfileCommunity::class),
            snoovatar: Wire::nullableObject($data['snoovatar'] ?? null, "{$path}.snoovatar", RedditImage::class),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
            verification: Wire::object($data['verification'] ?? [], "{$path}.verification", RedditVerification::class),
            visibility: Wire::object($data['visibility'] ?? [], "{$path}.visibility", RedditProfileVisibility::class),
        );
    }
}
