<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditPostMetrics implements Model
{
    public function __construct(
        public readonly ?int $awards = null,
        public readonly ?int $comments = null,
        public readonly ?int $crossposts = null,
        public readonly ?int $gilded = null,
        public readonly ?int $score = null,
        public readonly ?float $upvoteRatio = null,
        public readonly ?int $views = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            awards: Wire::nullableInt($data['awards'] ?? null, "{$path}.awards"),
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            crossposts: Wire::nullableInt($data['crossposts'] ?? null, "{$path}.crossposts"),
            gilded: Wire::nullableInt($data['gilded'] ?? null, "{$path}.gilded"),
            score: Wire::nullableInt($data['score'] ?? null, "{$path}.score"),
            upvoteRatio: Wire::nullableFloat($data['upvoteRatio'] ?? null, "{$path}.upvoteRatio"),
            views: Wire::nullableInt($data['views'] ?? null, "{$path}.views"),
        );
    }
}
