<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditAuthor implements Model
{
    public function __construct(
        public readonly ?RedditFlair $flair = null,
        public readonly ?string $handle = null,
        public readonly ?string $id = null,
        public readonly ?bool $isPremium = null,
        public readonly ?string $placeholder = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            flair: Wire::nullableObject($data['flair'] ?? null, "{$path}.flair", RedditFlair::class),
            handle: Wire::nullableString($data['handle'] ?? null, "{$path}.handle"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isPremium: Wire::nullableBool($data['isPremium'] ?? null, "{$path}.isPremium"),
            placeholder: Wire::nullableString($data['placeholder'] ?? null, "{$path}.placeholder"),
        );
    }
}
