<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditCommentDisplay implements Model
{
    public function __construct(
        public readonly ?string $collapsedReason = null,
        public readonly ?bool $isCollapsed = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            collapsedReason: Wire::nullableString($data['collapsedReason'] ?? null, "{$path}.collapsedReason"),
            isCollapsed: Wire::nullableBool($data['isCollapsed'] ?? null, "{$path}.isCollapsed"),
        );
    }
}
