<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditEmbed implements Model
{
    public function __construct(
        public readonly ?RedditEmbedAuthor $author = null,
        public readonly ?string $domain = null,
        public readonly ?int $height = null,
        public readonly ?string $html = null,
        public readonly ?string $mediaDomainUrl = null,
        public readonly ?RedditEmbedSource $provider = null,
        public readonly ?bool $scrolling = null,
        public readonly ?RedditThumbnail $thumbnail = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
        public readonly ?string $version = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", RedditEmbedAuthor::class),
            domain: Wire::nullableString($data['domain'] ?? null, "{$path}.domain"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            html: Wire::nullableString($data['html'] ?? null, "{$path}.html"),
            mediaDomainUrl: Wire::nullableString($data['mediaDomainUrl'] ?? null, "{$path}.mediaDomainUrl"),
            provider: Wire::nullableObject($data['provider'] ?? null, "{$path}.provider", RedditEmbedSource::class),
            scrolling: Wire::nullableBool($data['scrolling'] ?? null, "{$path}.scrolling"),
            thumbnail: Wire::nullableObject($data['thumbnail'] ?? null, "{$path}.thumbnail", RedditThumbnail::class),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            version: Wire::nullableString($data['version'] ?? null, "{$path}.version"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
