<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditThumbnail implements Model
{
    public function __construct(
        public readonly ?int $height = null,
        public readonly ?string $state = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            state: Wire::nullableString($data['state'] ?? null, "{$path}.state"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
