<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditTrophy implements Model
{
    public function __construct(
        public readonly string $name,
        public readonly ?string $awardId = null,
        public readonly ?string $description = null,
        public readonly ?string $grantedAt = null,
        public readonly ?RedditImage $icon = null,
        public readonly ?string $id = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            awardId: Wire::nullableString($data['awardId'] ?? null, "{$path}.awardId"),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            grantedAt: Wire::nullableString($data['grantedAt'] ?? null, "{$path}.grantedAt"),
            icon: Wire::nullableObject($data['icon'] ?? null, "{$path}.icon", RedditImage::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            name: Wire::string($data['name'] ?? '', "{$path}.name"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
