<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditCommentSettings implements Model
{
    public function __construct(
        public readonly ?bool $restrictCommenting = null,
        public readonly ?int $scoreHideDuration = null,
        public readonly ?string $suggestedSort = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            restrictCommenting: Wire::nullableBool($data['restrictCommenting'] ?? null, "{$path}.restrictCommenting"),
            scoreHideDuration: Wire::nullableInt($data['scoreHideDuration'] ?? null, "{$path}.scoreHideDuration"),
            suggestedSort: Wire::nullableString($data['suggestedSort'] ?? null, "{$path}.suggestedSort"),
        );
    }
}
