<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditWikiPage implements Model
{
    public function __construct(
        public readonly string $title,
        public readonly string $url,
        public readonly ?RedditWikiContent $content = null,
        public readonly ?RedditWikiRevision $revision = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            content: Wire::nullableObject($data['content'] ?? null, "{$path}.content", RedditWikiContent::class),
            revision: Wire::nullableObject($data['revision'] ?? null, "{$path}.revision", RedditWikiRevision::class),
            title: Wire::string($data['title'] ?? '', "{$path}.title"),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
        );
    }
}
