<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditWikiContent implements Model
{
    public function __construct(
        public readonly ?string $html = null,
        public readonly ?string $markdown = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            html: Wire::nullableString($data['html'] ?? null, "{$path}.html"),
            markdown: Wire::nullableString($data['markdown'] ?? null, "{$path}.markdown"),
        );
    }
}
