<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditCommentsSetting implements Model
{
    public function __construct(
        public readonly ?bool $allowLiveComments = null,
        public readonly ?string $discussionType = null,
        public readonly ?bool $isContestMode = null,
        public readonly ?string $suggestedSort = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            allowLiveComments: Wire::nullableBool($data['allowLiveComments'] ?? null, "{$path}.allowLiveComments"),
            discussionType: Wire::nullableString($data['discussionType'] ?? null, "{$path}.discussionType"),
            isContestMode: Wire::nullableBool($data['isContestMode'] ?? null, "{$path}.isContestMode"),
            suggestedSort: Wire::nullableString($data['suggestedSort'] ?? null, "{$path}.suggestedSort"),
        );
    }
}
