<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditSubredditColors implements Model
{
    public function __construct(
        public readonly ?string $bannerBackground = null,
        public readonly ?string $key = null,
        public readonly ?string $primary = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            bannerBackground: Wire::nullableString($data['bannerBackground'] ?? null, "{$path}.bannerBackground"),
            key: Wire::nullableString($data['key'] ?? null, "{$path}.key"),
            primary: Wire::nullableString($data['primary'] ?? null, "{$path}.primary"),
        );
    }
}
