<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditEmbedAuthor implements Model
{
    public function __construct(
        public readonly ?string $displayName = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            displayName: Wire::nullableString($data['displayName'] ?? null, "{$path}.displayName"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
