<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditCommunity implements Model
{
    public function __construct(
        public readonly RedditSubredditMetrics $metrics,
        public readonly ?string $displayHandle = null,
        public readonly ?string $handle = null,
        public readonly ?string $id = null,
        public readonly ?bool $isQuarantined = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            displayHandle: Wire::nullableString($data['displayHandle'] ?? null, "{$path}.displayHandle"),
            handle: Wire::nullableString($data['handle'] ?? null, "{$path}.handle"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isQuarantined: Wire::nullableBool($data['isQuarantined'] ?? null, "{$path}.isQuarantined"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", RedditSubredditMetrics::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
