<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditKarma implements Model
{
    public function __construct(
        public readonly ?int $awardee = null,
        public readonly ?int $awarder = null,
        public readonly ?int $comments = null,
        public readonly ?int $posts = null,
        public readonly ?int $total = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            awardee: Wire::nullableInt($data['awardee'] ?? null, "{$path}.awardee"),
            awarder: Wire::nullableInt($data['awarder'] ?? null, "{$path}.awarder"),
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            posts: Wire::nullableInt($data['posts'] ?? null, "{$path}.posts"),
            total: Wire::nullableInt($data['total'] ?? null, "{$path}.total"),
        );
    }
}
