<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditVerification implements Model
{
    public function __construct(
        public readonly ?bool $hasVerifiedEmail = null,
        public readonly ?bool $reportedVerified = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasVerifiedEmail: Wire::nullableBool($data['hasVerifiedEmail'] ?? null, "{$path}.hasVerifiedEmail"),
            reportedVerified: Wire::nullableBool($data['reportedVerified'] ?? null, "{$path}.reportedVerified"),
        );
    }
}
