<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditFlair implements Model
{
    public function __construct(
        public readonly ?string $backgroundColor = null,
        public readonly ?string $cssClass = null,
        public readonly ?bool $hasPatreonFlair = null,
        public readonly ?string $templateId = null,
        public readonly ?string $text = null,
        public readonly ?string $textColor = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            backgroundColor: Wire::nullableString($data['backgroundColor'] ?? null, "{$path}.backgroundColor"),
            cssClass: Wire::nullableString($data['cssClass'] ?? null, "{$path}.cssClass"),
            hasPatreonFlair: Wire::nullableBool($data['hasPatreonFlair'] ?? null, "{$path}.hasPatreonFlair"),
            templateId: Wire::nullableString($data['templateId'] ?? null, "{$path}.templateId"),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            textColor: Wire::nullableString($data['textColor'] ?? null, "{$path}.textColor"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
