<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditImage implements Model
{
    public function __construct(
        public readonly ?int $height = null,
        public readonly ?string $label = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        /**
         * @var list<RedditImage>|null
         */
        public readonly ?array $variants = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            variants: Wire::nullableList($data['variants'] ?? null, "{$path}.variants", static fn(mixed $item, string $path): RedditImage => Wire::object($item, $path, RedditImage::class)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
