<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class RedditListingContext implements Model
{
    public function __construct(
        public readonly ?RedditPostReference $originalPost = null,
        public readonly ?RedditPostReference $post = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            originalPost: Wire::nullableObject($data['originalPost'] ?? null, "{$path}.originalPost", RedditPostReference::class),
            post: Wire::nullableObject($data['post'] ?? null, "{$path}.post", RedditPostReference::class),
        );
    }
}
