<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TestDataOperation implements Model
{
    public function __construct(
        public readonly string $description,
        public readonly string $id,
        /**
         * @var list<string>
         */
        public readonly array $inputFields,
        /**
         * @var list<string>
         */
        public readonly array $locators,
        /**
         * @var 'GET'
         */
        public readonly string $method,
        public readonly bool $paginated,
        public readonly string $path,
        /**
         * @var 'instagram'|'tiktok'|'twitter'|'reddit'
         */
        public readonly string $platform,
        public readonly string $publicSchema,
        /**
         * @var 'profile'|'post'|'comment'|'hashtag'|'location'|'music'|'category'|'list'|'entity'|'subreddit'|'rule'|'wiki'|'trophy'
         */
        public readonly string $resource,
        public readonly string $summary,
        public readonly string $toolName,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            description: Wire::string($data['description'] ?? '', "{$path}.description"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            inputFields: Wire::list($data['inputFields'] ?? [], "{$path}.inputFields", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            locators: Wire::list($data['locators'] ?? [], "{$path}.locators", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            method: Wire::enum($data['method'] ?? null, "{$path}.method", ['GET']),
            paginated: Wire::bool($data['paginated'] ?? false, "{$path}.paginated"),
            path: Wire::string($data['path'] ?? '', "{$path}.path"),
            platform: Wire::enum($data['platform'] ?? null, "{$path}.platform", ['instagram', 'tiktok', 'twitter', 'reddit']),
            publicSchema: Wire::string($data['publicSchema'] ?? '', "{$path}.publicSchema"),
            resource: Wire::enum($data['resource'] ?? null, "{$path}.resource", ['profile', 'post', 'comment', 'hashtag', 'location', 'music', 'category', 'list', 'entity', 'subreddit', 'rule', 'wiki', 'trophy']),
            summary: Wire::string($data['summary'] ?? '', "{$path}.summary"),
            toolName: Wire::string($data['toolName'] ?? '', "{$path}.toolName"),
        );
    }
}
