<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TestDataExpectedResult implements Model
{
    public function __construct(
        /**
         * @var 200|403|404
         */
        public readonly int $status,
        public readonly ?string $errorCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            errorCode: Wire::nullableString($data['errorCode'] ?? null, "{$path}.errorCode"),
            status: Wire::enum($data['status'] ?? null, "{$path}.status", [200, 403, 404]),
        );
    }
}
