<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TestDataRelationship implements Model
{
    public function __construct(
        public readonly string $entryId,
        public readonly string $type,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            entryId: Wire::string($data['entryId'] ?? '', "{$path}.entryId"),
            type: Wire::string($data['type'] ?? '', "{$path}.type"),
        );
    }
}
