<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokHashtagReference implements Model
{
    public function __construct(
        public readonly ?string $id = null,
        public readonly ?string $name = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
