<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokEffectTrigger implements Model
{
    public function __construct(
        /**
         * @var list<int>|null
         */
        public readonly ?array $actionCodes = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            actionCodes: Wire::nullableList($data['actionCodes'] ?? null, "{$path}.actionCodes", static fn(mixed $item, string $path): int => Wire::int($item, $path)),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
