<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileSearchContext implements Model
{
    public function __construct(
        public readonly ?string $description = null,
        public readonly ?string $name = null,
        public readonly ?string $nameField = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            nameField: Wire::nullableString($data['nameField'] ?? null, "{$path}.nameField"),
        );
    }
}
