<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProduct implements Model
{
    public function __construct(
        public readonly TikTokProductPricing $pricing,
        /**
         * @var list<TikTokProductCategory>|null
         */
        public readonly ?array $categories = null,
        public readonly ?TikTokImage $cover = null,
        public readonly ?string $disclosureLabel = null,
        public readonly ?string $id = null,
        /**
         * @var list<TikTokImage>|null
         */
        public readonly ?array $images = null,
        public readonly ?bool $inShop = null,
        public readonly ?bool $isPlatformProduct = null,
        public readonly ?string $label = null,
        public readonly ?string $name = null,
        public readonly ?int $platformCode = null,
        public readonly ?string $sellerId = null,
        public readonly ?string $shortName = null,
        /**
         * @var list<TikTokProductSKU>|null
         */
        public readonly ?array $skus = null,
        public readonly ?string $source = null,
        public readonly ?int $statusCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            categories: Wire::nullableList($data['categories'] ?? null, "{$path}.categories", static fn(mixed $item, string $path): TikTokProductCategory => Wire::object($item, $path, TikTokProductCategory::class)),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", TikTokImage::class),
            disclosureLabel: Wire::nullableString($data['disclosureLabel'] ?? null, "{$path}.disclosureLabel"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            images: Wire::nullableList($data['images'] ?? null, "{$path}.images", static fn(mixed $item, string $path): TikTokImage => Wire::object($item, $path, TikTokImage::class)),
            inShop: Wire::nullableBool($data['inShop'] ?? null, "{$path}.inShop"),
            isPlatformProduct: Wire::nullableBool($data['isPlatformProduct'] ?? null, "{$path}.isPlatformProduct"),
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            platformCode: Wire::nullableInt($data['platformCode'] ?? null, "{$path}.platformCode"),
            pricing: Wire::object($data['pricing'] ?? [], "{$path}.pricing", TikTokProductPricing::class),
            sellerId: Wire::nullableString($data['sellerId'] ?? null, "{$path}.sellerId"),
            shortName: Wire::nullableString($data['shortName'] ?? null, "{$path}.shortName"),
            skus: Wire::nullableList($data['skus'] ?? null, "{$path}.skus", static fn(mixed $item, string $path): TikTokProductSKU => Wire::object($item, $path, TikTokProductSKU::class)),
            source: Wire::nullableString($data['source'] ?? null, "{$path}.source"),
            statusCode: Wire::nullableInt($data['statusCode'] ?? null, "{$path}.statusCode"),
        );
    }
}
