<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfile implements Model, FetchResource
{
    public function __construct(
        public readonly TikTokProfileCommerce $commerce,
        public readonly TikTokExtracted $extracted,
        public readonly string $handle,
        public readonly string $id,
        public readonly TikTokProfileMetrics $metrics,
        public readonly TikTokProfileMusic $music,
        public readonly TikTokProfilePredictions $predictions,
        public readonly TikTokProfilePrivacy $privacy,
        public readonly TikTokProfileSearchContext $searchContext,
        public readonly TikTokProfileStories $stories,
        public readonly string $url,
        public readonly TikTokProfileVerification $verification,
        public readonly ?int $accountType = null,
        public readonly ?TikTokImage $avatar = null,
        public readonly ?string $bio = null,
        public readonly ?string $category = null,
        public readonly ?string $createdAt = null,
        public readonly ?string $displayName = null,
        public readonly ?bool $isAdVirtual = null,
        public readonly ?bool $isCanceled = null,
        public readonly ?bool $isDisciplineMember = null,
        public readonly ?bool $isEffectArtist = null,
        public readonly ?bool $isPrivate = null,
        public readonly ?bool $isStar = null,
        public readonly ?bool $isVerified = null,
        public readonly ?string $language = null,
        public readonly ?string $regionCode = null,
        public readonly ?string $secUid = null,
        /**
         * @var list<TikTokSocialLink>|null
         */
        public readonly ?array $socialLinks = null,
        public readonly ?int $storyStatus = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            accountType: Wire::nullableInt($data['accountType'] ?? null, "{$path}.accountType"),
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", TikTokImage::class),
            bio: Wire::nullableString($data['bio'] ?? null, "{$path}.bio"),
            category: Wire::nullableString($data['category'] ?? null, "{$path}.category"),
            commerce: Wire::object($data['commerce'] ?? [], "{$path}.commerce", TikTokProfileCommerce::class),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            displayName: Wire::nullableString($data['displayName'] ?? null, "{$path}.displayName"),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", TikTokExtracted::class),
            handle: Wire::string($data['handle'] ?? '', "{$path}.handle"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isAdVirtual: Wire::nullableBool($data['isAdVirtual'] ?? null, "{$path}.isAdVirtual"),
            isCanceled: Wire::nullableBool($data['isCanceled'] ?? null, "{$path}.isCanceled"),
            isDisciplineMember: Wire::nullableBool($data['isDisciplineMember'] ?? null, "{$path}.isDisciplineMember"),
            isEffectArtist: Wire::nullableBool($data['isEffectArtist'] ?? null, "{$path}.isEffectArtist"),
            isPrivate: Wire::nullableBool($data['isPrivate'] ?? null, "{$path}.isPrivate"),
            isStar: Wire::nullableBool($data['isStar'] ?? null, "{$path}.isStar"),
            isVerified: Wire::nullableBool($data['isVerified'] ?? null, "{$path}.isVerified"),
            language: Wire::nullableString($data['language'] ?? null, "{$path}.language"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokProfileMetrics::class),
            music: Wire::object($data['music'] ?? [], "{$path}.music", TikTokProfileMusic::class),
            predictions: Wire::object($data['predictions'] ?? [], "{$path}.predictions", TikTokProfilePredictions::class),
            privacy: Wire::object($data['privacy'] ?? [], "{$path}.privacy", TikTokProfilePrivacy::class),
            regionCode: Wire::nullableString($data['regionCode'] ?? null, "{$path}.regionCode"),
            searchContext: Wire::object($data['searchContext'] ?? [], "{$path}.searchContext", TikTokProfileSearchContext::class),
            secUid: Wire::nullableString($data['secUid'] ?? null, "{$path}.secUid"),
            socialLinks: Wire::nullableList($data['socialLinks'] ?? null, "{$path}.socialLinks", static fn(mixed $item, string $path): TikTokSocialLink => Wire::object($item, $path, TikTokSocialLink::class)),
            stories: Wire::object($data['stories'] ?? [], "{$path}.stories", TikTokProfileStories::class),
            storyStatus: Wire::nullableInt($data['storyStatus'] ?? null, "{$path}.storyStatus"),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
            verification: Wire::object($data['verification'] ?? [], "{$path}.verification", TikTokProfileVerification::class),
        );
    }
}
