<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileMusicMetrics implements Model
{
    public function __construct(
        public readonly ?int $likes = null,
        public readonly ?int $tracks = null,
        public readonly ?int $uses = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            tracks: Wire::nullableInt($data['tracks'] ?? null, "{$path}.tracks"),
            uses: Wire::nullableInt($data['uses'] ?? null, "{$path}.uses"),
        );
    }
}
