<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPost implements Model, FetchResource
{
    public function __construct(
        public readonly TikTokPostAI $ai,
        public readonly TikTokPostAudio $audio,
        public readonly TikTokPostCaption $caption,
        public readonly TikTokPostCommerce $commerce,
        public readonly string $createdAt,
        public readonly TikTokExtracted $extracted,
        /**
         * @var list<TikTokHashtagReference>
         */
        public readonly array $hashtags,
        public readonly string $id,
        /**
         * @var list<TikTokMedia>
         */
        public readonly array $media,
        public readonly TikTokPostMetrics $metrics,
        public readonly TikTokMusicContext $musicContext,
        public readonly TikTokPostSearchContext $searchContext,
        public readonly TikTokPostStatus $status,
        public readonly string $url,
        public readonly ?TikTokProfileReference $author = null,
        public readonly ?string $authorId = null,
        /**
         * @var list<TikTokCollaborator>|null
         */
        public readonly ?array $collaborators = null,
        public readonly ?TikTokImage $cover = null,
        public readonly ?string $description = null,
        /**
         * @var list<TikTokEffectReference>|null
         */
        public readonly ?array $effects = null,
        /**
         * @var list<TikTokTextEntity>|null
         */
        public readonly ?array $entities = null,
        public readonly ?bool $hasDanmaku = null,
        public readonly ?bool $hasPromotionalMusic = null,
        public readonly ?bool $isAd = null,
        public readonly ?bool $isMeme = null,
        public readonly ?bool $isPaidContent = null,
        public readonly ?bool $isPinned = null,
        public readonly ?bool $isVr = null,
        public readonly ?string $language = null,
        /**
         * @var list<TikTokLocationReference>|null
         */
        public readonly ?array $locations = null,
        /**
         * @var list<array<string, mixed>>|null
         */
        public readonly ?array $onScreenText = null,
        public readonly ?string $paidCollectionId = null,
        public readonly ?TikTokPlaylistReference $playlist = null,
        public readonly ?string $region = null,
        /**
         * @var list<TikTokInteractionSticker>|null
         */
        public readonly ?array $stickers = null,
        public readonly ?TikTokPostTemplate $template = null,
        public readonly ?string $text = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            ai: Wire::object($data['ai'] ?? [], "{$path}.ai", TikTokPostAI::class),
            audio: Wire::object($data['audio'] ?? [], "{$path}.audio", TikTokPostAudio::class),
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", TikTokProfileReference::class),
            authorId: Wire::nullableString($data['authorId'] ?? null, "{$path}.authorId"),
            caption: Wire::object($data['caption'] ?? [], "{$path}.caption", TikTokPostCaption::class),
            collaborators: Wire::nullableList($data['collaborators'] ?? null, "{$path}.collaborators", static fn(mixed $item, string $path): TikTokCollaborator => Wire::object($item, $path, TikTokCollaborator::class)),
            commerce: Wire::object($data['commerce'] ?? [], "{$path}.commerce", TikTokPostCommerce::class),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", TikTokImage::class),
            createdAt: Wire::string($data['createdAt'] ?? '', "{$path}.createdAt"),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            effects: Wire::nullableList($data['effects'] ?? null, "{$path}.effects", static fn(mixed $item, string $path): TikTokEffectReference => Wire::object($item, $path, TikTokEffectReference::class)),
            entities: Wire::nullableList($data['entities'] ?? null, "{$path}.entities", static fn(mixed $item, string $path): TikTokTextEntity => Wire::object($item, $path, TikTokTextEntity::class)),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", TikTokExtracted::class),
            hasDanmaku: Wire::nullableBool($data['hasDanmaku'] ?? null, "{$path}.hasDanmaku"),
            hasPromotionalMusic: Wire::nullableBool($data['hasPromotionalMusic'] ?? null, "{$path}.hasPromotionalMusic"),
            hashtags: Wire::list($data['hashtags'] ?? [], "{$path}.hashtags", static fn(mixed $item, string $path): TikTokHashtagReference => Wire::object($item, $path, TikTokHashtagReference::class)),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isAd: Wire::nullableBool($data['isAd'] ?? null, "{$path}.isAd"),
            isMeme: Wire::nullableBool($data['isMeme'] ?? null, "{$path}.isMeme"),
            isPaidContent: Wire::nullableBool($data['isPaidContent'] ?? null, "{$path}.isPaidContent"),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            isVr: Wire::nullableBool($data['isVr'] ?? null, "{$path}.isVr"),
            language: Wire::nullableString($data['language'] ?? null, "{$path}.language"),
            locations: Wire::nullableList($data['locations'] ?? null, "{$path}.locations", static fn(mixed $item, string $path): TikTokLocationReference => Wire::object($item, $path, TikTokLocationReference::class)),
            media: Wire::list($data['media'] ?? [], "{$path}.media", static fn(mixed $item, string $path): TikTokMedia => Wire::object($item, $path, TikTokMedia::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokPostMetrics::class),
            musicContext: Wire::object($data['musicContext'] ?? [], "{$path}.musicContext", TikTokMusicContext::class),
            onScreenText: Wire::nullableList($data['onScreenText'] ?? null, "{$path}.onScreenText", static fn(mixed $item, string $path): array => Wire::map($item, $path)),
            paidCollectionId: Wire::nullableString($data['paidCollectionId'] ?? null, "{$path}.paidCollectionId"),
            playlist: Wire::nullableObject($data['playlist'] ?? null, "{$path}.playlist", TikTokPlaylistReference::class),
            region: Wire::nullableString($data['region'] ?? null, "{$path}.region"),
            searchContext: Wire::object($data['searchContext'] ?? [], "{$path}.searchContext", TikTokPostSearchContext::class),
            status: Wire::object($data['status'] ?? [], "{$path}.status", TikTokPostStatus::class),
            stickers: Wire::nullableList($data['stickers'] ?? null, "{$path}.stickers", static fn(mixed $item, string $path): TikTokInteractionSticker => Wire::object($item, $path, TikTokInteractionSticker::class)),
            template: Wire::nullableObject($data['template'] ?? null, "{$path}.template", TikTokPostTemplate::class),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
        );
    }
}
