<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokTextEntity implements Model
{
    public function __construct(
        public readonly ?int $end = null,
        public readonly ?TikTokHashtagReference $hashtag = null,
        public readonly ?int $start = null,
        public readonly ?string $tagId = null,
        public readonly ?string $type = null,
        public readonly ?int $typeCode = null,
        public readonly ?TikTokProfileReference $user = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            end: Wire::nullableInt($data['end'] ?? null, "{$path}.end"),
            hashtag: Wire::nullableObject($data['hashtag'] ?? null, "{$path}.hashtag", TikTokHashtagReference::class),
            start: Wire::nullableInt($data['start'] ?? null, "{$path}.start"),
            tagId: Wire::nullableString($data['tagId'] ?? null, "{$path}.tagId"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            typeCode: Wire::nullableInt($data['typeCode'] ?? null, "{$path}.typeCode"),
            user: Wire::nullableObject($data['user'] ?? null, "{$path}.user", TikTokProfileReference::class),
        );
    }
}
