<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPageContinuation implements Model
{
    public function __construct(
        public readonly ?int $maxTime = null,
        public readonly ?int $minTime = null,
        public readonly ?int $offset = null,
        public readonly ?string $pageToken = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            maxTime: Wire::nullableInt($data['maxTime'] ?? null, "{$path}.maxTime"),
            minTime: Wire::nullableInt($data['minTime'] ?? null, "{$path}.minTime"),
            offset: Wire::nullableInt($data['offset'] ?? null, "{$path}.offset"),
            pageToken: Wire::nullableString($data['pageToken'] ?? null, "{$path}.pageToken"),
        );
    }
}
