<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokImage implements Model
{
    public function __construct(
        public readonly ?string $hash = null,
        public readonly ?int $height = null,
        public readonly ?string $id = null,
        public readonly ?string $label = null,
        /**
         * @var list<TikTokImage>|null
         */
        public readonly ?array $renditions = null,
        public readonly ?string $role = null,
        public readonly ?int $size = null,
        public readonly ?string $url = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $urls = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hash: Wire::nullableString($data['hash'] ?? null, "{$path}.hash"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            renditions: Wire::nullableList($data['renditions'] ?? null, "{$path}.renditions", static fn(mixed $item, string $path): TikTokImage => Wire::object($item, $path, TikTokImage::class)),
            role: Wire::nullableString($data['role'] ?? null, "{$path}.role"),
            size: Wire::nullableInt($data['size'] ?? null, "{$path}.size"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            urls: Wire::nullableList($data['urls'] ?? null, "{$path}.urls", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
