<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokEffectOwner implements Model
{
    public function __construct(
        public readonly TikTokEffectOwnerVerification $verification,
        public readonly ?TikTokImage $avatar = null,
        public readonly ?string $displayName = null,
        public readonly ?string $id = null,
        public readonly ?bool $isTopEffectDesigner = null,
        public readonly ?string $secUid = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", TikTokImage::class),
            displayName: Wire::nullableString($data['displayName'] ?? null, "{$path}.displayName"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isTopEffectDesigner: Wire::nullableBool($data['isTopEffectDesigner'] ?? null, "{$path}.isTopEffectDesigner"),
            secUid: Wire::nullableString($data['secUid'] ?? null, "{$path}.secUid"),
            verification: Wire::object($data['verification'] ?? [], "{$path}.verification", TikTokEffectOwnerVerification::class),
        );
    }
}
