<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPageMetadataMetrics implements Model
{
    public function __construct(
        public readonly ?int $comments = null,
        public readonly ?int $followers = null,
        public readonly ?int $following = null,
        public readonly ?int $results = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            followers: Wire::nullableInt($data['followers'] ?? null, "{$path}.followers"),
            following: Wire::nullableInt($data['following'] ?? null, "{$path}.following"),
            results: Wire::nullableInt($data['results'] ?? null, "{$path}.results"),
        );
    }
}
