<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokCategory implements Model
{
    public function __construct(
        public readonly TikTokCategoryContext $categoryContext,
        public readonly TikTokHashtagClassification $classification,
        public readonly string $id,
        public readonly TikTokHashtagMetrics $metrics,
        public readonly TikTokHashtagSearchContext $searchContext,
        public readonly string $url,
        public readonly ?TikTokImage $avatar = null,
        public readonly ?TikTokImage $cover = null,
        public readonly ?string $description = null,
        public readonly ?bool $isCommerce = null,
        public readonly ?bool $isStrongMusic = null,
        /**
         * @var list<TikTokMusicReference>|null
         */
        public readonly ?array $music = null,
        public readonly ?string $name = null,
        /**
         * @var list<TikTokPostReference>|null
         */
        public readonly ?array $previewPosts = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            avatar: Wire::nullableObject($data['avatar'] ?? null, "{$path}.avatar", TikTokImage::class),
            categoryContext: Wire::object($data['categoryContext'] ?? [], "{$path}.categoryContext", TikTokCategoryContext::class),
            classification: Wire::object($data['classification'] ?? [], "{$path}.classification", TikTokHashtagClassification::class),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", TikTokImage::class),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isCommerce: Wire::nullableBool($data['isCommerce'] ?? null, "{$path}.isCommerce"),
            isStrongMusic: Wire::nullableBool($data['isStrongMusic'] ?? null, "{$path}.isStrongMusic"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokHashtagMetrics::class),
            music: Wire::nullableList($data['music'] ?? null, "{$path}.music", static fn(mixed $item, string $path): TikTokMusicReference => Wire::object($item, $path, TikTokMusicReference::class)),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            previewPosts: Wire::nullableList($data['previewPosts'] ?? null, "{$path}.previewPosts", static fn(mixed $item, string $path): TikTokPostReference => Wire::object($item, $path, TikTokPostReference::class)),
            searchContext: Wire::object($data['searchContext'] ?? [], "{$path}.searchContext", TikTokHashtagSearchContext::class),
            url: Wire::string($data['url'] ?? '', "{$path}.url"),
        );
    }
}
