<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokComment implements Model
{
    public function __construct(
        public readonly string $createdAt,
        public readonly TikTokExtracted $extracted,
        public readonly string $id,
        public readonly TikTokCommentMetrics $metrics,
        public readonly TikTokCommentPredictions $predictions,
        public readonly ?TikTokProfileReference $author = null,
        /**
         * @var list<TikTokTextEntity>|null
         */
        public readonly ?array $entities = null,
        public readonly ?bool $isLikedByCreator = null,
        public readonly ?bool $isPinned = null,
        /**
         * @var list<TikTokCommentLabel>|null
         */
        public readonly ?array $labels = null,
        public readonly ?string $language = null,
        /**
         * @var list<TikTokImage>|null
         */
        public readonly ?array $media = null,
        public readonly ?string $parentId = null,
        public readonly ?string $postId = null,
        /**
         * @var list<TikTokCommentReference>|null
         */
        public readonly ?array $previewReplies = null,
        public readonly ?TikTokProfileReference $replyTo = null,
        public readonly ?string $rootCommentId = null,
        public readonly ?TikTokCommentSticker $sticker = null,
        public readonly ?string $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", TikTokProfileReference::class),
            createdAt: Wire::string($data['createdAt'] ?? '', "{$path}.createdAt"),
            entities: Wire::nullableList($data['entities'] ?? null, "{$path}.entities", static fn(mixed $item, string $path): TikTokTextEntity => Wire::object($item, $path, TikTokTextEntity::class)),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", TikTokExtracted::class),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isLikedByCreator: Wire::nullableBool($data['isLikedByCreator'] ?? null, "{$path}.isLikedByCreator"),
            isPinned: Wire::nullableBool($data['isPinned'] ?? null, "{$path}.isPinned"),
            labels: Wire::nullableList($data['labels'] ?? null, "{$path}.labels", static fn(mixed $item, string $path): TikTokCommentLabel => Wire::object($item, $path, TikTokCommentLabel::class)),
            language: Wire::nullableString($data['language'] ?? null, "{$path}.language"),
            media: Wire::nullableList($data['media'] ?? null, "{$path}.media", static fn(mixed $item, string $path): TikTokImage => Wire::object($item, $path, TikTokImage::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokCommentMetrics::class),
            parentId: Wire::nullableString($data['parentId'] ?? null, "{$path}.parentId"),
            postId: Wire::nullableString($data['postId'] ?? null, "{$path}.postId"),
            predictions: Wire::object($data['predictions'] ?? [], "{$path}.predictions", TikTokCommentPredictions::class),
            previewReplies: Wire::nullableList($data['previewReplies'] ?? null, "{$path}.previewReplies", static fn(mixed $item, string $path): TikTokCommentReference => Wire::object($item, $path, TikTokCommentReference::class)),
            replyTo: Wire::nullableObject($data['replyTo'] ?? null, "{$path}.replyTo", TikTokProfileReference::class),
            rootCommentId: Wire::nullableString($data['rootCommentId'] ?? null, "{$path}.rootCommentId"),
            sticker: Wire::nullableObject($data['sticker'] ?? null, "{$path}.sticker", TikTokCommentSticker::class),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
        );
    }
}
