<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokLocationRating implements Model
{
    public function __construct(
        public readonly TikTokRatingSource $source,
        public readonly ?bool $hasRating = null,
        public readonly ?float $maxScore = null,
        public readonly ?float $score = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasRating: Wire::nullableBool($data['hasRating'] ?? null, "{$path}.hasRating"),
            maxScore: Wire::nullableFloat($data['maxScore'] ?? null, "{$path}.maxScore"),
            score: Wire::nullableFloat($data['score'] ?? null, "{$path}.score"),
            source: Wire::object($data['source'] ?? [], "{$path}.source", TikTokRatingSource::class),
        );
    }
}
