<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokCategoryContext implements Model
{
    public function __construct(
        public readonly ?string $label = null,
        public readonly ?int $typeCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            typeCode: Wire::nullableInt($data['typeCode'] ?? null, "{$path}.typeCode"),
        );
    }
}
