<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostAudio implements Model
{
    public function __construct(
        public readonly ?TikTokMusicReference $addedTrack = null,
        public readonly ?float $addedVolume = null,
        public readonly ?float $endTime = null,
        public readonly ?float $originalVolume = null,
        public readonly ?float $startTime = null,
        public readonly ?TikTokMusicReference $track = null,
        public readonly ?bool $usesFullSong = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            addedTrack: Wire::nullableObject($data['addedTrack'] ?? null, "{$path}.addedTrack", TikTokMusicReference::class),
            addedVolume: Wire::nullableFloat($data['addedVolume'] ?? null, "{$path}.addedVolume"),
            endTime: Wire::nullableFloat($data['endTime'] ?? null, "{$path}.endTime"),
            originalVolume: Wire::nullableFloat($data['originalVolume'] ?? null, "{$path}.originalVolume"),
            startTime: Wire::nullableFloat($data['startTime'] ?? null, "{$path}.startTime"),
            track: Wire::nullableObject($data['track'] ?? null, "{$path}.track", TikTokMusicReference::class),
            usesFullSong: Wire::nullableBool($data['usesFullSong'] ?? null, "{$path}.usesFullSong"),
        );
    }
}
