<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokEffectCreation implements Model
{
    public function __construct(
        public readonly ?bool $isEffectHouse = null,
        public readonly ?bool $isExternalProducer = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            isEffectHouse: Wire::nullableBool($data['isEffectHouse'] ?? null, "{$path}.isEffectHouse"),
            isExternalProducer: Wire::nullableBool($data['isExternalProducer'] ?? null, "{$path}.isExternalProducer"),
        );
    }
}
