<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostMetrics implements Model
{
    public function __construct(
        public readonly TikTokWhatsAppMetrics $whatsapp,
        public readonly ?int $comments = null,
        public readonly ?int $downloads = null,
        public readonly ?int $likes = null,
        public readonly ?int $reposts = null,
        public readonly ?int $saves = null,
        public readonly ?int $shares = null,
        public readonly ?int $views = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            downloads: Wire::nullableInt($data['downloads'] ?? null, "{$path}.downloads"),
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            reposts: Wire::nullableInt($data['reposts'] ?? null, "{$path}.reposts"),
            saves: Wire::nullableInt($data['saves'] ?? null, "{$path}.saves"),
            shares: Wire::nullableInt($data['shares'] ?? null, "{$path}.shares"),
            views: Wire::nullableInt($data['views'] ?? null, "{$path}.views"),
            whatsapp: Wire::object($data['whatsapp'] ?? [], "{$path}.whatsapp", TikTokWhatsAppMetrics::class),
        );
    }
}
