<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokRendition implements Model
{
    public function __construct(
        public readonly ?int $bitrate = null,
        public readonly ?int $codecCode = null,
        public readonly ?float $frameRate = null,
        public readonly ?string $hash = null,
        public readonly ?int $height = null,
        public readonly ?string $id = null,
        public readonly ?bool $isBytevc1 = null,
        public readonly ?string $label = null,
        public readonly ?int $qualityCode = null,
        public readonly ?string $qualityLabel = null,
        public readonly ?string $role = null,
        public readonly ?int $size = null,
        public readonly ?string $url = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $urls = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            bitrate: Wire::nullableInt($data['bitrate'] ?? null, "{$path}.bitrate"),
            codecCode: Wire::nullableInt($data['codecCode'] ?? null, "{$path}.codecCode"),
            frameRate: Wire::nullableFloat($data['frameRate'] ?? null, "{$path}.frameRate"),
            hash: Wire::nullableString($data['hash'] ?? null, "{$path}.hash"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isBytevc1: Wire::nullableBool($data['isBytevc1'] ?? null, "{$path}.isBytevc1"),
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            qualityCode: Wire::nullableInt($data['qualityCode'] ?? null, "{$path}.qualityCode"),
            qualityLabel: Wire::nullableString($data['qualityLabel'] ?? null, "{$path}.qualityLabel"),
            role: Wire::nullableString($data['role'] ?? null, "{$path}.role"),
            size: Wire::nullableInt($data['size'] ?? null, "{$path}.size"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            urls: Wire::nullableList($data['urls'] ?? null, "{$path}.urls", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
