<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokMusicClassification implements Model
{
    public function __construct(
        public readonly ?string $languageLabel = null,
        /**
         * @var list<int>|null
         */
        public readonly ?array $styleCodes = null,
        /**
         * @var list<int>|null
         */
        public readonly ?array $themeCodes = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $themes = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            languageLabel: Wire::nullableString($data['languageLabel'] ?? null, "{$path}.languageLabel"),
            styleCodes: Wire::nullableList($data['styleCodes'] ?? null, "{$path}.styleCodes", static fn(mixed $item, string $path): int => Wire::int($item, $path)),
            themeCodes: Wire::nullableList($data['themeCodes'] ?? null, "{$path}.themeCodes", static fn(mixed $item, string $path): int => Wire::int($item, $path)),
            themes: Wire::nullableList($data['themes'] ?? null, "{$path}.themes", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
