<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokLocation implements Model
{
    public function __construct(
        public readonly TikTokLocationAddress $address,
        public readonly TikTokLocationClassification $classification,
        public readonly TikTokLocationCommerce $commerce,
        public readonly TikTokCoordinates $coordinates,
        public readonly string $id,
        public readonly TikTokLocationMetrics $metrics,
        public readonly TikTokOpeningHours $openingHours,
        public readonly TikTokLocationRating $rating,
        public readonly ?string $category = null,
        public readonly ?string $externalUrl = null,
        public readonly ?string $name = null,
        public readonly ?TikTokLocationParent $parent = null,
        public readonly ?string $priceLevel = null,
        public readonly ?string $source = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            address: Wire::object($data['address'] ?? [], "{$path}.address", TikTokLocationAddress::class),
            category: Wire::nullableString($data['category'] ?? null, "{$path}.category"),
            classification: Wire::object($data['classification'] ?? [], "{$path}.classification", TikTokLocationClassification::class),
            commerce: Wire::object($data['commerce'] ?? [], "{$path}.commerce", TikTokLocationCommerce::class),
            coordinates: Wire::object($data['coordinates'] ?? [], "{$path}.coordinates", TikTokCoordinates::class),
            externalUrl: Wire::nullableString($data['externalUrl'] ?? null, "{$path}.externalUrl"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokLocationMetrics::class),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            openingHours: Wire::object($data['openingHours'] ?? [], "{$path}.openingHours", TikTokOpeningHours::class),
            parent: Wire::nullableObject($data['parent'] ?? null, "{$path}.parent", TikTokLocationParent::class),
            priceLevel: Wire::nullableString($data['priceLevel'] ?? null, "{$path}.priceLevel"),
            rating: Wire::object($data['rating'] ?? [], "{$path}.rating", TikTokLocationRating::class),
            source: Wire::nullableString($data['source'] ?? null, "{$path}.source"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
