<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokInteractionSticker implements Model
{
    public function __construct(
        public readonly ?TikTokHashtagReference $hashtag = null,
        public readonly ?int $index = null,
        public readonly ?bool $isTextHashtag = null,
        public readonly ?int $materialIndex = null,
        /**
         * @var list<TikTokStickerPosition>|null
         */
        public readonly ?array $positions = null,
        public readonly ?string $text = null,
        public readonly ?int $typeCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hashtag: Wire::nullableObject($data['hashtag'] ?? null, "{$path}.hashtag", TikTokHashtagReference::class),
            index: Wire::nullableInt($data['index'] ?? null, "{$path}.index"),
            isTextHashtag: Wire::nullableBool($data['isTextHashtag'] ?? null, "{$path}.isTextHashtag"),
            materialIndex: Wire::nullableInt($data['materialIndex'] ?? null, "{$path}.materialIndex"),
            positions: Wire::nullableList($data['positions'] ?? null, "{$path}.positions", static fn(mixed $item, string $path): TikTokStickerPosition => Wire::object($item, $path, TikTokStickerPosition::class)),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            typeCode: Wire::nullableInt($data['typeCode'] ?? null, "{$path}.typeCode"),
        );
    }
}
