<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokMedia implements Model
{
    public function __construct(
        /**
         * @var list<TikTokImage>|null
         */
        public readonly ?array $covers = null,
        public readonly ?float $duration = null,
        public readonly ?bool $hasWatermark = null,
        public readonly ?string $hash = null,
        public readonly ?int $height = null,
        public readonly ?string $id = null,
        /**
         * @var list<TikTokPreviewThumbnails>|null
         */
        public readonly ?array $previewThumbnails = null,
        public readonly ?string $qualityLabel = null,
        /**
         * @var list<TikTokRendition>|null
         */
        public readonly ?array $renditions = null,
        public readonly ?int $size = null,
        /**
         * @var list<TikTokSubtitle>|null
         */
        public readonly ?array $subtitles = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $urls = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            covers: Wire::nullableList($data['covers'] ?? null, "{$path}.covers", static fn(mixed $item, string $path): TikTokImage => Wire::object($item, $path, TikTokImage::class)),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            hasWatermark: Wire::nullableBool($data['hasWatermark'] ?? null, "{$path}.hasWatermark"),
            hash: Wire::nullableString($data['hash'] ?? null, "{$path}.hash"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            previewThumbnails: Wire::nullableList($data['previewThumbnails'] ?? null, "{$path}.previewThumbnails", static fn(mixed $item, string $path): TikTokPreviewThumbnails => Wire::object($item, $path, TikTokPreviewThumbnails::class)),
            qualityLabel: Wire::nullableString($data['qualityLabel'] ?? null, "{$path}.qualityLabel"),
            renditions: Wire::nullableList($data['renditions'] ?? null, "{$path}.renditions", static fn(mixed $item, string $path): TikTokRendition => Wire::object($item, $path, TikTokRendition::class)),
            size: Wire::nullableInt($data['size'] ?? null, "{$path}.size"),
            subtitles: Wire::nullableList($data['subtitles'] ?? null, "{$path}.subtitles", static fn(mixed $item, string $path): TikTokSubtitle => Wire::object($item, $path, TikTokSubtitle::class)),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            urls: Wire::nullableList($data['urls'] ?? null, "{$path}.urls", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
