<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokLocationMetrics implements Model
{
    public function __construct(
        public readonly ?int $favorites = null,
        public readonly ?int $reviews = null,
        public readonly ?int $videos = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            favorites: Wire::nullableInt($data['favorites'] ?? null, "{$path}.favorites"),
            reviews: Wire::nullableInt($data['reviews'] ?? null, "{$path}.reviews"),
            videos: Wire::nullableInt($data['videos'] ?? null, "{$path}.videos"),
        );
    }
}
