<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostStatus implements Model
{
    public function __construct(
        public readonly ?bool $isDeleted = null,
        public readonly ?bool $isProhibited = null,
        public readonly ?bool $isUnderReview = null,
        public readonly ?int $privacyCode = null,
        public readonly ?int $reviewedCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            isDeleted: Wire::nullableBool($data['isDeleted'] ?? null, "{$path}.isDeleted"),
            isProhibited: Wire::nullableBool($data['isProhibited'] ?? null, "{$path}.isProhibited"),
            isUnderReview: Wire::nullableBool($data['isUnderReview'] ?? null, "{$path}.isUnderReview"),
            privacyCode: Wire::nullableInt($data['privacyCode'] ?? null, "{$path}.privacyCode"),
            reviewedCode: Wire::nullableInt($data['reviewedCode'] ?? null, "{$path}.reviewedCode"),
        );
    }
}
