<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokBeatData implements Model
{
    public function __construct(
        public readonly ?string $hash = null,
        public readonly ?string $id = null,
        /**
         * @var list<TikTokBeatResource>|null
         */
        public readonly ?array $resources = null,
        public readonly ?int $size = null,
        public readonly ?string $url = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $urls = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hash: Wire::nullableString($data['hash'] ?? null, "{$path}.hash"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            resources: Wire::nullableList($data['resources'] ?? null, "{$path}.resources", static fn(mixed $item, string $path): TikTokBeatResource => Wire::object($item, $path, TikTokBeatResource::class)),
            size: Wire::nullableInt($data['size'] ?? null, "{$path}.size"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            urls: Wire::nullableList($data['urls'] ?? null, "{$path}.urls", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
