<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileReferenceStories implements Model
{
    public function __construct(
        public readonly TikTokProfileReferenceStoriesMetrics $metrics,
        public readonly ?string $changedAt = null,
        /**
         * @var list<TikTokStoryReference>|null
         */
        public readonly ?array $items = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            changedAt: Wire::nullableString($data['changedAt'] ?? null, "{$path}.changedAt"),
            items: Wire::nullableList($data['items'] ?? null, "{$path}.items", static fn(mixed $item, string $path): TikTokStoryReference => Wire::object($item, $path, TikTokStoryReference::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokProfileReferenceStoriesMetrics::class),
        );
    }
}
