<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProductSKU implements Model
{
    public function __construct(
        public readonly ?string $externalId = null,
        public readonly ?string $externalProductId = null,
        public readonly ?string $id = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            externalId: Wire::nullableString($data['externalId'] ?? null, "{$path}.externalId"),
            externalProductId: Wire::nullableString($data['externalProductId'] ?? null, "{$path}.externalProductId"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
        );
    }
}
