<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostSearchContext implements Model
{
    public function __construct(
        public readonly ?string $description = null,
        /**
         * @var list<TikTokSearchHighlight>|null
         */
        public readonly ?array $highlights = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            highlights: Wire::nullableList($data['highlights'] ?? null, "{$path}.highlights", static fn(mixed $item, string $path): TikTokSearchHighlight => Wire::object($item, $path, TikTokSearchHighlight::class)),
        );
    }
}
