<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokEffectReference implements Model
{
    public function __construct(
        public readonly TikTokEffectClassification $classification,
        public readonly TikTokEffectCreation $creation,
        public readonly TikTokEffectMetrics $metrics,
        /**
         * @var list<array<string, mixed>>|null
         */
        public readonly ?array $attributions = null,
        /**
         * @var list<array<string, mixed>>|null
         */
        public readonly ?array $children = null,
        public readonly ?string $description = null,
        public readonly ?string $effectId = null,
        public readonly ?TikTokImage $icon = null,
        public readonly ?string $id = null,
        public readonly ?bool $isTopEffect = null,
        /**
         * @var list<array<string, mixed>>|null
         */
        public readonly ?array $linkedAnchors = null,
        public readonly ?string $name = null,
        public readonly ?TikTokEffectOwner $owner = null,
        public readonly ?string $publishedAt = null,
        public readonly ?string $resourceId = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $tags = null,
        /**
         * @var list<TikTokEffectTrigger>|null
         */
        public readonly ?array $triggers = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            attributions: Wire::nullableList($data['attributions'] ?? null, "{$path}.attributions", static fn(mixed $item, string $path): array => Wire::map($item, $path)),
            children: Wire::nullableList($data['children'] ?? null, "{$path}.children", static fn(mixed $item, string $path): array => Wire::map($item, $path)),
            classification: Wire::object($data['classification'] ?? [], "{$path}.classification", TikTokEffectClassification::class),
            creation: Wire::object($data['creation'] ?? [], "{$path}.creation", TikTokEffectCreation::class),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            effectId: Wire::nullableString($data['effectId'] ?? null, "{$path}.effectId"),
            icon: Wire::nullableObject($data['icon'] ?? null, "{$path}.icon", TikTokImage::class),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isTopEffect: Wire::nullableBool($data['isTopEffect'] ?? null, "{$path}.isTopEffect"),
            linkedAnchors: Wire::nullableList($data['linkedAnchors'] ?? null, "{$path}.linkedAnchors", static fn(mixed $item, string $path): array => Wire::map($item, $path)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokEffectMetrics::class),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            owner: Wire::nullableObject($data['owner'] ?? null, "{$path}.owner", TikTokEffectOwner::class),
            publishedAt: Wire::nullableString($data['publishedAt'] ?? null, "{$path}.publishedAt"),
            resourceId: Wire::nullableString($data['resourceId'] ?? null, "{$path}.resourceId"),
            tags: Wire::nullableList($data['tags'] ?? null, "{$path}.tags", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            triggers: Wire::nullableList($data['triggers'] ?? null, "{$path}.triggers", static fn(mixed $item, string $path): TikTokEffectTrigger => Wire::object($item, $path, TikTokEffectTrigger::class)),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
