<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokEffectMetrics implements Model
{
    public function __construct(
        public readonly ?int $uses = null,
        public readonly ?int $views = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            uses: Wire::nullableInt($data['uses'] ?? null, "{$path}.uses"),
            views: Wire::nullableInt($data['views'] ?? null, "{$path}.views"),
        );
    }
}
