<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokMusicSource implements Model
{
    public function __construct(
        public readonly ?string $audioAssetId = null,
        public readonly ?string $sourcePostId = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            audioAssetId: Wire::nullableString($data['audioAssetId'] ?? null, "{$path}.audioAssetId"),
            sourcePostId: Wire::nullableString($data['sourcePostId'] ?? null, "{$path}.sourcePostId"),
        );
    }
}
