<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileReferencePredictions implements Model
{
    public function __construct(
        public readonly ?string $ageGroup = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            ageGroup: Wire::nullableString($data['ageGroup'] ?? null, "{$path}.ageGroup"),
        );
    }
}
