<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPageMetadata implements Model
{
    public function __construct(
        public readonly TikTokPageMetadataMetrics $metrics,
        public readonly ?TikTokChartMetadata $chart = null,
        public readonly ?TikTokPageContinuation $continuation = null,
        public readonly ?bool $hasFilteredComments = null,
        public readonly ?bool $hasMore = null,
        public readonly ?string $query = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            chart: Wire::nullableObject($data['chart'] ?? null, "{$path}.chart", TikTokChartMetadata::class),
            continuation: Wire::nullableObject($data['continuation'] ?? null, "{$path}.continuation", TikTokPageContinuation::class),
            hasFilteredComments: Wire::nullableBool($data['hasFilteredComments'] ?? null, "{$path}.hasFilteredComments"),
            hasMore: Wire::nullableBool($data['hasMore'] ?? null, "{$path}.hasMore"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokPageMetadataMetrics::class),
            query: Wire::nullableString($data['query'] ?? null, "{$path}.query"),
        );
    }
}
