<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostTemplate implements Model
{
    public function __construct(
        public readonly TikTokTemplateMetrics $metrics,
        public readonly ?string $authorName = null,
        public readonly ?string $description = null,
        public readonly ?float $duration = null,
        public readonly ?string $id = null,
        public readonly ?string $musicId = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            authorName: Wire::nullableString($data['authorName'] ?? null, "{$path}.authorName"),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokTemplateMetrics::class),
            musicId: Wire::nullableString($data['musicId'] ?? null, "{$path}.musicId"),
        );
    }
}
