<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostCommerce implements Model
{
    public function __construct(
        public readonly TikTokCommerceMetrics $metrics,
        public readonly ?int $brandedContentType = null,
        public readonly ?string $disclosureLabel = null,
        public readonly ?bool $isDiversionAd = null,
        public readonly ?bool $isEcommerce = null,
        /**
         * @var list<TikTokProduct>|null
         */
        public readonly ?array $products = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $sellerIds = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            brandedContentType: Wire::nullableInt($data['brandedContentType'] ?? null, "{$path}.brandedContentType"),
            disclosureLabel: Wire::nullableString($data['disclosureLabel'] ?? null, "{$path}.disclosureLabel"),
            isDiversionAd: Wire::nullableBool($data['isDiversionAd'] ?? null, "{$path}.isDiversionAd"),
            isEcommerce: Wire::nullableBool($data['isEcommerce'] ?? null, "{$path}.isEcommerce"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokCommerceMetrics::class),
            products: Wire::nullableList($data['products'] ?? null, "{$path}.products", static fn(mixed $item, string $path): TikTokProduct => Wire::object($item, $path, TikTokProduct::class)),
            sellerIds: Wire::nullableList($data['sellerIds'] ?? null, "{$path}.sellerIds", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
