<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokLocationAddress implements Model
{
    public function __construct(
        public readonly ?string $city = null,
        public readonly ?string $cityCode = null,
        public readonly ?string $countryCode = null,
        public readonly ?TikTokDistrict $district = null,
        public readonly ?string $fallback = null,
        public readonly ?string $formatted = null,
        public readonly ?string $regionCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            city: Wire::nullableString($data['city'] ?? null, "{$path}.city"),
            cityCode: Wire::nullableString($data['cityCode'] ?? null, "{$path}.cityCode"),
            countryCode: Wire::nullableString($data['countryCode'] ?? null, "{$path}.countryCode"),
            district: Wire::nullableObject($data['district'] ?? null, "{$path}.district", TikTokDistrict::class),
            fallback: Wire::nullableString($data['fallback'] ?? null, "{$path}.fallback"),
            formatted: Wire::nullableString($data['formatted'] ?? null, "{$path}.formatted"),
            regionCode: Wire::nullableString($data['regionCode'] ?? null, "{$path}.regionCode"),
        );
    }
}
