<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokMatchedTrack implements Model
{
    public function __construct(
        public readonly TikTokMusicPreview $chorus,
        public readonly TikTokMusicRelease $release,
        public readonly ?string $artistName = null,
        /**
         * @var list<TikTokProfileReference>|null
         */
        public readonly ?array $artists = null,
        public readonly ?TikTokImage $cover = null,
        public readonly ?float $duration = null,
        public readonly ?string $id = null,
        public readonly ?string $mixedArtistName = null,
        public readonly ?string $mixedTitle = null,
        public readonly ?string $title = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            artistName: Wire::nullableString($data['artistName'] ?? null, "{$path}.artistName"),
            artists: Wire::nullableList($data['artists'] ?? null, "{$path}.artists", static fn(mixed $item, string $path): TikTokProfileReference => Wire::object($item, $path, TikTokProfileReference::class)),
            chorus: Wire::object($data['chorus'] ?? [], "{$path}.chorus", TikTokMusicPreview::class),
            cover: Wire::nullableObject($data['cover'] ?? null, "{$path}.cover", TikTokImage::class),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            mixedArtistName: Wire::nullableString($data['mixedArtistName'] ?? null, "{$path}.mixedArtistName"),
            mixedTitle: Wire::nullableString($data['mixedTitle'] ?? null, "{$path}.mixedTitle"),
            release: Wire::object($data['release'] ?? [], "{$path}.release", TikTokMusicRelease::class),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
