<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileMusic implements Model
{
    public function __construct(
        public readonly TikTokProfileMusicMetrics $metrics,
        /**
         * @var list<string>|null
         */
        public readonly ?array $newReleaseIds = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokProfileMusicMetrics::class),
            newReleaseIds: Wire::nullableList($data['newReleaseIds'] ?? null, "{$path}.newReleaseIds", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
        );
    }
}
