<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokPostCaption implements Model
{
    public function __construct(
        /**
         * @var list<TikTokTextEntity>|null
         */
        public readonly ?array $entities = null,
        public readonly ?string $markup = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            entities: Wire::nullableList($data['entities'] ?? null, "{$path}.entities", static fn(mixed $item, string $path): TikTokTextEntity => Wire::object($item, $path, TikTokTextEntity::class)),
            markup: Wire::nullableString($data['markup'] ?? null, "{$path}.markup"),
        );
    }
}
