<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokProfileVerification implements Model
{
    public function __construct(
        public readonly ?int $badgeType = null,
        public readonly ?string $customLabel = null,
        public readonly ?string $label = null,
        public readonly ?int $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            badgeType: Wire::nullableInt($data['badgeType'] ?? null, "{$path}.badgeType"),
            customLabel: Wire::nullableString($data['customLabel'] ?? null, "{$path}.customLabel"),
            label: Wire::nullableString($data['label'] ?? null, "{$path}.label"),
            type: Wire::nullableInt($data['type'] ?? null, "{$path}.type"),
        );
    }
}
