<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokMusic implements Model
{
    public function __construct(
        public readonly TikTokMusicChartContext $chartContext,
        public readonly TikTokMusicClassification $classification,
        public readonly TikTokMusicDurations $durations,
        public readonly TikTokMusicGrouping $grouping,
        public readonly string $id,
        public readonly TikTokMusicMetrics $metrics,
        public readonly TikTokMusicPreview $preview,
        public readonly TikTokMusicRelease $release,
        public readonly TikTokMusicSearchContext $searchContext,
        public readonly TikTokMusicSource $source,
        public readonly ?string $album = null,
        public readonly ?string $appleMusicSongId = null,
        public readonly ?string $artistName = null,
        /**
         * @var list<TikTokProfileReference>|null
         */
        public readonly ?array $artists = null,
        public readonly ?TikTokAudio $audio = null,
        public readonly ?TikTokBeatData $beatData = null,
        /**
         * @var list<TikTokImage>|null
         */
        public readonly ?array $covers = null,
        public readonly ?string $createdAt = null,
        public readonly ?float $duration = null,
        /**
         * @var list<array<string, mixed>>|null
         */
        public readonly ?array $externalSongs = null,
        public readonly ?bool $hasBehindTheSong = null,
        public readonly ?bool $hasHumanVoice = null,
        public readonly ?bool $hasMatchedMetadata = null,
        public readonly ?bool $isAuthorArtist = null,
        public readonly ?bool $isAuthorDeleted = null,
        public readonly ?bool $isOriginal = null,
        public readonly ?bool $isOriginalSound = null,
        public readonly ?bool $isPgc = null,
        public readonly ?bool $isPlayMusic = null,
        /**
         * @var list<TikTokLyricAsset>|null
         */
        public readonly ?array $lyricAssets = null,
        public readonly ?TikTokMusicReference $matchedCatalogTrack = null,
        public readonly ?TikTokMatchedTrack $matchedSong = null,
        public readonly ?TikTokMatchedTrack $matchedSound = null,
        public readonly ?string $mid = null,
        public readonly ?TikTokProfileReference $owner = null,
        public readonly ?int $recommendationStatusCode = null,
        /**
         * @var list<TikTokMusicReference>|null
         */
        public readonly ?array $similarTracks = null,
        /**
         * @var list<TikTokStreamingLink>|null
         */
        public readonly ?array $streamingLinks = null,
        public readonly ?string $title = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            album: Wire::nullableString($data['album'] ?? null, "{$path}.album"),
            appleMusicSongId: Wire::nullableString($data['appleMusicSongId'] ?? null, "{$path}.appleMusicSongId"),
            artistName: Wire::nullableString($data['artistName'] ?? null, "{$path}.artistName"),
            artists: Wire::nullableList($data['artists'] ?? null, "{$path}.artists", static fn(mixed $item, string $path): TikTokProfileReference => Wire::object($item, $path, TikTokProfileReference::class)),
            audio: Wire::nullableObject($data['audio'] ?? null, "{$path}.audio", TikTokAudio::class),
            beatData: Wire::nullableObject($data['beatData'] ?? null, "{$path}.beatData", TikTokBeatData::class),
            chartContext: Wire::object($data['chartContext'] ?? [], "{$path}.chartContext", TikTokMusicChartContext::class),
            classification: Wire::object($data['classification'] ?? [], "{$path}.classification", TikTokMusicClassification::class),
            covers: Wire::nullableList($data['covers'] ?? null, "{$path}.covers", static fn(mixed $item, string $path): TikTokImage => Wire::object($item, $path, TikTokImage::class)),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            duration: Wire::nullableFloat($data['duration'] ?? null, "{$path}.duration"),
            durations: Wire::object($data['durations'] ?? [], "{$path}.durations", TikTokMusicDurations::class),
            externalSongs: Wire::nullableList($data['externalSongs'] ?? null, "{$path}.externalSongs", static fn(mixed $item, string $path): array => Wire::map($item, $path)),
            grouping: Wire::object($data['grouping'] ?? [], "{$path}.grouping", TikTokMusicGrouping::class),
            hasBehindTheSong: Wire::nullableBool($data['hasBehindTheSong'] ?? null, "{$path}.hasBehindTheSong"),
            hasHumanVoice: Wire::nullableBool($data['hasHumanVoice'] ?? null, "{$path}.hasHumanVoice"),
            hasMatchedMetadata: Wire::nullableBool($data['hasMatchedMetadata'] ?? null, "{$path}.hasMatchedMetadata"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            isAuthorArtist: Wire::nullableBool($data['isAuthorArtist'] ?? null, "{$path}.isAuthorArtist"),
            isAuthorDeleted: Wire::nullableBool($data['isAuthorDeleted'] ?? null, "{$path}.isAuthorDeleted"),
            isOriginal: Wire::nullableBool($data['isOriginal'] ?? null, "{$path}.isOriginal"),
            isOriginalSound: Wire::nullableBool($data['isOriginalSound'] ?? null, "{$path}.isOriginalSound"),
            isPgc: Wire::nullableBool($data['isPgc'] ?? null, "{$path}.isPgc"),
            isPlayMusic: Wire::nullableBool($data['isPlayMusic'] ?? null, "{$path}.isPlayMusic"),
            lyricAssets: Wire::nullableList($data['lyricAssets'] ?? null, "{$path}.lyricAssets", static fn(mixed $item, string $path): TikTokLyricAsset => Wire::object($item, $path, TikTokLyricAsset::class)),
            matchedCatalogTrack: Wire::nullableObject($data['matchedCatalogTrack'] ?? null, "{$path}.matchedCatalogTrack", TikTokMusicReference::class),
            matchedSong: Wire::nullableObject($data['matchedSong'] ?? null, "{$path}.matchedSong", TikTokMatchedTrack::class),
            matchedSound: Wire::nullableObject($data['matchedSound'] ?? null, "{$path}.matchedSound", TikTokMatchedTrack::class),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TikTokMusicMetrics::class),
            mid: Wire::nullableString($data['mid'] ?? null, "{$path}.mid"),
            owner: Wire::nullableObject($data['owner'] ?? null, "{$path}.owner", TikTokProfileReference::class),
            preview: Wire::object($data['preview'] ?? [], "{$path}.preview", TikTokMusicPreview::class),
            recommendationStatusCode: Wire::nullableInt($data['recommendationStatusCode'] ?? null, "{$path}.recommendationStatusCode"),
            release: Wire::object($data['release'] ?? [], "{$path}.release", TikTokMusicRelease::class),
            searchContext: Wire::object($data['searchContext'] ?? [], "{$path}.searchContext", TikTokMusicSearchContext::class),
            similarTracks: Wire::nullableList($data['similarTracks'] ?? null, "{$path}.similarTracks", static fn(mixed $item, string $path): TikTokMusicReference => Wire::object($item, $path, TikTokMusicReference::class)),
            source: Wire::object($data['source'] ?? [], "{$path}.source", TikTokMusicSource::class),
            streamingLinks: Wire::nullableList($data['streamingLinks'] ?? null, "{$path}.streamingLinks", static fn(mixed $item, string $path): TikTokStreamingLink => Wire::object($item, $path, TikTokStreamingLink::class)),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
