<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TikTokLocationClassification implements Model
{
    public function __construct(
        public readonly TikTokServiceCategory $serviceCategory,
        public readonly ?string $backendType = null,
        public readonly ?string $className = null,
        public readonly ?string $code = null,
        public readonly ?string $detailType = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $hierarchy = null,
        public readonly ?string $levelCode = null,
        public readonly ?int $sourceCode = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            backendType: Wire::nullableString($data['backendType'] ?? null, "{$path}.backendType"),
            className: Wire::nullableString($data['className'] ?? null, "{$path}.className"),
            code: Wire::nullableString($data['code'] ?? null, "{$path}.code"),
            detailType: Wire::nullableString($data['detailType'] ?? null, "{$path}.detailType"),
            hierarchy: Wire::nullableList($data['hierarchy'] ?? null, "{$path}.hierarchy", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            levelCode: Wire::nullableString($data['levelCode'] ?? null, "{$path}.levelCode"),
            serviceCategory: Wire::object($data['serviceCategory'] ?? [], "{$path}.serviceCategory", TikTokServiceCategory::class),
            sourceCode: Wire::nullableInt($data['sourceCode'] ?? null, "{$path}.sourceCode"),
        );
    }
}
