<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterCard implements Model
{
    public function __construct(
        /**
         * @var list<TwitterCardApp>|null
         */
        public readonly ?array $apps = null,
        public readonly ?TwitterBroadcast $broadcast = null,
        /**
         * @var list<TwitterCardComponent>|null
         */
        public readonly ?array $components = null,
        public readonly ?string $description = null,
        /**
         * @var list<TwitterCardDestination>|null
         */
        public readonly ?array $destinations = null,
        public readonly ?string $displayUrl = null,
        public readonly ?string $domain = null,
        public readonly ?TwitterEvent $event = null,
        /**
         * @var list<TwitterImageAltText>|null
         */
        public readonly ?array $imageAltText = null,
        /**
         * @var list<TwitterImage>|null
         */
        public readonly ?array $images = null,
        public readonly ?string $layoutType = null,
        /**
         * @var list<TwitterMedia>|null
         */
        public readonly ?array $media = null,
        public readonly ?string $mediaType = null,
        public readonly ?TwitterPoll $poll = null,
        /**
         * @var list<TwitterProfileReference>|null
         */
        public readonly ?array $profiles = null,
        public readonly ?string $publisherId = null,
        public readonly ?string $title = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            apps: Wire::nullableList($data['apps'] ?? null, "{$path}.apps", static fn(mixed $item, string $path): TwitterCardApp => Wire::object($item, $path, TwitterCardApp::class)),
            broadcast: Wire::nullableObject($data['broadcast'] ?? null, "{$path}.broadcast", TwitterBroadcast::class),
            components: Wire::nullableList($data['components'] ?? null, "{$path}.components", static fn(mixed $item, string $path): TwitterCardComponent => Wire::object($item, $path, TwitterCardComponent::class)),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            destinations: Wire::nullableList($data['destinations'] ?? null, "{$path}.destinations", static fn(mixed $item, string $path): TwitterCardDestination => Wire::object($item, $path, TwitterCardDestination::class)),
            displayUrl: Wire::nullableString($data['displayUrl'] ?? null, "{$path}.displayUrl"),
            domain: Wire::nullableString($data['domain'] ?? null, "{$path}.domain"),
            event: Wire::nullableObject($data['event'] ?? null, "{$path}.event", TwitterEvent::class),
            imageAltText: Wire::nullableList($data['imageAltText'] ?? null, "{$path}.imageAltText", static fn(mixed $item, string $path): TwitterImageAltText => Wire::object($item, $path, TwitterImageAltText::class)),
            images: Wire::nullableList($data['images'] ?? null, "{$path}.images", static fn(mixed $item, string $path): TwitterImage => Wire::object($item, $path, TwitterImage::class)),
            layoutType: Wire::nullableString($data['layoutType'] ?? null, "{$path}.layoutType"),
            media: Wire::nullableList($data['media'] ?? null, "{$path}.media", static fn(mixed $item, string $path): TwitterMedia => Wire::object($item, $path, TwitterMedia::class)),
            mediaType: Wire::nullableString($data['mediaType'] ?? null, "{$path}.mediaType"),
            poll: Wire::nullableObject($data['poll'] ?? null, "{$path}.poll", TwitterPoll::class),
            profiles: Wire::nullableList($data['profiles'] ?? null, "{$path}.profiles", static fn(mixed $item, string $path): TwitterProfileReference => Wire::object($item, $path, TwitterProfileReference::class)),
            publisherId: Wire::nullableString($data['publisherId'] ?? null, "{$path}.publisherId"),
            title: Wire::nullableString($data['title'] ?? null, "{$path}.title"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
