<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterLabel implements Model
{
    public function __construct(
        public readonly ?TwitterRichText $description = null,
        public readonly ?TwitterImage $icon = null,
        public readonly ?string $text = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            description: Wire::nullableObject($data['description'] ?? null, "{$path}.description", TwitterRichText::class),
            icon: Wire::nullableObject($data['icon'] ?? null, "{$path}.icon", TwitterImage::class),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
