<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterLongText implements Model
{
    public function __construct(
        /**
         * @var list<TwitterFormatting>|null
         */
        public readonly ?array $formatting = null,
        public readonly ?string $id = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $inlineMedia = null,
        public readonly ?bool $isExpandable = null,
        /**
         * @var list<mixed>|null
         */
        public readonly ?array $timestamps = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            formatting: Wire::nullableList($data['formatting'] ?? null, "{$path}.formatting", static fn(mixed $item, string $path): TwitterFormatting => Wire::object($item, $path, TwitterFormatting::class)),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            inlineMedia: Wire::nullableList($data['inlineMedia'] ?? null, "{$path}.inlineMedia", static fn(mixed $item): mixed => $item),
            isExpandable: Wire::nullableBool($data['isExpandable'] ?? null, "{$path}.isExpandable"),
            timestamps: Wire::nullableList($data['timestamps'] ?? null, "{$path}.timestamps", static fn(mixed $item): mixed => $item),
        );
    }
}
