<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterMediaVariant implements Model
{
    public function __construct(
        public readonly ?int $bitrate = null,
        public readonly ?string $contentType = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            bitrate: Wire::nullableInt($data['bitrate'] ?? null, "{$path}.bitrate"),
            contentType: Wire::nullableString($data['contentType'] ?? null, "{$path}.contentType"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
