<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterRGB implements Model
{
    public function __construct(
        public readonly int $blue,
        public readonly int $green,
        public readonly int $red,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            blue: Wire::int($data['blue'] ?? 0, "{$path}.blue"),
            green: Wire::int($data['green'] ?? 0, "{$path}.green"),
            red: Wire::int($data['red'] ?? 0, "{$path}.red"),
        );
    }
}
