<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterRectangle implements Model
{
    public function __construct(
        public readonly ?int $height = null,
        public readonly ?int $width = null,
        public readonly ?int $x = null,
        public readonly ?int $y = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
            x: Wire::nullableInt($data['x'] ?? null, "{$path}.x"),
            y: Wire::nullableInt($data['y'] ?? null, "{$path}.y"),
        );
    }
}
