<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterCardComponent implements Model
{
    public function __construct(
        public readonly ?string $appGroupId = null,
        /**
         * @var list<TwitterCardButton>|null
         */
        public readonly ?array $buttons = null,
        public readonly ?string $destinationId = null,
        public readonly ?string $id = null,
        /**
         * @var list<TwitterCardMediaRef>|null
         */
        public readonly ?array $media = null,
        public readonly ?string $mediaKey = null,
        public readonly ?TwitterCardText $subtitle = null,
        public readonly ?TwitterCardText $title = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            appGroupId: Wire::nullableString($data['appGroupId'] ?? null, "{$path}.appGroupId"),
            buttons: Wire::nullableList($data['buttons'] ?? null, "{$path}.buttons", static fn(mixed $item, string $path): TwitterCardButton => Wire::object($item, $path, TwitterCardButton::class)),
            destinationId: Wire::nullableString($data['destinationId'] ?? null, "{$path}.destinationId"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            media: Wire::nullableList($data['media'] ?? null, "{$path}.media", static fn(mixed $item, string $path): TwitterCardMediaRef => Wire::object($item, $path, TwitterCardMediaRef::class)),
            mediaKey: Wire::nullableString($data['mediaKey'] ?? null, "{$path}.mediaKey"),
            subtitle: Wire::nullableObject($data['subtitle'] ?? null, "{$path}.subtitle", TwitterCardText::class),
            title: Wire::nullableObject($data['title'] ?? null, "{$path}.title", TwitterCardText::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
