<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterMediaFeature implements Model
{
    public function __construct(
        /**
         * @var list<TwitterRectangle>|null
         */
        public readonly ?array $faceRegions = null,
        public readonly ?string $size = null,
        /**
         * @var list<TwitterProfileReference>|null
         */
        public readonly ?array $taggedProfiles = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            faceRegions: Wire::nullableList($data['faceRegions'] ?? null, "{$path}.faceRegions", static fn(mixed $item, string $path): TwitterRectangle => Wire::object($item, $path, TwitterRectangle::class)),
            size: Wire::nullableString($data['size'] ?? null, "{$path}.size"),
            taggedProfiles: Wire::nullableList($data['taggedProfiles'] ?? null, "{$path}.taggedProfiles", static fn(mixed $item, string $path): TwitterProfileReference => Wire::object($item, $path, TwitterProfileReference::class)),
        );
    }
}
