<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterCardDestination implements Model
{
    public function __construct(
        public readonly ?string $appGroupId = null,
        public readonly ?string $displayUrl = null,
        public readonly ?string $id = null,
        public readonly ?string $mediaKey = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            appGroupId: Wire::nullableString($data['appGroupId'] ?? null, "{$path}.appGroupId"),
            displayUrl: Wire::nullableString($data['displayUrl'] ?? null, "{$path}.displayUrl"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            mediaKey: Wire::nullableString($data['mediaKey'] ?? null, "{$path}.mediaKey"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
