<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterCardButton implements Model
{
    public function __construct(
        public readonly ?string $action = null,
        public readonly ?string $destinationId = null,
        public readonly ?string $style = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            action: Wire::nullableString($data['action'] ?? null, "{$path}.action"),
            destinationId: Wire::nullableString($data['destinationId'] ?? null, "{$path}.destinationId"),
            style: Wire::nullableString($data['style'] ?? null, "{$path}.style"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
