<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterConversationContext implements Model
{
    public function __construct(
        /**
         * @var list<TwitterPostReference>|null
         */
        public readonly ?array $ancestors = null,
        /**
         * @var list<TwitterPostReference>|null
         */
        public readonly ?array $otherPosts = null,
        public readonly ?TwitterPostReference $requestedPost = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            ancestors: Wire::nullableList($data['ancestors'] ?? null, "{$path}.ancestors", static fn(mixed $item, string $path): TwitterPostReference => Wire::object($item, $path, TwitterPostReference::class)),
            otherPosts: Wire::nullableList($data['otherPosts'] ?? null, "{$path}.otherPosts", static fn(mixed $item, string $path): TwitterPostReference => Wire::object($item, $path, TwitterPostReference::class)),
            requestedPost: Wire::nullableObject($data['requestedPost'] ?? null, "{$path}.requestedPost", TwitterPostReference::class),
        );
    }
}
