<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterPlace implements Model
{
    public function __construct(
        public readonly ?string $country = null,
        public readonly ?string $countryCode = null,
        public readonly ?string $fullName = null,
        public readonly ?string $id = null,
        public readonly ?string $name = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            country: Wire::nullableString($data['country'] ?? null, "{$path}.country"),
            countryCode: Wire::nullableString($data['countryCode'] ?? null, "{$path}.countryCode"),
            fullName: Wire::nullableString($data['fullName'] ?? null, "{$path}.fullName"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
