<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterRange implements Model
{
    public function __construct(
        public readonly int $end,
        public readonly int $start,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            end: Wire::int($data['end'] ?? 0, "{$path}.end"),
            start: Wire::int($data['start'] ?? 0, "{$path}.start"),
        );
    }
}
