<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterTimelinePlacement implements Model
{
    public function __construct(
        public readonly ?string $conversationSection = null,
        public readonly ?string $displayType = null,
        public readonly ?string $moduleDisplayType = null,
        public readonly ?int $position = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            conversationSection: Wire::nullableString($data['conversationSection'] ?? null, "{$path}.conversationSection"),
            displayType: Wire::nullableString($data['displayType'] ?? null, "{$path}.displayType"),
            moduleDisplayType: Wire::nullableString($data['moduleDisplayType'] ?? null, "{$path}.moduleDisplayType"),
            position: Wire::nullableInt($data['position'] ?? null, "{$path}.position"),
        );
    }
}
