<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterEdit implements Model
{
    public function __construct(
        public readonly ?string $editableUntil = null,
        /**
         * @var list<string>|null
         */
        public readonly ?array $historyIds = null,
        public readonly ?string $initialPostId = null,
        public readonly ?int $remaining = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            editableUntil: Wire::nullableString($data['editableUntil'] ?? null, "{$path}.editableUntil"),
            historyIds: Wire::nullableList($data['historyIds'] ?? null, "{$path}.historyIds", static fn(mixed $item, string $path): string => Wire::string($item, $path)),
            initialPostId: Wire::nullableString($data['initialPostId'] ?? null, "{$path}.initialPostId"),
            remaining: Wire::nullableInt($data['remaining'] ?? null, "{$path}.remaining"),
        );
    }
}
