<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterNotePresentation implements Model
{
    public function __construct(
        public readonly ?string $iconType = null,
        public readonly ?string $style = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            iconType: Wire::nullableString($data['iconType'] ?? null, "{$path}.iconType"),
            style: Wire::nullableString($data['style'] ?? null, "{$path}.style"),
        );
    }
}
