<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterProfileLocation implements Model
{
    public function __construct(
        public readonly ?TwitterPlace $place = null,
        public readonly ?string $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            place: Wire::nullableObject($data['place'] ?? null, "{$path}.place", TwitterPlace::class),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
        );
    }
}
