<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterList implements Model
{
    public function __construct(
        public readonly string $id,
        public readonly TwitterListMetrics $metrics,
        public readonly ?TwitterImage $banner = null,
        public readonly ?string $description = null,
        public readonly ?string $name = null,
        public readonly ?TwitterProfileReference $owner = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            banner: Wire::nullableObject($data['banner'] ?? null, "{$path}.banner", TwitterImage::class),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            id: Wire::string($data['id'] ?? '', "{$path}.id"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TwitterListMetrics::class),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            owner: Wire::nullableObject($data['owner'] ?? null, "{$path}.owner", TwitterProfileReference::class),
        );
    }
}
