<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterAspectRatio implements Model
{
    public function __construct(
        public readonly int $height,
        public readonly int $width,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::int($data['height'] ?? 0, "{$path}.height"),
            width: Wire::int($data['width'] ?? 0, "{$path}.width"),
        );
    }
}
