<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterPostReference implements Model
{
    public function __construct(
        public readonly TwitterExtracted $extracted,
        public readonly TwitterPostMetrics $metrics,
        public readonly ?TwitterArticle $article = null,
        public readonly ?TwitterProfileReference $author = null,
        public readonly ?string $authorId = null,
        public readonly ?TwitterCard $card = null,
        public readonly ?TwitterCommunityNote $communityNote = null,
        public readonly ?string $conversationId = null,
        public readonly ?string $createdAt = null,
        public readonly ?TwitterRange $displayTextRange = null,
        public readonly ?TwitterEdit $edit = null,
        /**
         * @var list<TwitterEntity>|null
         */
        public readonly ?array $entities = null,
        public readonly ?bool $hasGrokAnalysisButton = null,
        public readonly ?string $id = null,
        public readonly ?string $inReplyToHandle = null,
        public readonly ?string $inReplyToPostId = null,
        public readonly ?string $inReplyToUserId = null,
        public readonly ?bool $isPromoted = null,
        public readonly ?bool $isQuote = null,
        public readonly ?bool $isRepost = null,
        public readonly ?bool $isSensitive = null,
        public readonly ?string $language = null,
        public readonly ?TwitterLongText $longText = null,
        /**
         * @var list<TwitterMedia>|null
         */
        public readonly ?array $media = null,
        public readonly ?TwitterPreview $preview = null,
        public readonly ?TwitterPreviousMetrics $previousMetrics = null,
        public readonly ?TwitterPromotion $promotion = null,
        public readonly ?TwitterPostReference $quotedPost = null,
        public readonly ?string $quotedPostId = null,
        public readonly ?TwitterPostReference $repostedPost = null,
        /**
         * @var list<TwitterRestriction>|null
         */
        public readonly ?array $restrictions = null,
        public readonly ?string $text = null,
        public readonly ?TwitterTimelinePlacement $timeline = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            article: Wire::nullableObject($data['article'] ?? null, "{$path}.article", TwitterArticle::class),
            author: Wire::nullableObject($data['author'] ?? null, "{$path}.author", TwitterProfileReference::class),
            authorId: Wire::nullableString($data['authorId'] ?? null, "{$path}.authorId"),
            card: Wire::nullableObject($data['card'] ?? null, "{$path}.card", TwitterCard::class),
            communityNote: Wire::nullableObject($data['communityNote'] ?? null, "{$path}.communityNote", TwitterCommunityNote::class),
            conversationId: Wire::nullableString($data['conversationId'] ?? null, "{$path}.conversationId"),
            createdAt: Wire::nullableString($data['createdAt'] ?? null, "{$path}.createdAt"),
            displayTextRange: Wire::nullableObject($data['displayTextRange'] ?? null, "{$path}.displayTextRange", TwitterRange::class),
            edit: Wire::nullableObject($data['edit'] ?? null, "{$path}.edit", TwitterEdit::class),
            entities: Wire::nullableList($data['entities'] ?? null, "{$path}.entities", static fn(mixed $item, string $path): TwitterEntity => Wire::object($item, $path, TwitterEntity::class)),
            extracted: Wire::object($data['extracted'] ?? [], "{$path}.extracted", TwitterExtracted::class),
            hasGrokAnalysisButton: Wire::nullableBool($data['hasGrokAnalysisButton'] ?? null, "{$path}.hasGrokAnalysisButton"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            inReplyToHandle: Wire::nullableString($data['inReplyToHandle'] ?? null, "{$path}.inReplyToHandle"),
            inReplyToPostId: Wire::nullableString($data['inReplyToPostId'] ?? null, "{$path}.inReplyToPostId"),
            inReplyToUserId: Wire::nullableString($data['inReplyToUserId'] ?? null, "{$path}.inReplyToUserId"),
            isPromoted: Wire::nullableBool($data['isPromoted'] ?? null, "{$path}.isPromoted"),
            isQuote: Wire::nullableBool($data['isQuote'] ?? null, "{$path}.isQuote"),
            isRepost: Wire::nullableBool($data['isRepost'] ?? null, "{$path}.isRepost"),
            isSensitive: Wire::nullableBool($data['isSensitive'] ?? null, "{$path}.isSensitive"),
            language: Wire::nullableString($data['language'] ?? null, "{$path}.language"),
            longText: Wire::nullableObject($data['longText'] ?? null, "{$path}.longText", TwitterLongText::class),
            media: Wire::nullableList($data['media'] ?? null, "{$path}.media", static fn(mixed $item, string $path): TwitterMedia => Wire::object($item, $path, TwitterMedia::class)),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TwitterPostMetrics::class),
            preview: Wire::nullableObject($data['preview'] ?? null, "{$path}.preview", TwitterPreview::class),
            previousMetrics: Wire::nullableObject($data['previousMetrics'] ?? null, "{$path}.previousMetrics", TwitterPreviousMetrics::class),
            promotion: Wire::nullableObject($data['promotion'] ?? null, "{$path}.promotion", TwitterPromotion::class),
            quotedPost: Wire::nullableObject($data['quotedPost'] ?? null, "{$path}.quotedPost", TwitterPostReference::class),
            quotedPostId: Wire::nullableString($data['quotedPostId'] ?? null, "{$path}.quotedPostId"),
            repostedPost: Wire::nullableObject($data['repostedPost'] ?? null, "{$path}.repostedPost", TwitterPostReference::class),
            restrictions: Wire::nullableList($data['restrictions'] ?? null, "{$path}.restrictions", static fn(mixed $item, string $path): TwitterRestriction => Wire::object($item, $path, TwitterRestriction::class)),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
            timeline: Wire::nullableObject($data['timeline'] ?? null, "{$path}.timeline", TwitterTimelinePlacement::class),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
