<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterVerification implements Model
{
    public function __construct(
        public readonly ?bool $isBlueVerified = null,
        public readonly ?bool $legacyVerified = null,
        public readonly ?string $type = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            isBlueVerified: Wire::nullableBool($data['isBlueVerified'] ?? null, "{$path}.isBlueVerified"),
            legacyVerified: Wire::nullableBool($data['legacyVerified'] ?? null, "{$path}.legacyVerified"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
        );
    }
}
