<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterPreview implements Model
{
    public function __construct(
        public readonly ?TwitterRange $displayTextRange = null,
        /**
         * @var list<TwitterEntity>|null
         */
        public readonly ?array $entities = null,
        public readonly ?string $text = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            displayTextRange: Wire::nullableObject($data['displayTextRange'] ?? null, "{$path}.displayTextRange", TwitterRange::class),
            entities: Wire::nullableList($data['entities'] ?? null, "{$path}.entities", static fn(mixed $item, string $path): TwitterEntity => Wire::object($item, $path, TwitterEntity::class)),
            text: Wire::nullableString($data['text'] ?? null, "{$path}.text"),
        );
    }
}
