<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterWithheld implements Model
{
    public function __construct(
        public readonly ?bool $copyright = null,
        public readonly ?string $description = null,
        public readonly ?string $scope = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            copyright: Wire::nullableBool($data['copyright'] ?? null, "{$path}.copyright"),
            description: Wire::nullableString($data['description'] ?? null, "{$path}.description"),
            scope: Wire::nullableString($data['scope'] ?? null, "{$path}.scope"),
        );
    }
}
