<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterProfileMetrics implements Model
{
    public function __construct(
        public readonly ?int $affiliates = null,
        public readonly ?int $creatorSubscriptions = null,
        public readonly ?int $followers = null,
        public readonly ?int $following = null,
        public readonly ?int $likedPosts = null,
        public readonly ?int $mediaPosts = null,
        public readonly ?int $posts = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            affiliates: Wire::nullableInt($data['affiliates'] ?? null, "{$path}.affiliates"),
            creatorSubscriptions: Wire::nullableInt($data['creatorSubscriptions'] ?? null, "{$path}.creatorSubscriptions"),
            followers: Wire::nullableInt($data['followers'] ?? null, "{$path}.followers"),
            following: Wire::nullableInt($data['following'] ?? null, "{$path}.following"),
            likedPosts: Wire::nullableInt($data['likedPosts'] ?? null, "{$path}.likedPosts"),
            mediaPosts: Wire::nullableInt($data['mediaPosts'] ?? null, "{$path}.mediaPosts"),
            posts: Wire::nullableInt($data['posts'] ?? null, "{$path}.posts"),
        );
    }
}
