<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterProfileEntities implements Model
{
    public function __construct(
        /**
         * @var list<TwitterEntity>|null
         */
        public readonly ?array $bio = null,
        /**
         * @var list<TwitterEntity>|null
         */
        public readonly ?array $externalUrl = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            bio: Wire::nullableList($data['bio'] ?? null, "{$path}.bio", static fn(mixed $item, string $path): TwitterEntity => Wire::object($item, $path, TwitterEntity::class)),
            externalUrl: Wire::nullableList($data['externalUrl'] ?? null, "{$path}.externalUrl", static fn(mixed $item, string $path): TwitterEntity => Wire::object($item, $path, TwitterEntity::class)),
        );
    }
}
