<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterVisibility implements Model
{
    public function __construct(
        public readonly ?bool $hasHiddenLikesOnProfile = null,
        public readonly ?bool $hasHiddenSubscriptionsOnProfile = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            hasHiddenLikesOnProfile: Wire::nullableBool($data['hasHiddenLikesOnProfile'] ?? null, "{$path}.hasHiddenLikesOnProfile"),
            hasHiddenSubscriptionsOnProfile: Wire::nullableBool($data['hasHiddenSubscriptionsOnProfile'] ?? null, "{$path}.hasHiddenSubscriptionsOnProfile"),
        );
    }
}
