<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterRestriction implements Model
{
    public function __construct(
        public readonly ?string $action = null,
        public readonly ?string $message = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            action: Wire::nullableString($data['action'] ?? null, "{$path}.action"),
            message: Wire::nullableString($data['message'] ?? null, "{$path}.message"),
        );
    }
}
