<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterMediaSize implements Model
{
    public function __construct(
        public readonly ?int $height = null,
        public readonly ?string $name = null,
        public readonly ?string $resizeMode = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            name: Wire::nullableString($data['name'] ?? null, "{$path}.name"),
            resizeMode: Wire::nullableString($data['resizeMode'] ?? null, "{$path}.resizeMode"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
