<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterPoll implements Model
{
    public function __construct(
        public readonly TwitterPollMetrics $metrics,
        /**
         * @var list<TwitterPollChoice>|null
         */
        public readonly ?array $choices = null,
        public readonly ?bool $countsAreFinal = null,
        public readonly ?int $duration = null,
        public readonly ?string $endsAt = null,
        public readonly ?string $updatedAt = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            choices: Wire::nullableList($data['choices'] ?? null, "{$path}.choices", static fn(mixed $item, string $path): TwitterPollChoice => Wire::object($item, $path, TwitterPollChoice::class)),
            countsAreFinal: Wire::nullableBool($data['countsAreFinal'] ?? null, "{$path}.countsAreFinal"),
            duration: Wire::nullableInt($data['duration'] ?? null, "{$path}.duration"),
            endsAt: Wire::nullableString($data['endsAt'] ?? null, "{$path}.endsAt"),
            metrics: Wire::object($data['metrics'] ?? [], "{$path}.metrics", TwitterPollMetrics::class),
            updatedAt: Wire::nullableString($data['updatedAt'] ?? null, "{$path}.updatedAt"),
        );
    }
}
