<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterPostMetrics implements Model
{
    public function __construct(
        public readonly ?int $comments = null,
        public readonly ?int $likes = null,
        public readonly ?int $quotes = null,
        public readonly ?int $reposts = null,
        public readonly ?int $saves = null,
        public readonly ?int $views = null,
        public readonly ?string $viewsState = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            comments: Wire::nullableInt($data['comments'] ?? null, "{$path}.comments"),
            likes: Wire::nullableInt($data['likes'] ?? null, "{$path}.likes"),
            quotes: Wire::nullableInt($data['quotes'] ?? null, "{$path}.quotes"),
            reposts: Wire::nullableInt($data['reposts'] ?? null, "{$path}.reposts"),
            saves: Wire::nullableInt($data['saves'] ?? null, "{$path}.saves"),
            views: Wire::nullableInt($data['views'] ?? null, "{$path}.views"),
            viewsState: Wire::nullableString($data['viewsState'] ?? null, "{$path}.viewsState"),
        );
    }
}
