<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterSubscriptions implements Model
{
    public function __construct(
        public readonly ?bool $isEligible = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            isEligible: Wire::nullableBool($data['isEligible'] ?? null, "{$path}.isEligible"),
        );
    }
}
