<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterCardApp implements Model
{
    public function __construct(
        public readonly ?TwitterCardText $category = null,
        public readonly ?string $countryCode = null,
        public readonly ?TwitterCardText $description = null,
        public readonly ?string $groupId = null,
        public readonly ?bool $hasInAppPurchases = null,
        public readonly ?string $iconKey = null,
        public readonly ?string $id = null,
        public readonly ?bool $isEditorsChoice = null,
        public readonly ?bool $isFree = null,
        public readonly ?TwitterAppMetrics $metrics = null,
        public readonly ?string $resolvedUrl = null,
        public readonly ?int $sizeBytes = null,
        public readonly ?TwitterCardText $title = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            category: Wire::nullableObject($data['category'] ?? null, "{$path}.category", TwitterCardText::class),
            countryCode: Wire::nullableString($data['countryCode'] ?? null, "{$path}.countryCode"),
            description: Wire::nullableObject($data['description'] ?? null, "{$path}.description", TwitterCardText::class),
            groupId: Wire::nullableString($data['groupId'] ?? null, "{$path}.groupId"),
            hasInAppPurchases: Wire::nullableBool($data['hasInAppPurchases'] ?? null, "{$path}.hasInAppPurchases"),
            iconKey: Wire::nullableString($data['iconKey'] ?? null, "{$path}.iconKey"),
            id: Wire::nullableString($data['id'] ?? null, "{$path}.id"),
            isEditorsChoice: Wire::nullableBool($data['isEditorsChoice'] ?? null, "{$path}.isEditorsChoice"),
            isFree: Wire::nullableBool($data['isFree'] ?? null, "{$path}.isFree"),
            metrics: Wire::nullableObject($data['metrics'] ?? null, "{$path}.metrics", TwitterAppMetrics::class),
            resolvedUrl: Wire::nullableString($data['resolvedUrl'] ?? null, "{$path}.resolvedUrl"),
            sizeBytes: Wire::nullableInt($data['sizeBytes'] ?? null, "{$path}.sizeBytes"),
            title: Wire::nullableObject($data['title'] ?? null, "{$path}.title", TwitterCardText::class),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
        );
    }
}
