<?php

// Generated by scripts/generate.php. Do not edit.

declare(strict_types=1);

namespace OpenHandle\Models;

use OpenHandle\Internal\Model;
use OpenHandle\Internal\Wire;

final class TwitterImage implements Model
{
    public function __construct(
        public readonly ?string $altText = null,
        public readonly ?int $height = null,
        public readonly ?bool $isNft = null,
        public readonly ?string $role = null,
        public readonly ?string $shape = null,
        public readonly ?string $type = null,
        public readonly ?string $url = null,
        public readonly ?int $width = null,
    ) {
    }

    /**
     * @param array<string, mixed> $data
     */
    public static function fromArray(array $data, string $path = 'data'): static
    {
        return new self(
            altText: Wire::nullableString($data['altText'] ?? null, "{$path}.altText"),
            height: Wire::nullableInt($data['height'] ?? null, "{$path}.height"),
            isNft: Wire::nullableBool($data['isNft'] ?? null, "{$path}.isNft"),
            role: Wire::nullableString($data['role'] ?? null, "{$path}.role"),
            shape: Wire::nullableString($data['shape'] ?? null, "{$path}.shape"),
            type: Wire::nullableString($data['type'] ?? null, "{$path}.type"),
            url: Wire::nullableString($data['url'] ?? null, "{$path}.url"),
            width: Wire::nullableInt($data['width'] ?? null, "{$path}.width"),
        );
    }
}
